//go:build ignore

package main

import (
	"archive/zip"
	"bytes"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"text/template"
	"time"
	"unicode"
)

const (
	cldrRepoLatestReleaseURL = "https://api.github.com/repos/unicode-org/cldr-json/releases/latest"
	isoURL                   = "https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-one.xml"
)

// rootLocale is the name of the CLDR root locale in the cldr-json data.
const rootLocale = "und"

type Generator struct {
	CLDRVersion   string
	ISOLastUpdate string
	Currencies    map[string]*CurrencyInfo
	Locales       map[string]*LocaleInfo
	// Parents holds the CLDR parent locales that are not found by removing the last subtag.
	Parents map[string]string
	tempDir string
}

type CurrencyInfo struct {
	Code          string // ISO 4217 code (e.g., "USD")
	Number        string // ISO 4217 number (e.g., "840")
	Name          string // Official currency name
	MinorUnits    int    // Number of decimal places
	CashIncrement int64  // Smallest cash amount in minor units
}

type LocaleInfo struct {
	Numbers Numbers
	// Symbols holds the currency symbols that this locale defines, without inherited symbols.
	Symbols map[string]string
}

type Numbers struct {
	CurrencyFormat   string // Currency pattern (e.g., "#,##0.00 ¤")
	GroupSeparator   string // Group separator (e.g., "," in en)
	DecimalSeparator string // Decimal separator (e.g., "." in en)
	MinusSign        string // Minus sign (e.g., "-")
}

// defaultNumbers is the number data of the zero Locale.
var defaultNumbers = Numbers{
	CurrencyFormat:   "#,##0.00 ¤",
	GroupSeparator:   ",",
	DecimalSeparator: ".",
	MinusSign:        "-",
}

const localeTemplate = `// Code generated by generator.go; DO NOT EDIT.

// CLDR Version: {{.CLDRVersion}}

package locale

// Supported locales.
var (
    {{- range .Locales}}
    {{.Var}} = Locale{id: {{.ID}}}
    {{- end}}
)

// localeData holds the CLDR data of each locale, indexed by Locale.id.
// Index 0 holds the data of the zero Locale. The other entries are sorted by code.
var localeData = [...]data{
    {{- range .Data}}
    {code: {{q .Code}}, numbers: Numbers{CurrencyFormat: {{q .Numbers.CurrencyFormat}}, GroupSeparator: {{q .Numbers.GroupSeparator}}, DecimalSeparator: {{q .Numbers.DecimalSeparator}}, MinusSign: {{q .Numbers.MinusSign}}}, symbols: {{.SymbolSet}}},
    {{- end}}
}

// symbolSets holds the currency symbols that are different from the currency code, sorted by code.
var symbolSets = [...][]symbol{
    {{- range .SymbolSets}}
    { {{- range $i, $s := .}}{{if $i}}, {{end}}{ {{- q $s.Code}}, {{q $s.Symbol -}} }{{end -}} },
    {{- end}}
}
`

const currencyTemplate = `// Code generated by generator.go; DO NOT EDIT.

// CLDR Version: {{.CLDRVersion}}
// ISO 4217 Data Last Updated: {{.ISOLastUpdate}}

package currency

import "github.com/khatibomar/fulus/locale"

// builtin holds all generated ISO 4217 currencies, sorted by code.
var builtin = []Currency{
    {{- range .Currencies}}
    {{.Code}}{},
    {{- end}}
}
{{range .Currencies}}
var _ Currency = {{.Code}}{}

// {{.Code}} is the {{.Name}} currency.
type {{.Code}} struct{}

func ({{.Code}}) Code() string { return {{q .Code}} }

func ({{.Code}}) Number() string { return {{q .Number}} }

func ({{.Code}}) Name() string { return {{q .Name}} }

func ({{.Code}}) MinorUnits() int { return {{.MinorUnits}} }

func ({{.Code}}) FormatInfo(loc locale.Locale) FormatInfo { return formatInfo(loc, {{q .Code}}) }
{{- if gt .CashIncrement 1}}

// CashIncrement returns the smallest cash amount in minor units.
func ({{.Code}}) CashIncrement() int64 { return {{.CashIncrement}} }
{{- end}}
{{end -}}
`

func main() {
	tempDir, err := os.MkdirTemp("", "fulus-generator-*")
	if err != nil {
		log.Fatal(err)
	}

	g := &Generator{
		Currencies: make(map[string]*CurrencyInfo),
		Locales:    make(map[string]*LocaleInfo),
		Parents:    make(map[string]string),
		tempDir:    tempDir,
	}

	steps := []func() error{
		g.fetchCLDR,
		g.fetchISO,
		g.processLocales,
		g.processParentLocales,
		g.processCurrencyData,
		g.generateLocales,
		g.generateCurrencies,
	}
	for _, step := range steps {
		if err := step(); err != nil {
			os.RemoveAll(tempDir)
			log.Fatal(err)
		}
	}
	os.RemoveAll(tempDir)
}

func (g *Generator) fetchCLDR() error {
	log.Println("Fetching latest CLDR release info...")

	req, err := http.NewRequest("GET", cldrRepoLatestReleaseURL, nil)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}
	req.Header.Set("Accept", "application/vnd.github.v3+json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return fmt.Errorf("failed to fetch release info: %w", err)
	}
	defer resp.Body.Close()

	var release struct {
		TagName string `json:"tag_name"`
		Assets  []struct {
			Name               string `json:"name"`
			BrowserDownloadURL string `json:"browser_download_url"`
		} `json:"assets"`
	}

	if err := json.NewDecoder(resp.Body).Decode(&release); err != nil {
		return fmt.Errorf("failed to decode release info: %w", err)
	}

	log.Printf("Latest CLDR version: %s", release.TagName)

	var zipURL string
	for _, asset := range release.Assets {
		if strings.HasSuffix(asset.Name, ".zip") {
			zipURL = asset.BrowserDownloadURL
			break
		}
	}

	if zipURL == "" {
		return fmt.Errorf("no zip file found in release %s", release.TagName)
	}

	log.Printf("Downloading CLDR data from %s...", zipURL)

	resp, err = http.Get(zipURL)
	if err != nil {
		return fmt.Errorf("failed to download zip: %w", err)
	}
	defer resp.Body.Close()

	zipFile, err := os.CreateTemp(g.tempDir, "cldr-*.zip")
	if err != nil {
		return fmt.Errorf("failed to create temp zip file: %w", err)
	}
	defer zipFile.Close()

	if _, err := io.Copy(zipFile, resp.Body); err != nil {
		return fmt.Errorf("failed to save zip file: %w", err)
	}

	log.Println("Extracting CLDR data...")

	r, err := zip.OpenReader(zipFile.Name())
	if err != nil {
		return fmt.Errorf("failed to open zip file: %w", err)
	}
	defer r.Close()

	for _, f := range r.File {
		target := filepath.Join(g.tempDir, f.Name)
		if !strings.HasPrefix(target, filepath.Clean(g.tempDir)+string(os.PathSeparator)) {
			return fmt.Errorf("zip entry %s is outside the target directory", f.Name)
		}

		if f.FileInfo().IsDir() {
			if err := os.MkdirAll(target, 0755); err != nil {
				return fmt.Errorf("failed to create directory %s: %w", target, err)
			}
			continue
		}

		if err := extractFile(f, target); err != nil {
			return err
		}
	}

	g.CLDRVersion = release.TagName
	log.Printf("CLDR data extracted successfully")

	requiredDirs := []string{
		"cldr-numbers-full",
		"cldr-core",
	}

	for _, dir := range requiredDirs {
		if _, err := os.Stat(filepath.Join(g.tempDir, dir)); err != nil {
			return fmt.Errorf("required directory %s not found: %w", dir, err)
		}
	}

	return nil
}

func extractFile(f *zip.File, target string) error {
	if err := os.MkdirAll(filepath.Dir(target), 0755); err != nil {
		return fmt.Errorf("failed to create parent directory for %s: %w", target, err)
	}

	outFile, err := os.OpenFile(target, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, f.Mode())
	if err != nil {
		return fmt.Errorf("failed to create file %s: %w", target, err)
	}
	defer outFile.Close()

	rc, err := f.Open()
	if err != nil {
		return fmt.Errorf("failed to open zip file entry %s: %w", f.Name, err)
	}
	defer rc.Close()

	if _, err := io.Copy(outFile, rc); err != nil {
		return fmt.Errorf("failed to extract file %s: %w", f.Name, err)
	}
	return nil
}

func (g *Generator) fetchISO() error {
	log.Println("Fetching ISO currency data...")
	resp, err := http.Get(isoURL)
	if err != nil {
		return fmt.Errorf("fetchISO: %w", err)
	}
	defer resp.Body.Close()

	g.ISOLastUpdate = resp.Header.Get("Last-Modified")
	if g.ISOLastUpdate == "" {
		g.ISOLastUpdate = time.Now().Format("2006-01-02")
	}

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("fetchISO: %w", err)
	}

	type ISOEntry struct {
		Country    string `xml:"CtryNm"`
		Currency   string `xml:"CcyNm"`
		Code       string `xml:"Ccy"`
		Number     string `xml:"CcyNbr"`
		MinorUnits string `xml:"CcyMnrUnts"`
	}

	type ISOData struct {
		Entries []struct {
			Entry []ISOEntry `xml:"CcyNtry"`
		} `xml:"CcyTbl"`
	}

	var iso ISOData
	if err := xml.Unmarshal(data, &iso); err != nil {
		return fmt.Errorf("fetchISO: %w", err)
	}

	for _, table := range iso.Entries {
		for _, entry := range table.Entry {
			if entry.Code == "" || entry.Number == "" {
				continue
			}

			// Skip testing and special purpose codes
			if strings.HasPrefix(entry.Country, "ZZ") {
				continue
			}

			minorUnits := 2
			if entry.MinorUnits != "N.A." {
				if units, err := strconv.Atoi(entry.MinorUnits); err == nil {
					minorUnits = units
				}
			}

			if _, exists := g.Currencies[entry.Code]; !exists {
				g.Currencies[entry.Code] = &CurrencyInfo{
					Code:          entry.Code,
					Number:        entry.Number,
					Name:          entry.Currency,
					MinorUnits:    minorUnits,
					CashIncrement: 1,
				}
			}
		}
	}

	log.Printf("Processed %d currencies", len(g.Currencies))
	return nil
}

func (g *Generator) processLocales() error {
	log.Println("Processing locales...")
	localesPath := filepath.Join(g.tempDir, "cldr-numbers-full", "main")
	entries, err := os.ReadDir(localesPath)
	if err != nil {
		return fmt.Errorf("failed to read locales directory: %w", err)
	}

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		locale := entry.Name()

		numbersData, err := os.ReadFile(filepath.Join(localesPath, locale, "numbers.json"))
		if err != nil {
			log.Printf("Warning: couldn't read numbers.json for %s: %v", locale, err)
			continue
		}

		var numbersFile struct {
			Main map[string]struct {
				Numbers struct {
					Symbols struct {
						Decimal string `json:"decimal"`
						Group   string `json:"group"`
						Minus   string `json:"minusSign"`
					} `json:"symbols-numberSystem-latn"`
					CurrencyFormats struct {
						Standard string `json:"standard"`
					} `json:"currencyFormats-numberSystem-latn"`
				}
			}
		}

		if err := json.Unmarshal(numbersData, &numbersFile); err != nil {
			log.Printf("Warning: couldn't parse numbers.json for %s: %v", locale, err)
			continue
		}

		localeData := numbersFile.Main[locale].Numbers
		info := &LocaleInfo{
			Numbers: Numbers{
				CurrencyFormat:   localeData.CurrencyFormats.Standard,
				GroupSeparator:   localeData.Symbols.Group,
				DecimalSeparator: localeData.Symbols.Decimal,
				MinusSign:        localeData.Symbols.Minus,
			},
			Symbols: make(map[string]string),
		}
		g.Locales[locale] = info

		currenciesData, err := os.ReadFile(filepath.Join(localesPath, locale, "currencies.json"))
		if err != nil {
			log.Printf("Warning: couldn't read currencies.json for %s: %v", locale, err)
			continue
		}

		var currenciesFile struct {
			Main map[string]struct {
				Numbers struct {
					Currencies map[string]struct {
						Symbol    string `json:"symbol"`
						SymbolAlt string `json:"symbol-alt-narrow,omitempty"`
					}
				}
			}
		}

		if err := json.Unmarshal(currenciesData, &currenciesFile); err != nil {
			log.Printf("Warning: couldn't parse currencies.json for %s: %v", locale, err)
			continue
		}

		for code, currencyData := range currenciesFile.Main[locale].Numbers.Currencies {
			if _, exists := g.Currencies[code]; !exists {
				continue
			}
			symbol := currencyData.Symbol
			if symbol == "" {
				symbol = currencyData.SymbolAlt
			}
			if symbol == "" {
				symbol = code
			}
			info.Symbols[code] = symbol
		}
	}

	if _, ok := g.Locales[rootLocale]; !ok {
		return fmt.Errorf("root locale %s not found", rootLocale)
	}

	log.Printf("Processed %d locales", len(g.Locales))
	return nil
}

// processParentLocales reads the CLDR parent locales that are not found by removing the last subtag.
func (g *Generator) processParentLocales() error {
	data, err := os.ReadFile(filepath.Join(g.tempDir, "cldr-core", "supplemental", "parentLocales.json"))
	if err != nil {
		return fmt.Errorf("failed to read parentLocales.json: %w", err)
	}

	var file struct {
		Supplemental struct {
			ParentLocales struct {
				ParentLocale map[string]string `json:"parentLocale"`
			} `json:"parentLocales"`
		} `json:"supplemental"`
	}
	if err := json.Unmarshal(data, &file); err != nil {
		return fmt.Errorf("failed to parse parentLocales.json: %w", err)
	}

	for locale, parent := range file.Supplemental.ParentLocales.ParentLocale {
		if parent == "root" {
			parent = rootLocale
		}
		g.Parents[locale] = parent
	}
	return nil
}

// parent returns the CLDR parent of a locale, or "" for the root locale.
func (g *Generator) parent(locale string) string {
	if locale == rootLocale {
		return ""
	}
	if p, ok := g.Parents[locale]; ok {
		return p
	}
	if i := strings.LastIndex(locale, "-"); i >= 0 {
		return locale[:i]
	}
	return rootLocale
}

// resolveSymbol returns the symbol of a currency in a locale, with CLDR inheritance.
func (g *Generator) resolveSymbol(locale, code string) (string, bool) {
	for l := locale; l != ""; l = g.parent(l) {
		if info, ok := g.Locales[l]; ok {
			if symbol, ok := info.Symbols[code]; ok {
				return symbol, true
			}
		}
	}
	return "", false
}

// processCurrencyData reads the CLDR cash rounding rules.
// The cash increment is cashRounding units of 10^-cashDigits, converted to ISO 4217 minor units.
func (g *Generator) processCurrencyData() error {
	log.Println("Processing currency data...")
	data, err := os.ReadFile(filepath.Join(g.tempDir, "cldr-core", "supplemental", "currencyData.json"))
	if err != nil {
		return fmt.Errorf("failed to read currencyData.json: %w", err)
	}

	type fraction struct {
		Digits       string `json:"_digits"`
		CashDigits   string `json:"_cashDigits"`
		CashRounding string `json:"_cashRounding"`
	}
	var file struct {
		Supplemental struct {
			CurrencyData struct {
				Fractions map[string]fraction `json:"fractions"`
			} `json:"currencyData"`
		} `json:"supplemental"`
	}
	if err := json.Unmarshal(data, &file); err != nil {
		return fmt.Errorf("failed to parse currencyData.json: %w", err)
	}

	atoi := func(s string, fallback int) int {
		if v, err := strconv.Atoi(s); err == nil {
			return v
		}
		return fallback
	}

	for code, info := range g.Currencies {
		f, ok := file.Supplemental.CurrencyData.Fractions[code]
		if !ok || (f.CashDigits == "" && f.CashRounding == "") {
			continue
		}
		cashDigits := atoi(f.CashDigits, atoi(f.Digits, 2))
		if cashDigits > info.MinorUnits {
			continue
		}

		increment := int64(max(atoi(f.CashRounding, 0), 1))
		for range info.MinorUnits - cashDigits {
			increment *= 10
		}
		info.CashIncrement = increment
	}

	return nil
}

type symbolEntry struct {
	Code   string
	Symbol string
}

type localeEntry struct {
	Code      string
	Numbers   Numbers
	SymbolSet int
}

func (g *Generator) generateLocales() error {
	log.Println("Generating locale data...")

	codes := make([]string, 0, len(g.Locales))
	for locale := range g.Locales {
		codes = append(codes, locale)
	}
	sort.Strings(codes)

	currencyCodes := make([]string, 0, len(g.Currencies))
	for code := range g.Currencies {
		currencyCodes = append(currencyCodes, code)
	}
	sort.Strings(currencyCodes)

	var symbolSets [][]symbolEntry
	setIndex := make(map[string]int)
	symbolSetOf := func(locale string) int {
		var set []symbolEntry
		var key strings.Builder
		for _, code := range currencyCodes {
			if symbol, ok := g.resolveSymbol(locale, code); ok && symbol != code {
				set = append(set, symbolEntry{Code: code, Symbol: symbol})
				fmt.Fprintf(&key, "%s=%s\x00", code, symbol)
			}
		}
		if i, ok := setIndex[key.String()]; ok {
			return i
		}
		setIndex[key.String()] = len(symbolSets)
		symbolSets = append(symbolSets, set)
		return len(symbolSets) - 1
	}

	type localeVar struct {
		Var string
		ID  int
	}
	vars := make([]localeVar, 0, len(codes))
	data := []localeEntry{{Code: "", Numbers: defaultNumbers, SymbolSet: symbolSetOf("en")}}
	for i, code := range codes {
		vars = append(vars, localeVar{Var: toIdentifier(code), ID: i + 1})
		data = append(data, localeEntry{Code: code, Numbers: g.Locales[code].Numbers, SymbolSet: symbolSetOf(code)})
	}

	log.Printf("Generating locale data with %d locales and %d symbol sets", len(codes), len(symbolSets))

	return writeTemplate(filepath.Join("locale", "gen_locale.go"), localeTemplate, map[string]any{
		"CLDRVersion": g.CLDRVersion,
		"Locales":     vars,
		"Data":        data,
		"SymbolSets":  symbolSets,
	})
}

func (g *Generator) generateCurrencies() error {
	currencies := make([]*CurrencyInfo, 0, len(g.Currencies))
	for _, info := range g.Currencies {
		currencies = append(currencies, info)
	}
	sort.Slice(currencies, func(i, j int) bool { return currencies[i].Code < currencies[j].Code })

	log.Printf("Generating %d currencies", len(currencies))

	return writeTemplate(filepath.Join("currency", "gen_currencies.go"), currencyTemplate, map[string]any{
		"CLDRVersion":   g.CLDRVersion,
		"ISOLastUpdate": g.ISOLastUpdate,
		"Currencies":    currencies,
	})
}

func writeTemplate(fileName, text string, data any) error {
	tmpl := template.Must(template.New(filepath.Base(fileName)).Funcs(template.FuncMap{
		"q": strconv.Quote,
	}).Parse(text))

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("failed to execute template for %s: %w", fileName, err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("failed to format generated code for %s: %w", fileName, err)
	}

	if err := os.MkdirAll(filepath.Dir(fileName), 0755); err != nil {
		return err
	}
	return os.WriteFile(fileName, formatted, 0644)
}

func toIdentifier(code string) string {
	id := strings.ToUpper(strings.ReplaceAll(code, "-", "_"))
	if unicode.IsDigit(rune(id[0])) {
		id = "_" + id
	}
	return id
}
