// Code generated by currency_generator.go; DO NOT EDIT.

package currency

var _ Currency = BMD{}

type BMD struct{}

func (BMD) Code() string { return "BMD" }

func (BMD) Number() string { return "060" }

func (BMD) Name() string { return "Bermudian Dollar" }

func (BMD) MinorUnits() int { return 2 }

func (BMD) Symbol() string { return "$" }

func (BMD) MinorUnitName() string { return "Cent" }

func (BMD) MinorUnitSymbol() string { return "¢" }
