//go:build ignore

package main

import (
	"fmt"
	"os"
	"strings"
	"text/template"
)

// CurrencyInfo implements the Currency interface
type CurrencyInfo struct {
	Code            string
	Number          string
	Name            string
	MinorUnits      int
	Symbol          string
	MinorUnitName   string
	MinorUnitSymbol string
}

// CurrencyMap maps currency codes to their detailed information
var CurrencyMap = map[string]CurrencyInfo{
	"AED": {
		Code:            "AED",
		Number:          "784",
		Name:            "UAE Dirham",
		MinorUnits:      2,
		Symbol:          "د.إ",
		MinorUnitName:   "Fils",
		MinorUnitSymbol: "فلس",
	},
	"AFN": {
		Code:            "AFN",
		Number:          "971",
		Name:            "Afghani",
		MinorUnits:      2,
		Symbol:          "؋",
		MinorUnitName:   "Pul",
		MinorUnitSymbol: "پول",
	},
	"ALL": {
		Code:            "ALL",
		Number:          "008",
		Name:            "Lek",
		MinorUnits:      2,
		Symbol:          "L",
		MinorUnitName:   "Qindarkë",
		MinorUnitSymbol: "q",
	},
	"AMD": {
		Code:            "AMD",
		Number:          "051",
		Name:            "Armenian Dram",
		MinorUnits:      2,
		Symbol:          "֏",
		MinorUnitName:   "Luma",
		MinorUnitSymbol: "լ",
	},
	"ANG": {
		Code:            "ANG",
		Number:          "532",
		Name:            "Netherlands Antillean Guilder",
		MinorUnits:      2,
		Symbol:          "ƒ",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"AOA": {
		Code:            "AOA",
		Number:          "973",
		Name:            "Kwanza",
		MinorUnits:      2,
		Symbol:          "Kz",
		MinorUnitName:   "Cêntimo",
		MinorUnitSymbol: "c",
	},
	"ARS": {
		Code:            "ARS",
		Number:          "032",
		Name:            "Argentine Peso",
		MinorUnits:      2,
		Symbol:          "$",
		MinorUnitName:   "Centavo",
		MinorUnitSymbol: "¢",
	},
	"AUD": {
		Code:            "AUD",
		Number:          "036",
		Name:            "Australian Dollar",
		MinorUnits:      2,
		Symbol:          "A$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "c",
	},
	"AWG": {
		Code:            "AWG",
		Number:          "533",
		Name:            "Aruban Florin",
		MinorUnits:      2,
		Symbol:          "ƒ",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"AZN": {
		Code:            "AZN",
		Number:          "944",
		Name:            "Azerbaijan Manat",
		MinorUnits:      2,
		Symbol:          "₼",
		MinorUnitName:   "Qəpik",
		MinorUnitSymbol: "qəp",
	},
	"BAM": {
		Code:            "BAM",
		Number:          "977",
		Name:            "Convertible Mark",
		MinorUnits:      2,
		Symbol:          "KM",
		MinorUnitName:   "Fening",
		MinorUnitSymbol: "f",
	},
	"BBD": {
		Code:            "BBD",
		Number:          "052",
		Name:            "Barbados Dollar",
		MinorUnits:      2,
		Symbol:          "$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"BDT": {
		Code:            "BDT",
		Number:          "050",
		Name:            "Taka",
		MinorUnits:      2,
		Symbol:          "৳",
		MinorUnitName:   "Poisha",
		MinorUnitSymbol: "p",
	},
	"BGN": {
		Code:            "BGN",
		Number:          "975",
		Name:            "Bulgarian Lev",
		MinorUnits:      2,
		Symbol:          "лв",
		MinorUnitName:   "Stotinka",
		MinorUnitSymbol: "ст.",
	},
	"BHD": {
		Code:            "BHD",
		Number:          "048",
		Name:            "Bahraini Dinar",
		MinorUnits:      3,
		Symbol:          ".د.ب",
		MinorUnitName:   "Fils",
		MinorUnitSymbol: "فلس",
	},
	"BIF": {
		Code:            "BIF",
		Number:          "108",
		Name:            "Burundi Franc",
		MinorUnits:      0,
		Symbol:          "FBu",
		MinorUnitName:   "Centime",
		MinorUnitSymbol: "",
	},
	"BMD": {
		Code:            "BMD",
		Number:          "060",
		Name:            "Bermudian Dollar",
		MinorUnits:      2,
		Symbol:          "$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"BND": {
		Code:            "BND",
		Number:          "096",
		Name:            "Brunei Dollar",
		MinorUnits:      2,
		Symbol:          "$",
		MinorUnitName:   "Sen",
		MinorUnitSymbol: "¢",
	},
	"BOB": {
		Code:            "BOB",
		Number:          "068",
		Name:            "Boliviano",
		MinorUnits:      2,
		Symbol:          "Bs.",
		MinorUnitName:   "Centavo",
		MinorUnitSymbol: "¢",
	},
	"BRL": {
		Code:            "BRL",
		Number:          "986",
		Name:            "Brazilian Real",
		MinorUnits:      2,
		Symbol:          "R$",
		MinorUnitName:   "Centavo",
		MinorUnitSymbol: "¢",
	},
	"BSD": {
		Code:            "BSD",
		Number:          "044",
		Name:            "Bahamian Dollar",
		MinorUnits:      2,
		Symbol:          "$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"BTN": {
		Code:            "BTN",
		Number:          "064",
		Name:            "Ngultrum",
		MinorUnits:      2,
		Symbol:          "Nu.",
		MinorUnitName:   "Chetrum",
		MinorUnitSymbol: "Ch.",
	},
	"BWP": {
		Code:            "BWP",
		Number:          "072",
		Name:            "Pula",
		MinorUnits:      2,
		Symbol:          "P",
		MinorUnitName:   "Thebe",
		MinorUnitSymbol: "t",
	},
	"BYN": {
		Code:            "BYN",
		Number:          "933",
		Name:            "Belarusian Ruble",
		MinorUnits:      2,
		Symbol:          "Br",
		MinorUnitName:   "Kopek",
		MinorUnitSymbol: "к",
	},
	"BZD": {
		Code:            "BZD",
		Number:          "084",
		Name:            "Belize Dollar",
		MinorUnits:      2,
		Symbol:          "BZ$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"CAD": {
		Code:            "CAD",
		Number:          "124",
		Name:            "Canadian Dollar",
		MinorUnits:      2,
		Symbol:          "C$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"CDF": {
		Code:            "CDF",
		Number:          "976",
		Name:            "Congolese Franc",
		MinorUnits:      2,
		Symbol:          "FC",
		MinorUnitName:   "Centime",
		MinorUnitSymbol: "c",
	},
	"CHF": {
		Code:            "CHF",
		Number:          "756",
		Name:            "Swiss Franc",
		MinorUnits:      2,
		Symbol:          "Fr.",
		MinorUnitName:   "Rappen",
		MinorUnitSymbol: "Rp.",
	},
	"CLP": {
		Code:            "CLP",
		Number:          "152",
		Name:            "Chilean Peso",
		MinorUnits:      0,
		Symbol:          "$",
		MinorUnitName:   "Centavo",
		MinorUnitSymbol: "",
	},
	"CNY": {
		Code:            "CNY",
		Number:          "156",
		Name:            "Yuan Renminbi",
		MinorUnits:      2,
		Symbol:          "¥",
		MinorUnitName:   "Fen",
		MinorUnitSymbol: "分",
	},
	"COP": {
		Code:            "COP",
		Number:          "170",
		Name:            "Colombian Peso",
		MinorUnits:      2,
		Symbol:          "$",
		MinorUnitName:   "Centavo",
		MinorUnitSymbol: "¢",
	},
	"CRC": {
		Code:            "CRC",
		Number:          "188",
		Name:            "Costa Rican Colon",
		MinorUnits:      2,
		Symbol:          "₡",
		MinorUnitName:   "Céntimo",
		MinorUnitSymbol: "¢",
	},
	"CUP": {
		Code:            "CUP",
		Number:          "192",
		Name:            "Cuban Peso",
		MinorUnits:      2,
		Symbol:          "₱",
		MinorUnitName:   "Centavo",
		MinorUnitSymbol: "¢",
	},
	"CVE": {
		Code:            "CVE",
		Number:          "132",
		Name:            "Cabo Verde Escudo",
		MinorUnits:      2,
		Symbol:          "$",
		MinorUnitName:   "Centavo",
		MinorUnitSymbol: "¢",
	},
	"CZK": {
		Code:            "CZK",
		Number:          "203",
		Name:            "Czech Koruna",
		MinorUnits:      2,
		Symbol:          "Kč",
		MinorUnitName:   "Haléř",
		MinorUnitSymbol: "h",
	},
	"DJF": {
		Code:            "DJF",
		Number:          "262",
		Name:            "Djibouti Franc",
		MinorUnits:      0,
		Symbol:          "Fdj",
		MinorUnitName:   "Centime",
		MinorUnitSymbol: "",
	},
	"DKK": {
		Code:            "DKK",
		Number:          "208",
		Name:            "Danish Krone",
		MinorUnits:      2,
		Symbol:          "kr",
		MinorUnitName:   "Øre",
		MinorUnitSymbol: "øre",
	},
	"DOP": {
		Code:            "DOP",
		Number:          "214",
		Name:            "Dominican Peso",
		MinorUnits:      2,
		Symbol:          "RD$",
		MinorUnitName:   "Centavo",
		MinorUnitSymbol: "¢",
	},
	"DZD": {
		Code:            "DZD",
		Number:          "012",
		Name:            "Algerian Dinar",
		MinorUnits:      2,
		Symbol:          "د.ج",
		MinorUnitName:   "Centime",
		MinorUnitSymbol: "",
	},
	"EGP": {
		Code:            "EGP",
		Number:          "818",
		Name:            "Egyptian Pound",
		MinorUnits:      2,
		Symbol:          "£",
		MinorUnitName:   "Piastre",
		MinorUnitSymbol: "Pt",
	},
	"ERN": {
		Code:            "ERN",
		Number:          "232",
		Name:            "Nakfa",
		MinorUnits:      2,
		Symbol:          "Nfk",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"ETB": {
		Code:            "ETB",
		Number:          "230",
		Name:            "Ethiopian Birr",
		MinorUnits:      2,
		Symbol:          "Br",
		MinorUnitName:   "Santim",
		MinorUnitSymbol: "",
	},
	"EUR": {
		Code:            "EUR",
		Number:          "978",
		Name:            "Euro",
		MinorUnits:      2,
		Symbol:          "€",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "c",
	},
	"FJD": {
		Code:            "FJD",
		Number:          "242",
		Name:            "Fiji Dollar",
		MinorUnits:      2,
		Symbol:          "$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"FKP": {
		Code:            "FKP",
		Number:          "238",
		Name:            "Falkland Islands Pound",
		MinorUnits:      2,
		Symbol:          "£",
		MinorUnitName:   "Penny",
		MinorUnitSymbol: "p",
	},
	"GBP": {
		Code:            "GBP",
		Number:          "826",
		Name:            "Pound Sterling",
		MinorUnits:      2,
		Symbol:          "£",
		MinorUnitName:   "Penny",
		MinorUnitSymbol: "p",
	},
	"GEL": {
		Code:            "GEL",
		Number:          "981",
		Name:            "Lari",
		MinorUnits:      2,
		Symbol:          "₾",
		MinorUnitName:   "Tetri",
		MinorUnitSymbol: "თ",
	},
	"GHS": {
		Code:            "GHS",
		Number:          "936",
		Name:            "Ghana Cedi",
		MinorUnits:      2,
		Symbol:          "₵",
		MinorUnitName:   "Pesewa",
		MinorUnitSymbol: "Gp",
	},
	"GIP": {
		Code:            "GIP",
		Number:          "292",
		Name:            "Gibraltar Pound",
		MinorUnits:      2,
		Symbol:          "£",
		MinorUnitName:   "Penny",
		MinorUnitSymbol: "p",
	},
	"GMD": {
		Code:            "GMD",
		Number:          "270",
		Name:            "Dalasi",
		MinorUnits:      2,
		Symbol:          "D",
		MinorUnitName:   "Butut",
		MinorUnitSymbol: "b",
	},
	"GNF": {
		Code:            "GNF",
		Number:          "324",
		Name:            "Guinean Franc",
		MinorUnits:      0,
		Symbol:          "FG",
		MinorUnitName:   "Centime",
		MinorUnitSymbol: "",
	},
	"GTQ": {
		Code:            "GTQ",
		Number:          "320",
		Name:            "Quetzal",
		MinorUnits:      2,
		Symbol:          "Q",
		MinorUnitName:   "Centavo",
		MinorUnitSymbol: "c",
	},
	"GYD": {
		Code:            "GYD",
		Number:          "328",
		Name:            "Guyana Dollar",
		MinorUnits:      2,
		Symbol:          "$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"HKD": {
		Code:            "HKD",
		Number:          "344",
		Name:            "Hong Kong Dollar",
		MinorUnits:      2,
		Symbol:          "HK$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"HNL": {
		Code:            "HNL",
		Number:          "340",
		Name:            "Lempira",
		MinorUnits:      2,
		Symbol:          "L",
		MinorUnitName:   "Centavo",
		MinorUnitSymbol: "¢",
	},
	"HRK": {
		Code:            "HRK",
		Number:          "191",
		Name:            "Croatian Kuna",
		MinorUnits:      2,
		Symbol:          "kn",
		MinorUnitName:   "Lipa",
		MinorUnitSymbol: "lp",
	},
	"HTG": {
		Code:            "HTG",
		Number:          "332",
		Name:            "Gourde",
		MinorUnits:      2,
		Symbol:          "G",
		MinorUnitName:   "Centime",
		MinorUnitSymbol: "c",
	},
	"HUF": {
		Code:            "HUF",
		Number:          "348",
		Name:            "Forint",
		MinorUnits:      2,
		Symbol:          "Ft",
		MinorUnitName:   "Fillér",
		MinorUnitSymbol: "",
	},
	"IDR": {
		Code:            "IDR",
		Number:          "360",
		Name:            "Rupiah",
		MinorUnits:      2,
		Symbol:          "Rp",
		MinorUnitName:   "Sen",
		MinorUnitSymbol: "",
	},
	"ILS": {
		Code:            "ILS",
		Number:          "376",
		Name:            "New Israeli Sheqel",
		MinorUnits:      2,
		Symbol:          "₪",
		MinorUnitName:   "Agora",
		MinorUnitSymbol: "'",
	},
	"INR": {
		Code:            "INR",
		Number:          "356",
		Name:            "Indian Rupee",
		MinorUnits:      2,
		Symbol:          "₹",
		MinorUnitName:   "Paisa",
		MinorUnitSymbol: "p",
	},
	"IQD": {
		Code:            "IQD",
		Number:          "368",
		Name:            "Iraqi Dinar",
		MinorUnits:      3,
		Symbol:          "ع.د",
		MinorUnitName:   "Fils",
		MinorUnitSymbol: "فلس",
	},
	"IRR": {
		Code:            "IRR",
		Number:          "364",
		Name:            "Iranian Rial",
		MinorUnits:      2,
		Symbol:          "﷼",
		MinorUnitName:   "Dinar",
		MinorUnitSymbol: "",
	},
	"ISK": {
		Code:            "ISK",
		Number:          "352",
		Name:            "Iceland Krona",
		MinorUnits:      0,
		Symbol:          "kr",
		MinorUnitName:   "Eyrir",
		MinorUnitSymbol: "",
	},
	"JMD": {
		Code:            "JMD",
		Number:          "388",
		Name:            "Jamaican Dollar",
		MinorUnits:      2,
		Symbol:          "J$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"JOD": {
		Code:            "JOD",
		Number:          "400",
		Name:            "Jordanian Dinar",
		MinorUnits:      3,
		Symbol:          "د.ا",
		MinorUnitName:   "Piastre",
		MinorUnitSymbol: "Pt",
	},
	"JPY": {
		Code:            "JPY",
		Number:          "392",
		Name:            "Yen",
		MinorUnits:      0,
		Symbol:          "¥",
		MinorUnitName:   "Sen",
		MinorUnitSymbol: "",
	},
	"KES": {
		Code:            "KES",
		Number:          "404",
		Name:            "Kenyan Shilling",
		MinorUnits:      2,
		Symbol:          "KSh",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "c",
	},
	"KGS": {
		Code:            "KGS",
		Number:          "417",
		Name:            "Som",
		MinorUnits:      2,
		Symbol:          "сом",
		MinorUnitName:   "Tyiyn",
		MinorUnitSymbol: "т",
	},
	"KHR": {
		Code:            "KHR",
		Number:          "116",
		Name:            "Riel",
		MinorUnits:      2,
		Symbol:          "៛",
		MinorUnitName:   "Sen",
		MinorUnitSymbol: "",
	},
	"KMF": {
		Code:            "KMF",
		Number:          "174",
		Name:            "Comorian Franc",
		MinorUnits:      0,
		Symbol:          "CF",
		MinorUnitName:   "Centime",
		MinorUnitSymbol: "",
	},
	"KPW": {
		Code:            "KPW",
		Number:          "408",
		Name:            "North Korean Won",
		MinorUnits:      2,
		Symbol:          "₩",
		MinorUnitName:   "Chon",
		MinorUnitSymbol: "",
	},
	"KRW": {
		Code:            "KRW",
		Number:          "410",
		Name:            "Won",
		MinorUnits:      0,
		Symbol:          "₩",
		MinorUnitName:   "Jeon",
		MinorUnitSymbol: "",
	},
	"KWD": {
		Code:            "KWD",
		Number:          "414",
		Name:            "Kuwaiti Dinar",
		MinorUnits:      3,
		Symbol:          "د.ك",
		MinorUnitName:   "Fils",
		MinorUnitSymbol: "فلس",
	},
	"KYD": {
		Code:            "KYD",
		Number:          "136",
		Name:            "Cayman Islands Dollar",
		MinorUnits:      2,
		Symbol:          "$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"KZT": {
		Code:            "KZT",
		Number:          "398",
		Name:            "Tenge",
		MinorUnits:      2,
		Symbol:          "₸",
		MinorUnitName:   "Tiyn",
		MinorUnitSymbol: "тн",
	},
	"LAK": {
		Code:            "LAK",
		Number:          "418",
		Name:            "Lao Kip",
		MinorUnits:      2,
		Symbol:          "₭",
		MinorUnitName:   "Att",
		MinorUnitSymbol: "",
	},
	"LBP": {
		Code:            "LBP",
		Number:          "422",
		Name:            "Lebanese Pound",
		MinorUnits:      2,
		Symbol:          "ل.ل",
		MinorUnitName:   "Piastre",
		MinorUnitSymbol: "",
	},
	"LKR": {
		Code:            "LKR",
		Number:          "144",
		Name:            "Sri Lanka Rupee",
		MinorUnits:      2,
		Symbol:          "₨",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"LRD": {
		Code:            "LRD",
		Number:          "430",
		Name:            "Liberian Dollar",
		MinorUnits:      2,
		Symbol:          "$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"LSL": {
		Code:            "LSL",
		Number:          "426",
		Name:            "Loti",
		MinorUnits:      2,
		Symbol:          "L",
		MinorUnitName:   "Sente",
		MinorUnitSymbol: "",
	},
	"LYD": {
		Code:            "LYD",
		Number:          "434",
		Name:            "Libyan Dinar",
		MinorUnits:      3,
		Symbol:          "ل.د",
		MinorUnitName:   "Dirham",
		MinorUnitSymbol: "",
	},
	"MAD": {
		Code:            "MAD",
		Number:          "504",
		Name:            "Moroccan Dirham",
		MinorUnits:      2,
		Symbol:          "د.م.",
		MinorUnitName:   "Centime",
		MinorUnitSymbol: "c",
	},
	"MDL": {
		Code:            "MDL",
		Number:          "498",
		Name:            "Moldovan Leu",
		MinorUnits:      2,
		Symbol:          "L",
		MinorUnitName:   "Ban",
		MinorUnitSymbol: "",
	},
	"MGA": {
		Code:            "MGA",
		Number:          "969",
		Name:            "Malagasy Ariary",
		MinorUnits:      2,
		Symbol:          "Ar",
		MinorUnitName:   "Iraimbilanja",
		MinorUnitSymbol: "",
	},
	"MKD": {
		Code:            "MKD",
		Number:          "807",
		Name:            "Denar",
		MinorUnits:      2,
		Symbol:          "ден",
		MinorUnitName:   "Deni",
		MinorUnitSymbol: "",
	},
	"MMK": {
		Code:            "MMK",
		Number:          "104",
		Name:            "Kyat",
		MinorUnits:      2,
		Symbol:          "K",
		MinorUnitName:   "Pya",
		MinorUnitSymbol: "",
	},
	"MNT": {
		Code:            "MNT",
		Number:          "496",
		Name:            "Tugrik",
		MinorUnits:      2,
		Symbol:          "₮",
		MinorUnitName:   "Möngö",
		MinorUnitSymbol: "",
	},
	"MOP": {
		Code:            "MOP",
		Number:          "446",
		Name:            "Pataca",
		MinorUnits:      2,
		Symbol:          "MOP$",
		MinorUnitName:   "Avo",
		MinorUnitSymbol: "",
	},
	"MRU": {
		Code:            "MRU",
		Number:          "929",
		Name:            "Ouguiya",
		MinorUnits:      2,
		Symbol:          "UM",
		MinorUnitName:   "Khoums",
		MinorUnitSymbol: "",
	},
	"MUR": {
		Code:            "MUR",
		Number:          "480",
		Name:            "Mauritius Rupee",
		MinorUnits:      2,
		Symbol:          "₨",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"MVR": {
		Code:            "MVR",
		Number:          "462",
		Name:            "Rufiyaa",
		MinorUnits:      2,
		Symbol:          "Rf",
		MinorUnitName:   "Laari",
		MinorUnitSymbol: "",
	},
	"MWK": {
		Code:            "MWK",
		Number:          "454",
		Name:            "Malawi Kwacha",
		MinorUnits:      2,
		Symbol:          "MK",
		MinorUnitName:   "Tambala",
		MinorUnitSymbol: "t",
	},
	"MXN": {
		Code:            "MXN",
		Number:          "484",
		Name:            "Mexican Peso",
		MinorUnits:      2,
		Symbol:          "$",
		MinorUnitName:   "Centavo",
		MinorUnitSymbol: "¢",
	},
	"MYR": {
		Code:            "MYR",
		Number:          "458",
		Name:            "Malaysian Ringgit",
		MinorUnits:      2,
		Symbol:          "RM",
		MinorUnitName:   "Sen",
		MinorUnitSymbol: "sen",
	},
	"MZN": {
		Code:            "MZN",
		Number:          "943",
		Name:            "Mozambique Metical",
		MinorUnits:      2,
		Symbol:          "MT",
		MinorUnitName:   "Centavo",
		MinorUnitSymbol: "c",
	},
	"NAD": {
		Code:            "NAD",
		Number:          "516",
		Name:            "Namibia Dollar",
		MinorUnits:      2,
		Symbol:          "$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"NGN": {
		Code:            "NGN",
		Number:          "566",
		Name:            "Naira",
		MinorUnits:      2,
		Symbol:          "₦",
		MinorUnitName:   "Kobo",
		MinorUnitSymbol: "k",
	},
	"NIO": {
		Code:            "NIO",
		Number:          "558",
		Name:            "Cordoba Oro",
		MinorUnits:      2,
		Symbol:          "C$",
		MinorUnitName:   "Centavo",
		MinorUnitSymbol: "¢",
	},
	"NOK": {
		Code:            "NOK",
		Number:          "578",
		Name:            "Norwegian Krone",
		MinorUnits:      2,
		Symbol:          "kr",
		MinorUnitName:   "Øre",
		MinorUnitSymbol: "øre",
	},
	"NPR": {
		Code:            "NPR",
		Number:          "524",
		Name:            "Nepalese Rupee",
		MinorUnits:      2,
		Symbol:          "₨",
		MinorUnitName:   "Paisa",
		MinorUnitSymbol: "p",
	},
	"NZD": {
		Code:            "NZD",
		Number:          "554",
		Name:            "New Zealand Dollar",
		MinorUnits:      2,
		Symbol:          "$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "c",
	},
	"OMR": {
		Code:            "OMR",
		Number:          "512",
		Name:            "Rial Omani",
		MinorUnits:      3,
		Symbol:          "ر.ع.",
		MinorUnitName:   "Baisa",
		MinorUnitSymbol: "بيسة",
	},
	"PAB": {
		Code:            "PAB",
		Number:          "590",
		Name:            "Balboa",
		MinorUnits:      2,
		Symbol:          "B/.",
		MinorUnitName:   "Centésimo",
		MinorUnitSymbol: "¢",
	},
	"PEN": {
		Code:            "PEN",
		Number:          "604",
		Name:            "Sol",
		MinorUnits:      2,
		Symbol:          "S/",
		MinorUnitName:   "Céntimo",
		MinorUnitSymbol: "¢",
	},
	"PGK": {
		Code:            "PGK",
		Number:          "598",
		Name:            "Kina",
		MinorUnits:      2,
		Symbol:          "K",
		MinorUnitName:   "Toea",
		MinorUnitSymbol: "t",
	},
	"PHP": {
		Code:            "PHP",
		Number:          "608",
		Name:            "Philippine Peso",
		MinorUnits:      2,
		Symbol:          "₱",
		MinorUnitName:   "Centavo",
		MinorUnitSymbol: "¢",
	},
	"PKR": {
		Code:            "PKR",
		Number:          "586",
		Name:            "Pakistan Rupee",
		MinorUnits:      2,
		Symbol:          "₨",
		MinorUnitName:   "Paisa",
		MinorUnitSymbol: "p",
	},
	"PLN": {
		Code:            "PLN",
		Number:          "985",
		Name:            "Zloty",
		MinorUnits:      2,
		Symbol:          "zł",
		MinorUnitName:   "Grosz",
		MinorUnitSymbol: "gr",
	},
	"PYG": {
		Code:            "PYG",
		Number:          "600",
		Name:            "Guarani",
		MinorUnits:      0,
		Symbol:          "₲",
		MinorUnitName:   "Céntimo",
		MinorUnitSymbol: "",
	},
	"QAR": {
		Code:            "QAR",
		Number:          "634",
		Name:            "Qatari Rial",
		MinorUnits:      2,
		Symbol:          "ر.ق",
		MinorUnitName:   "Dirham",
		MinorUnitSymbol: "dr",
	},
	"RON": {
		Code:            "RON",
		Number:          "946",
		Name:            "Romanian Leu",
		MinorUnits:      2,
		Symbol:          "lei",
		MinorUnitName:   "Ban",
		MinorUnitSymbol: "b",
	},
	"RSD": {
		Code:            "RSD",
		Number:          "941",
		Name:            "Serbian Dinar",
		MinorUnits:      2,
		Symbol:          "дин.",
		MinorUnitName:   "Para",
		MinorUnitSymbol: "п",
	},
	"RUB": {
		Code:            "RUB",
		Number:          "643",
		Name:            "Russian Ruble",
		MinorUnits:      2,
		Symbol:          "₽",
		MinorUnitName:   "Kopek",
		MinorUnitSymbol: "к",
	},
	"RWF": {
		Code:            "RWF",
		Number:          "646",
		Name:            "Rwanda Franc",
		MinorUnits:      0,
		Symbol:          "FRw",
		MinorUnitName:   "Centime",
		MinorUnitSymbol: "",
	},
	"SAR": {
		Code:            "SAR",
		Number:          "682",
		Name:            "Saudi Riyal",
		MinorUnits:      2,
		Symbol:          "ر.س",
		MinorUnitName:   "Halala",
		MinorUnitSymbol: "ه",
	},
	"SBD": {
		Code:            "SBD",
		Number:          "090",
		Name:            "Solomon Islands Dollar",
		MinorUnits:      2,
		Symbol:          "$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"SCR": {
		Code:            "SCR",
		Number:          "690",
		Name:            "Seychelles Rupee",
		MinorUnits:      2,
		Symbol:          "₨",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"SDG": {
		Code:            "SDG",
		Number:          "938",
		Name:            "Sudanese Pound",
		MinorUnits:      2,
		Symbol:          "ج.س.",
		MinorUnitName:   "Piastre",
		MinorUnitSymbol: "",
	},
	"SEK": {
		Code:            "SEK",
		Number:          "752",
		Name:            "Swedish Krona",
		MinorUnits:      2,
		Symbol:          "kr",
		MinorUnitName:   "Öre",
		MinorUnitSymbol: "öre",
	},
	"SGD": {
		Code:            "SGD",
		Number:          "702",
		Name:            "Singapore Dollar",
		MinorUnits:      2,
		Symbol:          "$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"SHP": {
		Code:            "SHP",
		Number:          "654",
		Name:            "Saint Helena Pound",
		MinorUnits:      2,
		Symbol:          "£",
		MinorUnitName:   "Penny",
		MinorUnitSymbol: "p",
	},
	"SLL": {
		Code:            "SLL",
		Number:          "694",
		Name:            "Leone",
		MinorUnits:      2,
		Symbol:          "Le",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "c",
	},
	"SOS": {
		Code:            "SOS",
		Number:          "706",
		Name:            "Somali Shilling",
		MinorUnits:      2,
		Symbol:          "Sh",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"SRD": {
		Code:            "SRD",
		Number:          "968",
		Name:            "Surinam Dollar",
		MinorUnits:      2,
		Symbol:          "$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"SSP": {
		Code:            "SSP",
		Number:          "728",
		Name:            "South Sudanese Pound",
		MinorUnits:      2,
		Symbol:          "£",
		MinorUnitName:   "Piastre",
		MinorUnitSymbol: "",
	},
	"STN": {
		Code:            "STN",
		Number:          "930",
		Name:            "Dobra",
		MinorUnits:      2,
		Symbol:          "Db",
		MinorUnitName:   "Cêntimo",
		MinorUnitSymbol: "",
	},
	"SVC": {
		Code:            "SVC",
		Number:          "222",
		Name:            "El Salvador Colon",
		MinorUnits:      2,
		Symbol:          "₡",
		MinorUnitName:   "Centavo",
		MinorUnitSymbol: "¢",
	},
	"SYP": {
		Code:            "SYP",
		Number:          "760",
		Name:            "Syrian Pound",
		MinorUnits:      2,
		Symbol:          "£S",
		MinorUnitName:   "Piastre",
		MinorUnitSymbol: "",
	},
	"SZL": {
		Code:            "SZL",
		Number:          "748",
		Name:            "Lilangeni",
		MinorUnits:      2,
		Symbol:          "L",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"THB": {
		Code:            "THB",
		Number:          "764",
		Name:            "Baht",
		MinorUnits:      2,
		Symbol:          "฿",
		MinorUnitName:   "Satang",
		MinorUnitSymbol: "สต.",
	},
	"TJS": {
		Code:            "TJS",
		Number:          "972",
		Name:            "Somoni",
		MinorUnits:      2,
		Symbol:          "SM",
		MinorUnitName:   "Diram",
		MinorUnitSymbol: "",
	},
	"TMT": {
		Code:            "TMT",
		Number:          "934",
		Name:            "Turkmenistan New Manat",
		MinorUnits:      2,
		Symbol:          "T",
		MinorUnitName:   "Tennesi",
		MinorUnitSymbol: "t",
	},
	"TND": {
		Code:            "TND",
		Number:          "788",
		Name:            "Tunisian Dinar",
		MinorUnits:      3,
		Symbol:          "د.ت",
		MinorUnitName:   "Millime",
		MinorUnitSymbol: "",
	},
	"TOP": {
		Code:            "TOP",
		Number:          "776",
		Name:            "Pa'anga",
		MinorUnits:      2,
		Symbol:          "T$",
		MinorUnitName:   "Seniti",
		MinorUnitSymbol: "¢",
	},
	"TRY": {
		Code:            "TRY",
		Number:          "949",
		Name:            "Turkish Lira",
		MinorUnits:      2,
		Symbol:          "₺",
		MinorUnitName:   "Kuruş",
		MinorUnitSymbol: "Kr",
	},
	"TTD": {
		Code:            "TTD",
		Number:          "780",
		Name:            "Trinidad and Tobago Dollar",
		MinorUnits:      2,
		Symbol:          "TT$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"TWD": {
		Code:            "TWD",
		Number:          "901",
		Name:            "New Taiwan Dollar",
		MinorUnits:      2,
		Symbol:          "NT$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"TZS": {
		Code:            "TZS",
		Number:          "834",
		Name:            "Tanzanian Shilling",
		MinorUnits:      2,
		Symbol:          "TSh",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "c",
	},
	"UAH": {
		Code:            "UAH",
		Number:          "980",
		Name:            "Hryvnia",
		MinorUnits:      2,
		Symbol:          "₴",
		MinorUnitName:   "Kopiyka",
		MinorUnitSymbol: "к",
	},
	"UGX": {
		Code:            "UGX",
		Number:          "800",
		Name:            "Uganda Shilling",
		MinorUnits:      0,
		Symbol:          "USh",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "",
	},
	"USD": {
		Code:            "USD",
		Number:          "840",
		Name:            "US Dollar",
		MinorUnits:      2,
		Symbol:          "$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"UYU": {
		Code:            "UYU",
		Number:          "858",
		Name:            "Peso Uruguayo",
		MinorUnits:      2,
		Symbol:          "$U",
		MinorUnitName:   "Centésimo",
		MinorUnitSymbol: "¢",
	},
	"UZS": {
		Code:            "UZS",
		Number:          "860",
		Name:            "Uzbekistan Sum",
		MinorUnits:      2,
		Symbol:          "сўм",
		MinorUnitName:   "Tiyin",
		MinorUnitSymbol: "",
	},
	"VES": {
		Code:            "VES",
		Number:          "928",
		Name:            "Bolívar Soberano",
		MinorUnits:      2,
		Symbol:          "Bs.",
		MinorUnitName:   "Céntimo",
		MinorUnitSymbol: "¢",
	},
	"VND": {
		Code:            "VND",
		Number:          "704",
		Name:            "Dong",
		MinorUnits:      0,
		Symbol:          "₫",
		MinorUnitName:   "Hào",
		MinorUnitSymbol: "",
	},
	"VUV": {
		Code:            "VUV",
		Number:          "548",
		Name:            "Vatu",
		MinorUnits:      0,
		Symbol:          "VT",
		MinorUnitName:   "",
		MinorUnitSymbol: "",
	},
	"WST": {
		Code:            "WST",
		Number:          "882",
		Name:            "Tala",
		MinorUnits:      2,
		Symbol:          "WS$",
		MinorUnitName:   "Sene",
		MinorUnitSymbol: "s",
	},
	"XAF": {
		Code:            "XAF",
		Number:          "950",
		Name:            "CFA Franc BEAC",
		MinorUnits:      0,
		Symbol:          "FCFA",
		MinorUnitName:   "Centime",
		MinorUnitSymbol: "",
	},
	"XAG": {
		Code:            "XAG",
		Number:          "961",
		Name:            "Silver",
		MinorUnits:      0,
		Symbol:          "Ag",
		MinorUnitName:   "",
		MinorUnitSymbol: "",
	},
	"XAU": {
		Code:            "XAU",
		Number:          "959",
		Name:            "Gold",
		MinorUnits:      0,
		Symbol:          "Au",
		MinorUnitName:   "",
		MinorUnitSymbol: "",
	},
	"XCD": {
		Code:            "XCD",
		Number:          "951",
		Name:            "East Caribbean Dollar",
		MinorUnits:      2,
		Symbol:          "EC$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"XDR": {
		Code:            "XDR",
		Number:          "960",
		Name:            "SDR (Special Drawing Right)",
		MinorUnits:      0,
		Symbol:          "SDR",
		MinorUnitName:   "",
		MinorUnitSymbol: "",
	},
	"XOF": {
		Code:            "XOF",
		Number:          "952",
		Name:            "CFA Franc BCEAO",
		MinorUnits:      0,
		Symbol:          "CFA",
		MinorUnitName:   "Centime",
		MinorUnitSymbol: "",
	},
	"XPD": {
		Code:            "XPD",
		Number:          "964",
		Name:            "Palladium",
		MinorUnits:      0,
		Symbol:          "Pd",
		MinorUnitName:   "",
		MinorUnitSymbol: "",
	},
	"XPF": {
		Code:            "XPF",
		Number:          "953",
		Name:            "CFP Franc",
		MinorUnits:      0,
		Symbol:          "₣",
		MinorUnitName:   "Centime",
		MinorUnitSymbol: "",
	},
	"XPT": {
		Code:            "XPT",
		Number:          "962",
		Name:            "Platinum",
		MinorUnits:      0,
		Symbol:          "Pt",
		MinorUnitName:   "",
		MinorUnitSymbol: "",
	},
	"YER": {
		Code:            "YER",
		Number:          "886",
		Name:            "Yemeni Rial",
		MinorUnits:      2,
		Symbol:          "﷼",
		MinorUnitName:   "Fils",
		MinorUnitSymbol: "",
	},
	"ZAR": {
		Code:            "ZAR",
		Number:          "710",
		Name:            "Rand",
		MinorUnits:      2,
		Symbol:          "R",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "c",
	},
	"ZMW": {
		Code:            "ZMW",
		Number:          "967",
		Name:            "Zambian Kwacha",
		MinorUnits:      2,
		Symbol:          "ZK",
		MinorUnitName:   "Ngwee",
		MinorUnitSymbol: "n",
	},
	"ZWL": {
		Code:            "ZWL",
		Number:          "932",
		Name:            "Zimbabwe Dollar",
		MinorUnits:      2,
		Symbol:          "$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"BOV": {
		Code:            "BOV",
		Number:          "984",
		Name:            "Mvdol",
		MinorUnits:      2,
		Symbol:          "BOV",
		MinorUnitName:   "Centavo",
		MinorUnitSymbol: "",
	},
	"CHE": {
		Code:            "CHE",
		Number:          "947",
		Name:            "WIR Euro",
		MinorUnits:      2,
		Symbol:          "CHE",
		MinorUnitName:   "Rappen",
		MinorUnitSymbol: "",
	},
	"CHW": {
		Code:            "CHW",
		Number:          "948",
		Name:            "WIR Franc",
		MinorUnits:      2,
		Symbol:          "CHW",
		MinorUnitName:   "Rappen",
		MinorUnitSymbol: "",
	},
	"CLF": {
		Code:            "CLF",
		Number:          "990",
		Name:            "Unidad de Fomento",
		MinorUnits:      4,
		Symbol:          "CLF",
		MinorUnitName:   "Centésimo",
		MinorUnitSymbol: "",
	},
	"COU": {
		Code:            "COU",
		Number:          "970",
		Name:            "Unidad de Valor Real",
		MinorUnits:      2,
		Symbol:          "COU",
		MinorUnitName:   "Centavo",
		MinorUnitSymbol: "",
	},
	"MXV": {
		Code:            "MXV",
		Number:          "979",
		Name:            "Mexican Unidad de Inversion (UDI)",
		MinorUnits:      2,
		Symbol:          "MXV",
		MinorUnitName:   "Centavo",
		MinorUnitSymbol: "",
	},
	"USN": {
		Code:            "USN",
		Number:          "997",
		Name:            "US Dollar (Next day)",
		MinorUnits:      2,
		Symbol:          "$",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
	"UYI": {
		Code:            "UYI",
		Number:          "940",
		Name:            "Uruguay Peso en Unidades Indexadas (UI)",
		MinorUnits:      0,
		Symbol:          "UYI",
		MinorUnitName:   "",
		MinorUnitSymbol: "",
	},
	"UYW": {
		Code:            "UYW",
		Number:          "927",
		Name:            "Unidad Previsional",
		MinorUnits:      4,
		Symbol:          "UP",
		MinorUnitName:   "Céntimo",
		MinorUnitSymbol: "",
	},
	"VED": {
		Code:            "VED",
		Number:          "926",
		Name:            "Bolívar Soberano",
		MinorUnits:      2,
		Symbol:          "Bs.",
		MinorUnitName:   "Céntimo",
		MinorUnitSymbol: "¢",
	},
	"XBA": {
		Code:            "XBA",
		Number:          "955",
		Name:            "Bond Markets Unit European Composite Unit (EURCO)",
		MinorUnits:      0,
		Symbol:          "XBA",
		MinorUnitName:   "",
		MinorUnitSymbol: "",
	},
	"XBB": {
		Code:            "XBB",
		Number:          "956",
		Name:            "Bond Markets Unit European Monetary Unit (E.M.U.-6)",
		MinorUnits:      0,
		Symbol:          "XBB",
		MinorUnitName:   "",
		MinorUnitSymbol: "",
	},
	"XBC": {
		Code:            "XBC",
		Number:          "957",
		Name:            "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)",
		MinorUnits:      0,
		Symbol:          "XBC",
		MinorUnitName:   "",
		MinorUnitSymbol: "",
	},
	"XBD": {
		Code:            "XBD",
		Number:          "958",
		Name:            "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)",
		MinorUnits:      0,
		Symbol:          "XBD",
		MinorUnitName:   "",
		MinorUnitSymbol: "",
	},
	"XSU": {
		Code:            "XSU",
		Number:          "994",
		Name:            "Sucre",
		MinorUnits:      0,
		Symbol:          "XSU",
		MinorUnitName:   "",
		MinorUnitSymbol: "",
	},
	"XTS": {
		Code:            "XTS",
		Number:          "963",
		Name:            "Codes specifically reserved for testing purposes",
		MinorUnits:      0,
		Symbol:          "XTS",
		MinorUnitName:   "",
		MinorUnitSymbol: "",
	},
	"XUA": {
		Code:            "XUA",
		Number:          "965",
		Name:            "ADB Unit of Account",
		MinorUnits:      0,
		Symbol:          "XUA",
		MinorUnitName:   "",
		MinorUnitSymbol: "",
	},
	"ZWG": {
		Code:            "ZWG",
		Number:          "924",
		Name:            "Zimbabwe Gold",
		MinorUnits:      2,
		Symbol:          "ZWG",
		MinorUnitName:   "Cent",
		MinorUnitSymbol: "¢",
	},
}

const currencyTemplate = `// Code generated by currency_generator.go; DO NOT EDIT.

package currency

var _ Currency = {{.Code}}{}

type {{.Code}} struct{}

func ({{.Code}}) Code() string { return "{{.Code}}" }

func ({{.Code}}) Number() string { return "{{.Number}}" }

func ({{.Code}}) Name() string { return "{{.Name}}" }

func ({{.Code}}) MinorUnits() int { return {{.MinorUnits}} }

func ({{.Code}}) Symbol() string { return "{{.Symbol}}" }

func ({{.Code}}) MinorUnitName() string { return "{{.MinorUnitName}}" }

func ({{.Code}}) MinorUnitSymbol() string { return "{{.MinorUnitSymbol}}" }
`

func main() {
	tmpl := template.Must(template.New("currency").Parse(currencyTemplate))

	for code, info := range CurrencyMap {
		fileName := strings.ToLower(code) + ".go"
		file, err := os.Create(fileName)
		if err != nil {
			fmt.Printf("Error creating file %s: %v\n", fileName, err)
			continue
		}

		err = tmpl.Execute(file, info)
		if err != nil {
			fmt.Printf("Error executing template for %s: %v\n", code, err)
		}

		file.Close()
		fmt.Printf("Generated %s\n", fileName)
	}
}
