// Code generated by currency_generator.go; DO NOT EDIT.

package currency

var _ Currency = GBP{}

type GBP struct{}

func (GBP) Code() string { return "GBP" }

func (GBP) Number() string { return "826" }

func (GBP) Name() string { return "Pound Sterling" }

func (GBP) MinorUnits() int { return 2 }

func (GBP) Symbol() string { return "£" }

func (GBP) MinorUnitName() string { return "Penny" }

func (GBP) MinorUnitSymbol() string { return "p" }
