// Code generated by generator.go; DO NOT EDIT.

// CLDR Version: 48.2.3
// ISO 4217 Data Last Updated: Thu, 01 Oct 2026 03:00:58 GMT

package currency

import "github.com/khatibomar/fulus/locale"

var _ Currency = MUR{}

// Mauritius Rupee currency type
type MUR struct{}

func (MUR) Code() string { return "MUR" }

func (MUR) Number() string { return "480" }

func (MUR) Name() string { return "Mauritius Rupee" }

func (MUR) MinorUnits() int { return 2 }

func (MUR) FormatInfo(localeType locale.Locale) FormatInfo {
	switch localeType {
	// Group of 151 locales
	case locale.ANN, locale.RIF, locale.OKA, locale.AN, locale.LA, locale.OKA_US, locale.QU, locale.SMS, locale.BEW, locale.LRC, locale.MWW, locale.BAL_ARAB, locale.KAJ, locale.MDF, locale.NY, locale.EN_SHAW, locale.TA_SG, locale.WAL, locale.RAJ, locale.CO, locale.KAA_CYRL, locale.BO, locale.RHG_ROHG_BD, locale.KAA, locale.AZ_ARAB_IQ, locale.BSS, locale.BQI, locale.CU, locale.NV, locale.PAP_AW, locale.MZN, locale.HA_ARAB_SD, locale.KK_ARAB, locale.LAG, locale.SW_KE, locale.WBP, locale.MAI, locale.SAT_OLCK, locale.SHN, locale.SW_UG, locale.SYR, locale.IU, locale.MN, locale.MNI, locale.IO, locale.LKT, locale.HNJ, locale.SUZ_SUNU, locale.SMJ, locale.VO, locale.SD, locale.SYR_SY, locale.BO_IN, locale.MYV, locale.SMA, locale.TA_MY, locale.GN, locale.PAP, locale.SDH_IQ, locale.HA_NE, locale.KU_ARAB, locale.QU_EC, locale.QUC, locale.IU_LATN, locale.BAL, locale.SUZ_DEVA, locale.MOH, locale.ZH_LATN, locale.PI_LATN, locale.SD_DEVA, locale.AB, locale.LTG, locale.AA, locale.HA_GH, locale.TRV, locale.TRW, locale.HA, locale.KPE_GN, locale.SSY, locale.CCH, locale.MNI_MTEI, locale.RHG_ROHG, locale.MN_MONG, locale.ES_PE, locale.DV, locale.OSA, locale.KPE, locale.HNJ_HMNP, locale.ARN, locale.FRR, locale.SUZ, locale.MUS, locale.GEZ_ER, locale.SD_ARAB, locale.SMA_NO, locale.AA_ER, locale.KEK, locale.RHG, locale.CKB, locale.AZ_ARAB_TR, locale.KCG, locale.SW, locale.MIC, locale.KAA_LATN, locale.KS_DEVA, locale.SGS, locale.EN_DSRT, locale.SHN_TH, locale.BYN, locale.GAA, locale.SKR, locale.CHO, locale.TO, locale.CIC, locale.PIS, locale.LRC_IQ, locale.NSO, locale.TIG, locale.CSW, locale.SDH, locale.APC, locale.SID, locale.SAT_DEVA, locale.YI, locale.JBO, locale.SAT, locale.MG, locale.MI, locale.AZ_ARAB, locale.MNI_BENG, locale.HA_ARAB, locale.PI, locale.MGO, locale.WA, locale.BM_NKOO, locale.CAD, locale.MWW_HMNP, locale.KEN, locale.MHN, locale.UND, locale.LZZ, locale.GEZ, locale.ZA, locale.BGC, locale.BLT, locale.CKB_IR, locale.II, locale.AA_DJ, locale.KU_ARAB_IR, locale.COP, locale.SMJ_NO:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 103 locales
	case locale.KO_KP, locale.KDE, locale.GV, locale.KAM, locale.YUE_HANS, locale.UG, locale.BM, locale.ROF, locale.TEO, locale.GUZ, locale.YO, locale.MS_ARAB, locale.ES_419, locale.GA_GB, locale.ZH_HANS_MO, locale.CGG, locale.MS_SG, locale.ZH_HANS_SG, locale.JA, locale.ZH_HANT_HK, locale.ES_HN, locale.ZU, locale.ES_MX, locale.KLN, locale.MAS, locale.CHR, locale.MS, locale.TI, locale.KO_CN, locale.ZH_HANS_HK, locale.FIL, locale.KO, locale.BEM, locale.YUE, locale.ES_PR, locale.AK, locale.SAQ, locale.SO_KE, locale.JMC, locale.IG, locale.YUE_HANT_MO, locale.ES_CU, locale.MT, locale.SO_DJ, locale.YUE_HANT_CN, locale.EE_TG, locale.ZH_HANS_MY, locale.YO_BJ, locale.ZH_HANT_MY, locale.ZH, locale.CEB, locale.AM, locale.ES_US, locale.CY, locale.MR, locale.NYN, locale.MN_MONG_MN, locale.OM_KE, locale.ES_DO, locale.SN, locale.VAI_VAII, locale.MAS_TZ, locale.OR, locale.ML, locale.YUE_HANT, locale.EE, locale.TEO_KE, locale.SO_ET, locale.VAI, locale.TI_ER, locale.SO, locale.KW, locale.MER, locale.OM, locale.ST, locale.BHO, locale.ZH_HANT_MO, locale.PCM, locale.ST_LS, locale.ZH_HANT, locale.SI, locale.ES_BZ, locale.ES_SV, locale.KN, locale.KI, locale.ZH_HANS, locale.ND, locale.EN_MU, locale.TH, locale.DAV, locale.EBU, locale.ES_GT, locale.GD, locale.GA, locale.DOI, locale.NUS, locale.ES_PA, locale.VUN, locale.ES_BR, locale.VAI_LATN, locale.NAQ, locale.ES_NI, locale.HAW:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 94 locales
	case locale.EN_GM, locale.EN_TO, locale.EN_KI, locale.EN_LS, locale.EN_VI, locale.EN_MY, locale.EN_PN, locale.EN_SS, locale.EN_AS, locale.EN_GD, locale.EN_CK, locale.EN_SL, locale.EN_FK, locale.EN_SX, locale.EN_GY, locale.EN_MW, locale.EN_SG, locale.EN_UG, locale.EN_FM, locale.EN_MO, locale.EN_AU, locale.EN_CA, locale.EN_JE, locale.EN_MT, locale.EN_MP, locale.EN_TT, locale.EN_NF, locale.EN_SH, locale.EN_CY, locale.EN_001, locale.EN_TV, locale.EN_BW, locale.EN_IL, locale.EN_NG, locale.EN_BS, locale.EN_PG, locale.EN_AI, locale.EN_BB, locale.EN_WS, locale.EN_NA, locale.EN_VC, locale.EN_BZ, locale.EN_MG, locale.EN_TC, locale.EN_PW, locale.EN_TK, locale.EN_ER, locale.EN_SB, locale.EN_BI, locale.EN_HK, locale.EN_ZW, locale.EN_NZ, locale.EN_CM, locale.EN_GH, locale.EN_IO, locale.EN_GB, locale.EN_KY, locale.EN_PK, locale.EN_KE, locale.EN_LC, locale.EN_SC, locale.EN_GG, locale.EN_BM, locale.EN_DG, locale.EN_CX, locale.EN_PR, locale.EN_MS, locale.EN_PH, locale.EN_AE, locale.EN_KN, locale.EN_MH, locale.EN_NU, locale.EN_ZM, locale.EN_IM, locale.EN_NR, locale.EN_JP, locale.EN_UM, locale.EN_DM, locale.EN_IE, locale.EN_JM, locale.EN_SD, locale.EN_LR, locale.EN_VG, locale.EN_GI, locale.EN_GS, locale.EN_GU, locale.EN_FJ, locale.EN_CC, locale.EN_AG, locale.EN_TZ, locale.EN, locale.EN_SZ, locale.EN_RW, locale.EN_VU:
		return FormatInfo{
			Symbol:           "MUR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 69 locales
	case locale.TK, locale.SZL, locale.FF_LATN_GH, locale.BG, locale.FF_LATN_SL, locale.RU_UA, locale.KK_KZ, locale.FF, locale.TZM, locale.UK, locale.UZ_LATN, locale.FF_LATN_NG, locale.FF_LATN_NE, locale.SAH, locale.FF_LATN_GW, locale.BUA, locale.SMN, locale.KEA, locale.HU, locale.BR, locale.PT_MZ, locale.PT_TL, locale.TT, locale.KY, locale.CS, locale.KA, locale.YAV, locale.LV, locale.RU_BY, locale.PT_CH, locale.HY, locale.TG, locale.UZ, locale.RU_KG, locale.KSF, locale.FF_LATN, locale.CV, locale.KK_CYRL, locale.NMG, locale.RU_KZ, locale.FR_CA, locale.FF_LATN_BF, locale.PT_GW, locale.PT_MO, locale.PL, locale.RU_MD, locale.FF_LATN_CM, locale.FF_LATN_GM, locale.PT_AO, locale.EWO, locale.PT_CV, locale.KK, locale.HT, locale.PT_ST, locale.FF_LATN_GN, locale.PT_GQ, locale.PT_LU, locale.FF_LATN_MR, locale.BAS, locale.DYO, locale.BE, locale.PRG, locale.SK, locale.PT_PT, locale.FF_LATN_LR, locale.RU, locale.BE_TARASK, locale.UZ_CYRL, locale.DUA:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 64 locales
	case locale.KU_LATN_SY, locale.FR_LU, locale.LLD, locale.SR_CYRL_BA, locale.LB, locale.DE_IT, locale.IT_SM, locale.NDS_NL, locale.HSB, locale.SR_CYRL, locale.VMW, locale.IT, locale.DE_LU, locale.GL, locale.PMS, locale.IS, locale.DE, locale.KU_LATN, locale.SR_LATN_XK, locale.EL_POLYTON, locale.DE_BE, locale.MK, locale.SR_LATN_ME, locale.DA, locale.ES_EA, locale.SR_LATN, locale.RO_MD, locale.KU_LATN_IQ, locale.CA_AD, locale.NDS, locale.IT_VA, locale.LN, locale.BS_CYRL, locale.VI, locale.EL, locale.DSB, locale.SR_CYRL_ME, locale.ES, locale.FR_MA, locale.KU_TR, locale.SR_LATN_BA, locale.CA_FR, locale.EL_CY, locale.CA_IT, locale.LN_CG, locale.ES_PH, locale.LN_AO, locale.ES_IC, locale.AZ, locale.RO, locale.LIJ, locale.BS_LATN, locale.KU, locale.SR, locale.CA_ES_VALENCIA, locale.AZ_LATN, locale.AZ_CYRL, locale.AST, locale.DA_GL, locale.LN_CF, locale.SC, locale.BS, locale.CA, locale.SR_CYRL_XK:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 42 locales
	case locale.FR_MQ, locale.FR_GN, locale.FR_MU, locale.FR_VU, locale.FR_BF, locale.FR_GP, locale.FR_GF, locale.FR_GQ, locale.FR_YT, locale.FR_DZ, locale.FR_BL, locale.FR_MC, locale.FR_TD, locale.FR, locale.FR_BJ, locale.FR_BE, locale.FR_MR, locale.FR_CI, locale.FR_TN, locale.FR_HT, locale.FR_CG, locale.FR_GA, locale.FR_NC, locale.FR_WF, locale.FR_CD, locale.FR_DJ, locale.FR_BI, locale.FR_RE, locale.FR_ML, locale.FR_TG, locale.FR_RW, locale.FR_NE, locale.FR_PF, locale.FR_PM, locale.FR_CM, locale.FR_MG, locale.FR_SC, locale.FR_SY, locale.FR_KM, locale.FR_MF, locale.FR_CF, locale.FR_SN:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 22 locales
	case locale.AR_DJ, locale.AR, locale.AR_EH, locale.AR_SA, locale.AR_EG, locale.AR_YE, locale.AR_JO, locale.AR_SS, locale.AR_SY, locale.AR_KM, locale.AR_PS, locale.AR_AE, locale.AR_TD, locale.AR_IL, locale.AR_QA, locale.AR_ER, locale.AR_IQ, locale.AR_SD, locale.AR_OM, locale.AR_BH, locale.AR_SO, locale.AR_KW:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	// Group of 22 locales
	case locale.MS_BN, locale.QU_BO, locale.PT, locale.KKJ, locale.KGP, locale.FUR, locale.YRL_VE, locale.MGH, locale.RW, locale.YRL_CO, locale.ES_UY, locale.NNH, locale.SW_CD, locale.ES_CO, locale.MS_ARAB_BN, locale.JGO, locale.YRL, locale.JV, locale.ES_AR, locale.WO, locale.IA, locale.SCN:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 18 locales
	case locale.KXV_TELU, locale.PA_GURU, locale.SA, locale.DZ, locale.KOK, locale.PA, locale.KXV_LATN, locale.KOK_DEVA, locale.TA_LK, locale.HI, locale.BN_IN, locale.KOK_LATN, locale.KXV_ORYA, locale.TE, locale.KXV, locale.XNR, locale.TA, locale.KXV_DEVA:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 14 locales
	case locale.EN_SE, locale.SQ_XK, locale.EN_CZ, locale.EN_NO, locale.SQ_MK, locale.EN_HU, locale.EN_UA, locale.EN_LT, locale.EN_PT, locale.EN_SK, locale.EN_FI, locale.EN_LV, locale.SQ, locale.EN_EE:
		return FormatInfo{
			Symbol:           "MUR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 12 locales
	case locale.FF_ADLM_CM, locale.FF_ADLM_NE, locale.FF_ADLM_MR, locale.FF_ADLM_BF, locale.FF_ADLM_SN, locale.FF_ADLM_GH, locale.FF_ADLM_GM, locale.FF_ADLM_NG, locale.FF_ADLM_LR, locale.FF_ADLM, locale.FF_ADLM_SL, locale.FF_ADLM_GW:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "⹁",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 9 locales
	case locale.ID, locale.TR, locale.MUA, locale.ES_GQ, locale.TR_CY, locale.SU_LATN, locale.ES_BO, locale.SU, locale.MS_ID:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 9 locales
	case locale.KSH, locale.SV, locale.LT, locale.SV_AX, locale.SE_FI, locale.SE_SE, locale.ET, locale.SV_FI, locale.SE:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 8 locales
	case locale.EN_PL, locale.EN_DE, locale.EN_RO, locale.EN_IT, locale.EN_ES, locale.EN_DK, locale.EN_BE, locale.EN_SI:
		return FormatInfo{
			Symbol:           "MUR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 8 locales
	case locale.NL_SX, locale.NL_CW, locale.NL_BE, locale.NL_BQ, locale.NL, locale.NL_AW, locale.ES_PY, locale.NL_SR:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 8 locales
	case locale.SHI_LATN, locale.KAB, locale.SHI_TFNG, locale.OC_ES, locale.AGQ, locale.ZGH, locale.SHI, locale.OC:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 7 locales
	case locale.AF, locale.AF_NA, locale.NR, locale.VE, locale.ES_CR, locale.SS, locale.SS_SZ:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 7 locales
	case locale.LUO, locale.KM, locale.LG, locale.SBP, locale.RWK, locale.KSB, locale.BEZ:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 6 locales
	case locale.AR_DZ, locale.AR_LY, locale.AR_TN, locale.AR_MR, locale.AR_MA, locale.AR_LB:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "\u200e-",
		}
	// Group of 6 locales
	case locale.ES_VE, locale.ES_CL, locale.LO, locale.SG, locale.KL, locale.ES_EC:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,##0.00;¤-#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 6 locales
	case locale.EU, locale.FO_DK, locale.HR, locale.FO, locale.HR_BA, locale.SL:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 5 locales
	case locale.BGN_OM, locale.BGN, locale.BGN_AF, locale.BGN_AE, locale.BGN_IR:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: "٫",
			MinusSign:        "-",
		}
	// Group of 5 locales
	case locale.XOG, locale.ASA, locale.TPI, locale.CE, locale.MY:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 4 locales
	case locale.DE_AT, locale.OS_RU, locale.OS, locale.TS:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 4 locales
	case locale.NB, locale.NN, locale.NB_SJ, locale.NO:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00 ¤;-#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 4 locales
	case locale.TWQ, locale.KHQ, locale.SES, locale.DJE:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00¤",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.CCP_IN, locale.BN, locale.CCP:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##,##0.00¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.GSW_LI, locale.GSW, locale.GSW_FR:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   "'",
			DecimalSeparator: ".",
			MinusSign:        "−",
		}
	// Group of 3 locales
	case locale.LU, locale.SEH, locale.RN:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.NE, locale.NE_IN, locale.AS:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.PS_PK, locale.PS, locale.UZ_ARAB:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "\u200e−",
		}
	// Group of 2 locales
	case locale.BLO, locale.IE:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.DE_CH, locale.IT_CH:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00;¤-#,##0.00",
			GroupSeparator:   "'",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.EN_FR, locale.EN_GE:
		return FormatInfo{
			Symbol:           "MUR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.EN_IN, locale.HI_LATN:
		return FormatInfo{
			Symbol:           "MUR",
			Format:           "¤#,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.KS, locale.KS_ARAB:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.LMO, locale.WAE:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "'",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.MFE, locale.TYV:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.TN, locale.TN_BW:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,##0.00",
			GroupSeparator:   "'",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.UR, locale.UR_IN:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case locale.BA:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.BAL_LATN:
		return FormatInfo{
			Symbol:           "MURR",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.BRX:
		return FormatInfo{
			Symbol:           "एम.इउ.आर",
			Format:           "¤ #,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.DE_LI:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "'",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_150:
		return FormatInfo{
			Symbol:           "MUR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_AT:
		return FormatInfo{
			Symbol:           "MUR",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_CH:
		return FormatInfo{
			Symbol:           "MUR",
			Format:           "¤ #,##0.00;¤-#,##0.00",
			GroupSeparator:   "'",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_ID:
		return FormatInfo{
			Symbol:           "MUR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_MV:
		return FormatInfo{
			Symbol:           "MUR",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_NL:
		return FormatInfo{
			Symbol:           "MUR",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_ZA:
		return FormatInfo{
			Symbol:           "MUR",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EO:
		return FormatInfo{
			Symbol:           "₨",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.FA:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "\u200e¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e−",
		}
	case locale.FA_AF:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e−",
		}
	case locale.FI:
		return FormatInfo{
			Symbol:           "MUR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	case locale.FR_CH:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   "'",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.FY:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00;¤ #,##0.00-",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.GU:
		return FormatInfo{
			Symbol:           "રૂ.",
			Format:           "¤#,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.HE:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "\u200f#,##0.00 \u200f¤;\u200f-#,##0.00 \u200f¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case locale.LUY:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,##0.00;¤- #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.NQO:
		return FormatInfo{
			Symbol:           "ߡߙߔ",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.PA_ARAB:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case locale.RM:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.TOK:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,#0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.VEC:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.XH:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	default:
		return FormatInfo{
			Symbol:           "MUR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	}
}
