// Code generated by currency_generator.go; DO NOT EDIT.

// CLDR Version: 46.1.0
// ISO 4217 Data Last Updated: Sat, 15 Feb 2025 04:00:34 GMT

package currency

import "github.com/khatibomar/fulus/locale"

var _ Currency = XDR{}

// SDR (Special Drawing Right) currency type
type XDR struct{}

func (XDR) Code() string { return "XDR" }

func (XDR) Number() string { return "960" }

func (XDR) Name() string { return "SDR (Special Drawing Right)" }

func (XDR) MinorUnits() int { return 2 }

func (XDR) FormatInfo(locale locale.Locale) CurrencyFormatInfo {
	switch locale.String() {
	case "ar":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "ar-AE":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "ar-BH":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "ar-DJ":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "ar-DZ":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "\u200e-",
		}
	case "ar-EG":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "ar-EH":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "ar-ER":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "ar-IL":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "ar-IQ":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "ar-JO":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "ar-KM":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "ar-KW":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "ar-LB":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "\u200e-",
		}
	case "ar-LY":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "\u200e-",
		}
	case "ar-MA":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "\u200e-",
		}
	case "ar-MR":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "\u200e-",
		}
	case "ar-OM":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "ar-PS":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "ar-QA":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "ar-SA":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "ar-SD":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "ar-SO":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "ar-SS":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "ar-SY":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "ar-TD":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "ar-TN":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "\u200e-",
		}
	case "ar-YE":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "ast":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "bg":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "br":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "brx":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "bs":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "bs-Cyrl":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "bs-Latn":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "ca":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "ca-AD":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "ca-ES-valencia":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "ca-FR":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "ca-IT":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "cs":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "da":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "da-GL":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "de":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "de-AT":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "de-BE":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "de-CH":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00;¤-#,##0.00",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "de-IT":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "de-LI":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "de-LU":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "ee":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "ee-TG":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "el":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "el-CY":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "el-polyton":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "en":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-001":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-150":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-AE":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-AG":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-AI":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-AS":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-AT":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "en-AU":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-BB":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-BE":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "en-BI":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-BM":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-BS":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-BW":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-BZ":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-CA":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-CC":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-CH":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00;¤-#,##0.00",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-CK":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-CM":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-CX":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-CY":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-DE":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "en-DG":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-DK":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "en-DM":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-ER":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-FI":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "en-FJ":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-FK":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-FM":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-GB":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-GD":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-GG":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-GH":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-GI":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-GM":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-GU":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-GY":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-HK":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-ID":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "en-IE":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-IL":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-IM":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-IN":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-IO":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-JE":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-JM":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-KE":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-KI":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-KN":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-KY":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-LC":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-LR":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-LS":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-MG":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-MH":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-MO":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-MP":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-MS":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-MT":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-MU":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-MV":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-MW":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-MY":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-NA":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-NF":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-NG":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-NL":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "en-NR":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-NU":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-NZ":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-PG":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-PH":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-PK":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-PN":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-PR":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-PW":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-RW":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-SB":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-SC":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-SD":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-SE":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "en-SG":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-SH":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-SI":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "en-SL":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-SS":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-SX":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-SZ":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-TC":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-TK":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-TO":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-TT":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-TV":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-TZ":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-UG":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-UM":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-VC":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-VG":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-VI":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-VU":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-WS":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-ZA":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "en-ZM":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "en-ZW":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "es":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "es-419":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "es-AR":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "es-BO":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "es-BR":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "es-BZ":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "es-CL":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00;¤-#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "es-CO":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "es-CR":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "es-CU":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "es-DO":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "es-EA":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "es-EC":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00;¤-#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "es-GQ":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "es-GT":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "es-HN":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "es-IC":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "es-MX":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "es-NI":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "es-PA":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "es-PE":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "es-PH":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "es-PR":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "es-PY":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "es-SV":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "es-US":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "es-UY":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "es-VE":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00;¤-#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "et":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	case "eu":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	case "fi":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	case "fr":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-BE":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-BF":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-BI":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-BJ":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-BL":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-CA":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-CD":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-CF":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-CG":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-CH":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-CI":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-CM":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-DJ":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-DZ":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-GA":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-GF":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-GN":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-GP":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-GQ":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-HT":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-KM":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-LU":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-MA":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-MC":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-MF":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-MG":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-ML":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-MQ":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-MR":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-MU":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-NC":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-NE":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-PF":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-PM":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-RE":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-RW":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-SC":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-SN":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-SY":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-TD":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-TG":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-TN":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-VU":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-WF":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fr-YT":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fur":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "fy":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00;¤ #,##0.00-",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "ga":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "ga-GB":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "gd":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "gsw":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "−",
		}
	case "gsw-FR":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "−",
		}
	case "gsw-LI":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "−",
		}
	case "he":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "\u200f#,##0.00 \u200f¤;\u200f-#,##0.00 \u200f¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case "hi-Latn":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "hr":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	case "hr-BA":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	case "hu":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "id":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "is":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "it":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "it-CH":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00;¤-#,##0.00",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "it-SM":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "it-VA":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "ja":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "kgp":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "ko":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "ko-CN":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "ko-KP":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "ks":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "ks-Arab":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "lb":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "lo":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00;¤-#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "lt":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	case "lv":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "ml":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "my":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "nb":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤;-#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	case "nb-SJ":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤;-#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	case "nl":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "nl-AW":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "nl-BE":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "nl-BQ":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "nl-CW":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "nl-SR":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "nl-SX":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "nn":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤;-#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	case "no":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤;-#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	case "pl":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "pt":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "pt-AO":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "pt-CH":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "pt-CV":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "pt-GQ":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "pt-GW":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "pt-LU":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "pt-MO":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "pt-MZ":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "pt-PT":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "pt-ST":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "pt-TL":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "rm":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "−",
		}
	case "ro":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "ro-MD":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "ru":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "ru-BY":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "ru-KG":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "ru-KZ":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "ru-MD":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "ru-UA":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "sc":
		return CurrencyFormatInfo{
			Symbol:           "DIP",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "sk":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "sl":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	case "sr":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "sr-Cyrl":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "sr-Cyrl-BA":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "sr-Cyrl-ME":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "sr-Cyrl-XK":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "sr-Latn":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "sr-Latn-BA":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "sr-Latn-ME":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "sr-Latn-XK":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "sv":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	case "sv-AX":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	case "sv-FI":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	case "th":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "tr":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "tr-CY":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "ug":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "uk":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "vi":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "yrl":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "yrl-CO":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "yrl-VE":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case "yue":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "yue-Hans":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "yue-Hant":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "yue-Hant-CN":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "zh":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "zh-Hans":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "zh-Hans-HK":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "zh-Hans-MO":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "zh-Hans-MY":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "zh-Hans-SG":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "zh-Hant":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "zh-Hant-HK":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "zh-Hant-MO":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case "zh-Hant-MY":
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	default:
		return CurrencyFormatInfo{
			Symbol:           "XDR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	}
}
