// Code generated by generator.go; DO NOT EDIT.

// CLDR Version: 47.0.0
// ISO 4217 Data Last Updated: Sat, 31 May 2025 03:00:43 GMT

package currency

import "github.com/khatibomar/fulus/locale"

var _ Currency = PLN{}

// Zloty currency type
type PLN struct{}

func (PLN) Code() string { return "PLN" }

func (PLN) Number() string { return "985" }

func (PLN) Name() string { return "Zloty" }

func (PLN) MinorUnits() int { return 2 }

func (PLN) FormatInfo(localeType locale.Locale) FormatInfo {
	switch localeType {
	// Group of 140 locales
	case locale.RHG_ROHG_BD, locale.MDF, locale.SKR, locale.CO, locale.MNI_BENG, locale.ZA, locale.BLT, locale.MGO, locale.MN_MONG, locale.BA, locale.SSY, locale.TA_MY, locale.LRC, locale.TYV, locale.AN, locale.BO_IN, locale.PAP_AW, locale.LAG, locale.KAA, locale.NY, locale.SID, locale.KEN, locale.TRW, locale.IO, locale.SD, locale.PAP, locale.SD_ARAB, locale.SHN, locale.LTG, locale.MNI_MTEI, locale.NV, locale.RHG, locale.SAT_DEVA, locale.TA_SG, locale.TRV, locale.LRC_IQ, locale.AZ_ARAB_TR, locale.BGC, locale.HA_NE, locale.HNJ, locale.MN, locale.SW_KE, locale.CHO, locale.HA_ARAB, locale.RHG_ROHG, locale.AB, locale.GEZ, locale.AZ_ARAB, locale.BAL, locale.KPE_GN, locale.UND, locale.COP, locale.KOK, locale.KAA_LATN, locale.SD_DEVA, locale.SMA, locale.KS_DEVA, locale.TO, locale.VO, locale.SMS, locale.SYR_SY, locale.YI, locale.FRR, locale.AZ_ARAB_IQ, locale.LA, locale.AA, locale.ES_PE, locale.SAT_OLCK, locale.KCG, locale.SDH, locale.HA_GH, locale.QU_EC, locale.SW_UG, locale.CKB, locale.MI, locale.CU, locale.MUS, locale.TIG, locale.KPE, locale.AA_ER, locale.MNI, locale.IU, locale.MYV, locale.OSA, locale.QU, locale.ANN, locale.CAD, locale.MIC, locale.RIF, locale.SDH_IQ, locale.MAI, locale.APC, locale.GEZ_ER, locale.SYR, locale.HNJ_HMNP, locale.GAA, locale.KAA_CYRL, locale.KOK_DEVA, locale.SW, locale.MZN, locale.SMJ, locale.MOH, locale.MHN, locale.BAL_ARAB, locale.CSW, locale.GN, locale.CKB_IR, locale.QUC, locale.BYN, locale.RAJ, locale.SMA_NO, locale.AA_DJ, locale.CCH, locale.EN_SHAW, locale.ARN, locale.SHN_TH, locale.BEW, locale.EN_DSRT, locale.SCN, locale.KK_ARAB, locale.DV, locale.KAJ, locale.MG, locale.WA, locale.HA_ARAB_SD, locale.PIS, locale.BO, locale.IU_LATN, locale.WAL, locale.BM_NKOO, locale.JBO, locale.HA, locale.WBP, locale.SAT, locale.II, locale.BSS, locale.CIC, locale.ZH_LATN, locale.LKT, locale.SMJ_NO:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 101 locales
	case locale.JA, locale.MER, locale.YUE_HANS, locale.ES_HN, locale.TH, locale.NYN, locale.VAI_VAII, locale.ES_PA, locale.GUZ, locale.AK, locale.JMC, locale.KO_KP, locale.GV, locale.ES_GT, locale.PCM, locale.ES_419, locale.ZH_HANS_MO, locale.ES_BR, locale.ST_LS, locale.MS, locale.ZH_HANT_HK, locale.MAS, locale.SO_DJ, locale.CGG, locale.SO_ET, locale.BEM, locale.KI, locale.KW, locale.ES_SV, locale.MS_ARAB, locale.CHR, locale.DAV, locale.KDE, locale.AM, locale.SI, locale.EE, locale.NUS, locale.YO, locale.MN_MONG_MN, locale.TI, locale.SAQ, locale.ZH_HANS_HK, locale.FIL, locale.HAW, locale.MAS_TZ, locale.ES_PR, locale.OM_KE, locale.ZH_HANT_MY, locale.VAI_LATN, locale.OM, locale.YUE_HANT_MO, locale.ML, locale.VAI, locale.ZH_HANT, locale.SO_KE, locale.UG, locale.VUN, locale.IG, locale.KO_CN, locale.MS_SG, locale.SN, locale.ZH_HANS_SG, locale.ZH, locale.GA_GB, locale.TI_ER, locale.ROF, locale.YUE_HANT, locale.ND, locale.ES_NI, locale.BM, locale.CY, locale.ES_BZ, locale.ES_MX, locale.TEO_KE, locale.EE_TG, locale.NAQ, locale.ZH_HANS_MY, locale.DOI, locale.GA, locale.ES_US, locale.TEO, locale.KO, locale.ES_CU, locale.SO, locale.ZH_HANT_MO, locale.ZH_HANS, locale.EBU, locale.KAM, locale.GD, locale.KN, locale.KLN, locale.MR, locale.BHO, locale.YUE, locale.ES_DO, locale.OR, locale.YUE_HANT_CN, locale.ST, locale.YO_BJ, locale.MT, locale.CEB:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 94 locales
	case locale.EN_NF, locale.EN_LR, locale.EN_NG, locale.EN_BS, locale.EN_KE, locale.EN_KY, locale.EN_GB, locale.EN_IO, locale.EN_NA, locale.EN_DM, locale.EN_SD, locale.EN_FK, locale.EN_IM, locale.EN_VU, locale.EN_WS, locale.EN_GS, locale.EN_GG, locale.EN_BZ, locale.EN_PH, locale.EN_MT, locale.EN_SB, locale.EN_SS, locale.EN_TT, locale.EN_UG, locale.EN_VG, locale.EN_TZ, locale.EN_MS, locale.EN_VI, locale.EN_LC, locale.EN_AS, locale.EN_PN, locale.EN_MP, locale.EN_AI, locale.EN_SH, locale.EN_BW, locale.EN_GH, locale.EN_UM, locale.EN_GI, locale.EN_MY, locale.EN_CM, locale.EN_ZM, locale.EN_BB, locale.EN_KI, locale.EN_NR, locale.EN_SX, locale.EN_GU, locale.EN_JE, locale.EN_CK, locale.EN_CY, locale.EN_GY, locale.EN_FJ, locale.EN_VC, locale.EN_PW, locale.EN_SC, locale.EN, locale.EN_HK, locale.EN_MO, locale.EN_BM, locale.EN_NZ, locale.EN_PK, locale.EN_ER, locale.EN_MG, locale.EN_IL, locale.EN_MH, locale.EN_DG, locale.EN_AU, locale.EN_FM, locale.EN_GM, locale.EN_CA, locale.EN_IE, locale.EN_CX, locale.EN_MU, locale.EN_AE, locale.EN_TK, locale.EN_CC, locale.EN_LS, locale.EN_RW, locale.EN_BI, locale.EN_SG, locale.EN_AG, locale.EN_TO, locale.EN_PR, locale.EN_ZW, locale.EN_MW, locale.EN_SZ, locale.EN_001, locale.EN_SL, locale.EN_TV, locale.EN_GD, locale.EN_KN, locale.EN_NU, locale.EN_TC, locale.EN_JM, locale.EN_PG:
		return FormatInfo{
			Symbol:           "PLN",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 69 locales
	case locale.FF_LATN, locale.PT_MZ, locale.EWO, locale.TG, locale.KA, locale.RU, locale.FF, locale.KSF, locale.PT_GW, locale.LV, locale.BG, locale.FR_CA, locale.TK, locale.DYO, locale.FF_LATN_GN, locale.PRG, locale.RU_KZ, locale.TZM, locale.KEA, locale.BR, locale.PT_MO, locale.NMG, locale.RU_BY, locale.RU_KG, locale.KK_CYRL, locale.SK, locale.FF_LATN_CM, locale.HU, locale.FF_LATN_BF, locale.SZL, locale.EO, locale.RU_UA, locale.PT_LU, locale.FF_LATN_SL, locale.DUA, locale.HT, locale.PT_GQ, locale.FF_LATN_NE, locale.FF_LATN_GM, locale.BE, locale.PT_TL, locale.FF_LATN_LR, locale.PT_AO, locale.BE_TARASK, locale.UZ_LATN, locale.FF_LATN_GW, locale.PT_CH, locale.CV, locale.PL, locale.KK, locale.UZ_CYRL, locale.KY, locale.CS, locale.SMN, locale.HY, locale.PT_PT, locale.UK, locale.FF_LATN_MR, locale.YAV, locale.SAH, locale.PT_CV, locale.UZ, locale.RU_MD, locale.PT_ST, locale.FF_LATN_NG, locale.FF_LATN_GH, locale.BAS, locale.KK_KZ, locale.TT:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 57 locales
	case locale.SC, locale.LN_AO, locale.BS_LATN, locale.SR_CYRL, locale.CA, locale.ES_PH, locale.CA_IT, locale.CA_AD, locale.VMW, locale.SR_LATN_ME, locale.ES_IC, locale.DSB, locale.ES_EA, locale.IT_VA, locale.DE_IT, locale.HSB, locale.IT, locale.LN, locale.IT_SM, locale.SR, locale.SR_LATN_BA, locale.LN_CG, locale.NDS_NL, locale.IS, locale.NDS, locale.DE_LU, locale.EL, locale.LB, locale.RO_MD, locale.LLD, locale.GL, locale.CA_ES_VALENCIA, locale.BS, locale.AZ_CYRL, locale.AZ_LATN, locale.DA, locale.SR_CYRL_ME, locale.MK, locale.AZ, locale.SR_LATN, locale.KU, locale.VI, locale.EL_CY, locale.RO, locale.CA_FR, locale.SR_CYRL_XK, locale.SR_CYRL_BA, locale.EL_POLYTON, locale.DA_GL, locale.FR_MA, locale.FR_LU, locale.SR_LATN_XK, locale.DE_BE, locale.LN_CF, locale.DE, locale.ES, locale.LIJ:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 43 locales
	case locale.FR_DZ, locale.FR_GN, locale.FR_SC, locale.FR_TG, locale.FR_YT, locale.FR_NE, locale.FR_SY, locale.FR_VU, locale.FR_CM, locale.FR_CD, locale.FR_MR, locale.FR_CG, locale.FR_MG, locale.FR_GA, locale.FR_MF, locale.FR_MU, locale.FR_TD, locale.FR_MC, locale.FR_CH, locale.FR_RE, locale.FR_PF, locale.FR_DJ, locale.FR_WF, locale.FR_BI, locale.FR_BE, locale.FR_KM, locale.FR_TN, locale.FR, locale.FR_GF, locale.FR_CI, locale.FR_BJ, locale.FR_GP, locale.FR_SN, locale.FR_BF, locale.FR_CF, locale.FR_GQ, locale.FR_HT, locale.FR_MQ, locale.FR_RW, locale.FR_BL, locale.FR_ML, locale.FR_NC, locale.FR_PM:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 22 locales
	case locale.AR_KM, locale.AR_TD, locale.AR_OM, locale.AR_SY, locale.AR_IQ, locale.AR_EG, locale.AR_SS, locale.AR_BH, locale.AR, locale.AR_EH, locale.AR_DJ, locale.AR_SO, locale.AR_KW, locale.AR_YE, locale.AR_ER, locale.AR_IL, locale.AR_QA, locale.AR_AE, locale.AR_PS, locale.AR_JO, locale.AR_SD, locale.AR_SA:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	// Group of 21 locales
	case locale.ES_AR, locale.WO, locale.MS_BN, locale.JV, locale.KGP, locale.YRL_CO, locale.KKJ, locale.PT, locale.MS_ARAB_BN, locale.MGH, locale.YRL_VE, locale.ES_CO, locale.IA, locale.FUR, locale.YRL, locale.SW_CD, locale.ES_UY, locale.NNH, locale.RW, locale.JGO, locale.QU_BO:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 17 locales
	case locale.BN_IN, locale.TA_LK, locale.XNR, locale.PA, locale.DZ, locale.KXV_TELU, locale.KOK_LATN, locale.GU, locale.TA, locale.KXV_ORYA, locale.TE, locale.KXV_DEVA, locale.SA, locale.HI, locale.KXV_LATN, locale.PA_GURU, locale.KXV:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤#,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 12 locales
	case locale.FF_ADLM_NG, locale.FF_ADLM_GH, locale.FF_ADLM_MR, locale.FF_ADLM_SN, locale.FF_ADLM_LR, locale.FF_ADLM_GW, locale.FF_ADLM, locale.FF_ADLM_NE, locale.FF_ADLM_GM, locale.FF_ADLM_CM, locale.FF_ADLM_BF, locale.FF_ADLM_SL:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "⹁",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 10 locales
	case locale.SQ_MK, locale.EN_PT, locale.EN_SK, locale.EN_HU, locale.SQ_XK, locale.EN_NO, locale.EN_FI, locale.SQ, locale.EN_CZ, locale.EN_SE:
		return FormatInfo{
			Symbol:           "PLN",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 9 locales
	case locale.EN_DE, locale.EN_ES, locale.EN_IT, locale.AST, locale.EN_SI, locale.EN_BE, locale.EN_DK, locale.EN_PL, locale.EN_RO:
		return FormatInfo{
			Symbol:           "PLN",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 9 locales
	case locale.ES_GQ, locale.ES_BO, locale.SU, locale.MUA, locale.SU_LATN, locale.TR_CY, locale.MS_ID, locale.TR, locale.ID:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 8 locales
	case locale.NL_BE, locale.ES_PY, locale.NL, locale.NL_BQ, locale.NL_SR, locale.NL_SX, locale.NL_CW, locale.NL_AW:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 8 locales
	case locale.OC, locale.OC_ES, locale.SHI, locale.SHI_LATN, locale.SHI_TFNG, locale.ZGH, locale.KAB, locale.AGQ:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "#,##0.00¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 8 locales
	case locale.SV_AX, locale.KSH, locale.SV, locale.SE_SE, locale.SV_FI, locale.SE_FI, locale.ET, locale.SE:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 7 locales
	case locale.KM, locale.SBP, locale.LG, locale.RWK, locale.KSB, locale.BEZ, locale.LUO:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "#,##0.00¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 7 locales
	case locale.SS, locale.AF, locale.AF_NA, locale.NR, locale.SS_SZ, locale.VE, locale.ES_CR:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 6 locales
	case locale.AR_MA, locale.AR_LY, locale.AR_MR, locale.AR_TN, locale.AR_LB, locale.AR_DZ:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "\u200e-",
		}
	// Group of 6 locales
	case locale.ES_EC, locale.KL, locale.ES_CL, locale.LO, locale.ES_VE, locale.SG:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤#,##0.00;¤-#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 6 locales
	case locale.HR_BA, locale.FO_DK, locale.EU, locale.FO, locale.SL, locale.HR:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 5 locales
	case locale.BGN_OM, locale.BGN_AF, locale.BGN_AE, locale.BGN, locale.BGN_IR:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: "٫",
			MinusSign:        "-",
		}
	// Group of 5 locales
	case locale.MY, locale.CE, locale.XOG, locale.TPI, locale.ASA:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 4 locales
	case locale.GSW_LI, locale.GSW, locale.RM, locale.GSW_FR:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "−",
		}
	// Group of 4 locales
	case locale.NB_SJ, locale.NN, locale.NB, locale.NO:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "#,##0.00 ¤;-#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 4 locales
	case locale.TS, locale.OS, locale.OS_RU, locale.DE_AT:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤ #,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 4 locales
	case locale.TWQ, locale.SES, locale.DJE, locale.KHQ:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "#,##0.00¤",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.AS, locale.NE_IN, locale.NE:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤ #,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.CCP, locale.BN, locale.CCP_IN:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "#,##,##0.00¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.PS_PK, locale.PS, locale.UZ_ARAB:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "\u200e−",
		}
	// Group of 3 locales
	case locale.RN, locale.LU, locale.SEH:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "#,##0.00¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.HI_LATN, locale.EN_IN:
		return FormatInfo{
			Symbol:           "PLN",
			Format:           "¤#,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.IE, locale.BLO:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.IT_CH, locale.DE_CH:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤ #,##0.00;¤-#,##0.00",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.KS_ARAB, locale.KS:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤#,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.LMO, locale.WAE:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "’",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.MFE, locale.NSO:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤ #,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.TN, locale.TN_BW:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤#,##0.00",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.UR_IN, locale.UR:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case locale.BAL_LATN:
		return FormatInfo{
			Symbol:           "PLNZ",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.BRX:
		return FormatInfo{
			Symbol:           "पि.एल.एन",
			Format:           "¤ #,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.BS_CYRL:
		return FormatInfo{
			Symbol:           "зл",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.DE_LI:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_150:
		return FormatInfo{
			Symbol:           "PLN",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_AT:
		return FormatInfo{
			Symbol:           "PLN",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_CH:
		return FormatInfo{
			Symbol:           "PLN",
			Format:           "¤ #,##0.00;¤-#,##0.00",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_FR:
		return FormatInfo{
			Symbol:           "PLN",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_ID:
		return FormatInfo{
			Symbol:           "PLN",
			Format:           "¤#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_MV:
		return FormatInfo{
			Symbol:           "PLN",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_NL:
		return FormatInfo{
			Symbol:           "PLN",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_ZA:
		return FormatInfo{
			Symbol:           "PLN",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.FA:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "\u200e¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e−",
		}
	case locale.FA_AF:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e−",
		}
	case locale.FI:
		return FormatInfo{
			Symbol:           "PLN",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	case locale.FY:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤ #,##0.00;¤ #,##0.00-",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.HE:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "\u200f#,##0.00 \u200f¤;\u200f-#,##0.00 \u200f¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case locale.LT:
		return FormatInfo{
			Symbol:           "zl",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	case locale.LUY:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤#,##0.00;¤- #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.NQO:
		return FormatInfo{
			Symbol:           "ߔߟߗ߭",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.PA_ARAB:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case locale.TOK:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤#,#0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.VEC:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.XH:
		return FormatInfo{
			Symbol:           "zł",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.ZU:
		return FormatInfo{
			Symbol:           "Zł",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	default:
		return FormatInfo{
			Symbol:           "PLN",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	}
}
