// Code generated by generator.go; DO NOT EDIT.

// CLDR Version: 48.2.3
// ISO 4217 Data Last Updated: Thu, 01 Oct 2026 03:00:58 GMT

package currency

import "github.com/khatibomar/fulus/locale"

var _ Currency = UAH{}

// Hryvnia currency type
type UAH struct{}

func (UAH) Code() string { return "UAH" }

func (UAH) Number() string { return "980" }

func (UAH) Name() string { return "Hryvnia" }

func (UAH) MinorUnits() int { return 2 }

func (UAH) FormatInfo(localeType locale.Locale) FormatInfo {
	switch localeType {
	// Group of 151 locales
	case locale.JBO, locale.SD_ARAB, locale.SDH_IQ, locale.SMA_NO, locale.AA, locale.SAT_DEVA, locale.LKT, locale.NV, locale.MNI_MTEI, locale.SYR_SY, locale.EN_SHAW, locale.MHN, locale.HA_NE, locale.PAP, locale.VO, locale.BSS, locale.SYR, locale.LRC, locale.SAT, locale.SUZ_SUNU, locale.AZ_ARAB_TR, locale.KU_ARAB_IR, locale.OKA_US, locale.SD_DEVA, locale.SMJ_NO, locale.KAA, locale.RHG_ROHG, locale.KAJ, locale.BGC, locale.KAA_LATN, locale.CSW, locale.GN, locale.SUZ_DEVA, locale.TIG, locale.BAL, locale.TRV, locale.GEZ, locale.LAG, locale.SDH, locale.CAD, locale.SMA, locale.MI, locale.MZN, locale.SHN_TH, locale.SW_UG, locale.WAL, locale.GEZ_ER, locale.AA_ER, locale.NY, locale.TRW, locale.II, locale.ARN, locale.MG, locale.CKB, locale.SAT_OLCK, locale.BAL_ARAB, locale.LTG, locale.BQI, locale.CU, locale.KK_ARAB, locale.CCH, locale.CKB_IR, locale.SMS, locale.EN_DSRT, locale.TA_SG, locale.RHG, locale.IO, locale.PIS, locale.KEN, locale.QU_EC, locale.RIF, locale.NSO, locale.SUZ, locale.OKA, locale.CIC, locale.KEK, locale.AN, locale.TO, locale.KU_ARAB, locale.QUC, locale.FRR, locale.RAJ, locale.SD, locale.SW, locale.BLT, locale.CO, locale.PAP_AW, locale.ZA, locale.LA, locale.IU_LATN, locale.LZZ, locale.QU, locale.CHO, locale.MOH, locale.RHG_ROHG_BD, locale.SKR, locale.BM_NKOO, locale.LRC_IQ, locale.MUS, locale.SGS, locale.AZ_ARAB_IQ, locale.KAA_CYRL, locale.OSA, locale.PI_LATN, locale.TA_MY, locale.HNJ_HMNP, locale.MAI, locale.ES_PE, locale.SMJ, locale.WBP, locale.AA_DJ, locale.MWW_HMNP, locale.WA, locale.MNI, locale.SW_KE, locale.DV, locale.MNI_BENG, locale.MIC, locale.MN_MONG, locale.BO, locale.KCG, locale.SSY, locale.UND, locale.MDF, locale.SHN, locale.YI, locale.HA_ARAB, locale.MGO, locale.AB, locale.KPE, locale.KS_DEVA, locale.HNJ, locale.HA_ARAB_SD, locale.SID, locale.AZ_ARAB, locale.MN, locale.MWW, locale.PI, locale.COP, locale.HA, locale.ANN, locale.APC, locale.BEW, locale.HA_GH, locale.BYN, locale.GAA, locale.ZH_LATN, locale.MYV, locale.IU, locale.BO_IN, locale.KPE_GN:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 102 locales
	case locale.ST, locale.ES_GT, locale.ES_US, locale.NUS, locale.CGG, locale.OM, locale.YO, locale.YUE, locale.ES_419, locale.ES_MX, locale.ES_SV, locale.NAQ, locale.JMC, locale.BM, locale.YUE_HANT_MO, locale.FIL, locale.SI, locale.IG, locale.AK, locale.KN, locale.UG, locale.BHO, locale.ES_PR, locale.YUE_HANT, locale.ZH_HANS_SG, locale.MR, locale.ES_PA, locale.ZH_HANT, locale.ZH_HANT_HK, locale.MN_MONG_MN, locale.ES_CU, locale.YUE_HANT_CN, locale.AM, locale.ZH_HANT_MY, locale.GD, locale.CY, locale.KLN, locale.KO_CN, locale.ES_BZ, locale.TEO_KE, locale.ZH, locale.KDE, locale.GA_GB, locale.MER, locale.ROF, locale.NYN, locale.TH, locale.ES_HN, locale.DAV, locale.ML, locale.ZH_HANT_MO, locale.EBU, locale.SO_DJ, locale.SO_ET, locale.ZH_HANS, locale.KW, locale.ST_LS, locale.PCM, locale.TEO, locale.MS_SG, locale.MAS, locale.MT, locale.SO_KE, locale.ZU, locale.CEB, locale.VUN, locale.GV, locale.KAM, locale.VAI, locale.KI, locale.OM_KE, locale.ZH_HANS_MY, locale.KO_KP, locale.VAI_VAII, locale.ES_BR, locale.HAW, locale.TI_ER, locale.KO, locale.MS_ARAB, locale.SAQ, locale.ES_DO, locale.VAI_LATN, locale.MAS_TZ, locale.EE, locale.TI, locale.GUZ, locale.YUE_HANS, locale.ZH_HANS_HK, locale.DOI, locale.ES_NI, locale.GA, locale.CHR, locale.YO_BJ, locale.ZH_HANS_MO, locale.MS, locale.ND, locale.JA, locale.OR, locale.SO, locale.SN, locale.BEM, locale.EE_TG:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 95 locales
	case locale.EN_KE, locale.EN_UG, locale.EN_VC, locale.EN_VU, locale.EN_MT, locale.EN_CY, locale.EN_MG, locale.EN_IO, locale.EN_KY, locale.EN_FM, locale.EN_MO, locale.EN_GY, locale.EN_IL, locale.EN_CC, locale.EN, locale.EN_JE, locale.EN_NU, locale.EN_NZ, locale.EN_MP, locale.EN_TO, locale.EN_GI, locale.EN_HK, locale.EN_FK, locale.EN_SH, locale.EN_GB, locale.EN_SC, locale.EN_PG, locale.EN_KN, locale.EN_GS, locale.EN_MY, locale.EN_SG, locale.EN_BM, locale.EN_VG, locale.EN_AI, locale.EN_GD, locale.EN_WS, locale.EN_MU, locale.EN_SB, locale.EN_LR, locale.EN_GH, locale.EN_DM, locale.EN_TV, locale.EN_NG, locale.EN_RW, locale.EN_AG, locale.EN_BI, locale.EN_PN, locale.EN_TC, locale.EN_TK, locale.EN_NR, locale.EN_FJ, locale.EN_ZM, locale.EN_LC, locale.EN_MW, locale.EN_LS, locale.EN_CA, locale.EN_SL, locale.EN_CX, locale.EN_UM, locale.EN_ER, locale.EN_BS, locale.EN_SD, locale.EN_VI, locale.EN_GU, locale.EN_PW, locale.EN_TT, locale.EN_DG, locale.EN_SZ, locale.EN_NA, locale.EN_AE, locale.EN_BW, locale.EN_001, locale.EN_IE, locale.EN_JM, locale.EN_SS, locale.EN_IM, locale.EN_PH, locale.EN_JP, locale.EN_TZ, locale.EN_KI, locale.EN_CM, locale.EN_PK, locale.EN_PR, locale.EN_BZ, locale.EN_MS, locale.EN_BB, locale.EN_MH, locale.EN_AU, locale.EN_GM, locale.EN_AS, locale.EN_SX, locale.EN_NF, locale.EN_ZW, locale.EN_CK, locale.EN_GG:
		return FormatInfo{
			Symbol:           "UAH",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 68 locales
	case locale.UZ_CYRL, locale.PL, locale.RU_MD, locale.KEA, locale.TG, locale.DUA, locale.PRG, locale.PT_CH, locale.SMN, locale.UZ, locale.BUA, locale.TT, locale.BE_TARASK, locale.KSF, locale.PT_LU, locale.PT_GQ, locale.EWO, locale.PT_CV, locale.FF_LATN, locale.FF_LATN_MR, locale.BR, locale.BE, locale.FF_LATN_SL, locale.FF_LATN_LR, locale.CS, locale.TZM, locale.KK_CYRL, locale.PT_GW, locale.SK, locale.PT_MZ, locale.FF_LATN_NE, locale.TK, locale.BAS, locale.YAV, locale.KK, locale.RU_KG, locale.CV, locale.HU, locale.PT_TL, locale.DYO, locale.KA, locale.NMG, locale.PT_ST, locale.SZL, locale.HY, locale.UZ_LATN, locale.RU_KZ, locale.FF_LATN_GW, locale.PT_MO, locale.UK, locale.FF_LATN_GN, locale.FF_LATN_BF, locale.FF, locale.PT_AO, locale.PT_PT, locale.LV, locale.FF_LATN_NG, locale.FF_LATN_GH, locale.FF_LATN_GM, locale.KY, locale.RU_BY, locale.KK_KZ, locale.SAH, locale.HT, locale.RU, locale.FR_CA, locale.RU_UA, locale.FF_LATN_CM:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 64 locales
	case locale.AZ, locale.LN_CG, locale.CA_AD, locale.KU_LATN_IQ, locale.BS_LATN, locale.CA, locale.DA, locale.SR_CYRL_XK, locale.AST, locale.SR_LATN_BA, locale.SR_CYRL, locale.LIJ, locale.LLD, locale.RO, locale.LN, locale.PMS, locale.KU_TR, locale.BS_CYRL, locale.LN_AO, locale.BS, locale.CA_ES_VALENCIA, locale.NDS_NL, locale.DSB, locale.DE_LU, locale.IS, locale.KU, locale.VMW, locale.AZ_LATN, locale.NDS, locale.MK, locale.HSB, locale.SR_CYRL_ME, locale.DE_BE, locale.EL_POLYTON, locale.SR, locale.AZ_CYRL, locale.SR_LATN, locale.RO_MD, locale.DE_IT, locale.FR_LU, locale.KU_LATN_SY, locale.SR_CYRL_BA, locale.LB, locale.ES, locale.KU_LATN, locale.DE, locale.CA_IT, locale.GL, locale.FR_MA, locale.IT_SM, locale.ES_IC, locale.SC, locale.EL, locale.VI, locale.ES_PH, locale.LN_CF, locale.SR_LATN_ME, locale.EL_CY, locale.ES_EA, locale.IT, locale.IT_VA, locale.DA_GL, locale.SR_LATN_XK, locale.CA_FR:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 42 locales
	case locale.FR_PM, locale.FR_KM, locale.FR_BI, locale.FR_WF, locale.FR_MQ, locale.FR_CG, locale.FR_GQ, locale.FR_MG, locale.FR_DJ, locale.FR_GN, locale.FR_HT, locale.FR_RW, locale.FR_TN, locale.FR_YT, locale.FR_BF, locale.FR, locale.FR_TG, locale.FR_CM, locale.FR_MC, locale.FR_MR, locale.FR_TD, locale.FR_GP, locale.FR_SC, locale.FR_SN, locale.FR_CD, locale.FR_SY, locale.FR_RE, locale.FR_ML, locale.FR_CF, locale.FR_CI, locale.FR_PF, locale.FR_GF, locale.FR_NE, locale.FR_BL, locale.FR_DZ, locale.FR_NC, locale.FR_BE, locale.FR_VU, locale.FR_MF, locale.FR_GA, locale.FR_BJ, locale.FR_MU:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 22 locales
	case locale.AR_OM, locale.AR_SA, locale.AR_TD, locale.AR_AE, locale.AR_SO, locale.AR_IL, locale.AR_SD, locale.AR_EG, locale.AR_QA, locale.AR_SY, locale.AR_DJ, locale.AR_JO, locale.AR_ER, locale.AR_KM, locale.AR_SS, locale.AR, locale.AR_YE, locale.AR_BH, locale.AR_PS, locale.AR_IQ, locale.AR_EH, locale.AR_KW:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	// Group of 22 locales
	case locale.WO, locale.ES_AR, locale.JGO, locale.MS_BN, locale.SW_CD, locale.QU_BO, locale.JV, locale.MS_ARAB_BN, locale.YRL_VE, locale.PT, locale.ES_UY, locale.FUR, locale.SCN, locale.NNH, locale.YRL, locale.IA, locale.KGP, locale.RW, locale.ES_CO, locale.MGH, locale.YRL_CO, locale.KKJ:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 19 locales
	case locale.DZ, locale.KOK_LATN, locale.KXV, locale.PA, locale.TA, locale.TA_LK, locale.BN_IN, locale.KOK_DEVA, locale.XNR, locale.KXV_TELU, locale.GU, locale.KXV_DEVA, locale.KXV_LATN, locale.KXV_ORYA, locale.KOK, locale.PA_GURU, locale.HI, locale.SA, locale.TE:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤#,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 15 locales
	case locale.EN_LT, locale.BG, locale.EN_PT, locale.EN_NO, locale.EN_UA, locale.EN_CZ, locale.EN_SK, locale.SQ_XK, locale.EN_FI, locale.EN_HU, locale.SQ_MK, locale.SQ, locale.EN_SE, locale.EN_EE, locale.EN_LV:
		return FormatInfo{
			Symbol:           "UAH",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 12 locales
	case locale.FF_ADLM_BF, locale.FF_ADLM_GW, locale.FF_ADLM_SL, locale.FF_ADLM_CM, locale.FF_ADLM_LR, locale.FF_ADLM_NG, locale.FF_ADLM_SN, locale.FF_ADLM_GM, locale.FF_ADLM_GH, locale.FF_ADLM_MR, locale.FF_ADLM, locale.FF_ADLM_NE:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "⹁",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 9 locales
	case locale.SV, locale.SE, locale.SE_SE, locale.LT, locale.KSH, locale.SV_FI, locale.SV_AX, locale.ET, locale.SE_FI:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 9 locales
	case locale.TR_CY, locale.ES_BO, locale.SU_LATN, locale.MS_ID, locale.MUA, locale.ES_GQ, locale.ID, locale.TR, locale.SU:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 8 locales
	case locale.EN_DE, locale.EN_DK, locale.EN_PL, locale.EN_BE, locale.EN_SI, locale.EN_ES, locale.EN_RO, locale.EN_IT:
		return FormatInfo{
			Symbol:           "UAH",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 8 locales
	case locale.NL_CW, locale.NL_BQ, locale.NL_SR, locale.NL_BE, locale.NL, locale.ES_PY, locale.NL_AW, locale.NL_SX:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 8 locales
	case locale.OC, locale.SHI_LATN, locale.SHI, locale.SHI_TFNG, locale.AGQ, locale.KAB, locale.ZGH, locale.OC_ES:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "#,##0.00¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 7 locales
	case locale.LUO, locale.LG, locale.KM, locale.SBP, locale.KSB, locale.BEZ, locale.RWK:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "#,##0.00¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 7 locales
	case locale.NR, locale.ES_CR, locale.VE, locale.SS_SZ, locale.SS, locale.AF_NA, locale.AF:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 6 locales
	case locale.AR_MR, locale.AR_LY, locale.AR_LB, locale.AR_TN, locale.AR_DZ, locale.AR_MA:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "\u200e-",
		}
	// Group of 6 locales
	case locale.HR_BA, locale.EU, locale.FO_DK, locale.HR, locale.SL, locale.FO:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 6 locales
	case locale.LO, locale.ES_VE, locale.KL, locale.ES_EC, locale.ES_CL, locale.SG:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤#,##0.00;¤-#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 5 locales
	case locale.BGN_OM, locale.BGN_IR, locale.BGN_AE, locale.BGN_AF, locale.BGN:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: "٫",
			MinusSign:        "-",
		}
	// Group of 5 locales
	case locale.XOG, locale.TPI, locale.CE, locale.ASA, locale.MY:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 4 locales
	case locale.KHQ, locale.SES, locale.DJE, locale.TWQ:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "#,##0.00¤",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 4 locales
	case locale.NB, locale.NB_SJ, locale.NO, locale.NN:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "#,##0.00 ¤;-#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 4 locales
	case locale.TS, locale.OS_RU, locale.DE_AT, locale.OS:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤ #,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.CCP_IN, locale.BN, locale.CCP:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "#,##,##0.00¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.GSW_LI, locale.GSW, locale.GSW_FR:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   "'",
			DecimalSeparator: ".",
			MinusSign:        "−",
		}
	// Group of 3 locales
	case locale.NE, locale.AS, locale.NE_IN:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤ #,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.PS_PK, locale.UZ_ARAB, locale.PS:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "\u200e−",
		}
	// Group of 3 locales
	case locale.SEH, locale.LU, locale.RN:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "#,##0.00¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.EN_GE, locale.EN_FR:
		return FormatInfo{
			Symbol:           "UAH",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.EO, locale.VEC:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.HI_LATN, locale.EN_IN:
		return FormatInfo{
			Symbol:           "UAH",
			Format:           "¤#,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.IE, locale.BLO:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.IT_CH, locale.DE_CH:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤ #,##0.00;¤-#,##0.00",
			GroupSeparator:   "'",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.KS, locale.KS_ARAB:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤#,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.TN_BW, locale.TN:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤#,##0.00",
			GroupSeparator:   "'",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.TYV, locale.MFE:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤ #,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.UR, locale.UR_IN:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	// Group of 2 locales
	case locale.WAE, locale.LMO:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "'",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.BA:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.BAL_LATN:
		return FormatInfo{
			Symbol:           "YKNH",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.BRX:
		return FormatInfo{
			Symbol:           "इउ.ए.ऐत्स",
			Format:           "¤ #,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.DE_LI:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "'",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_150:
		return FormatInfo{
			Symbol:           "UAH",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_AT:
		return FormatInfo{
			Symbol:           "UAH",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_CH:
		return FormatInfo{
			Symbol:           "UAH",
			Format:           "¤ #,##0.00;¤-#,##0.00",
			GroupSeparator:   "'",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_ID:
		return FormatInfo{
			Symbol:           "UAH",
			Format:           "¤#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_MV:
		return FormatInfo{
			Symbol:           "UAH",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_NL:
		return FormatInfo{
			Symbol:           "UAH",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_ZA:
		return FormatInfo{
			Symbol:           "UAH",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.FA:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "\u200e¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e−",
		}
	case locale.FA_AF:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e−",
		}
	case locale.FI:
		return FormatInfo{
			Symbol:           "UAH",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	case locale.FR_CH:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   "'",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.FY:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤ #,##0.00;¤ #,##0.00-",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.HE:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "\u200f#,##0.00 \u200f¤;\u200f-#,##0.00 \u200f¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case locale.LUY:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤#,##0.00;¤- #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.NQO:
		return FormatInfo{
			Symbol:           "ߌߞߤ",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.PA_ARAB:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case locale.RM:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.TOK:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤#,#0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.XH:
		return FormatInfo{
			Symbol:           "₴",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	default:
		return FormatInfo{
			Symbol:           "UAH",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	}
}
