// Code generated by generator.go; DO NOT EDIT.

// CLDR Version: 48.2.0
// ISO 4217 Data Last Updated: Wed, 02 Sep 2026 13:40:22 GMT

package currency

import "github.com/khatibomar/fulus/locale"

var _ Currency = XSU{}

// Sucre currency type
type XSU struct{}

func (XSU) Code() string { return "XSU" }

func (XSU) Number() string { return "994" }

func (XSU) Name() string { return "Sucre" }

func (XSU) MinorUnits() int { return 2 }

func (XSU) FormatInfo(localeType locale.Locale) FormatInfo {
	switch localeType {
	// Group of 115 locales
	case locale.EN_CX, locale.GD, locale.ZH_HANT_MY, locale.EN_KE, locale.EN_KI, locale.EN_MU, locale.EN_PG, locale.EN_SD, locale.EN_TK, locale.ZH_HANS, locale.EN_AG, locale.EN_GB, locale.EN_MS, locale.EN_VI, locale.ZH_HANS_MY, locale.EN_BI, locale.EN_LR, locale.EN_PN, locale.UG, locale.CY, locale.EN_BB, locale.EN_CY, locale.EN_SL, locale.ZH_HANT_HK, locale.EN_HK, locale.EN_CC, locale.EN_NR, locale.EN_VC, locale.YUE_HANT, locale.EN_AS, locale.EN_BM, locale.EN_PK, locale.EN_BZ, locale.EN_GY, locale.EN_JE, locale.EN_MO, locale.EN_MY, locale.EN_NF, locale.EN, locale.EN_SZ, locale.EN_NG, locale.EN_VG, locale.EN_ZM, locale.EN_CM, locale.EN_IE, locale.EN_KY, locale.EN_LC, locale.EN_BW, locale.EN_GG, locale.EN_JM, locale.EN_MG, locale.EN_SB, locale.EN_SG, locale.EN_SH, locale.EN_SX, locale.EN_AI, locale.EN_BS, locale.EN_FM, locale.EN_JP, locale.EN_NZ, locale.EN_RW, locale.EN_AE, locale.EN_VU, locale.EN_ZW, locale.ZH, locale.ZH_HANS_MO, locale.EN_GI, locale.YUE, locale.YUE_HANT_MO, locale.EN_GM, locale.EN_GS, locale.EN_MT, locale.YUE_HANS, locale.ZH_HANS_HK, locale.EN_001, locale.EN_FJ, locale.ZH_HANT_MO, locale.EN_GH, locale.EN_WS, locale.EN_IO, locale.EN_MP, locale.EN_PR, locale.EN_TZ, locale.EN_DG, locale.ZH_HANT, locale.EN_PH, locale.EN_PW, locale.EN_KN, locale.EN_LS, locale.EN_NA, locale.EN_CK, locale.EN_DM, locale.EN_ER, locale.EN_GU, locale.EN_IM, locale.EN_SC, locale.EN_UG, locale.EN_GD, locale.EN_NU, locale.EN_TO, locale.EN_UM, locale.EN_CA, locale.EN_IL, locale.EN_TT, locale.JA, locale.TH, locale.YUE_HANT_CN, locale.EN_FK, locale.EN_MW, locale.EN_SS, locale.EN_TC, locale.EN_TV, locale.EN_AU, locale.EN_MH, locale.ZH_HANS_SG:
		return FormatInfo{
			Symbol:           "XSU",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 19 locales
	case locale.EN_RO, locale.EN_IT, locale.DE_LU, locale.EN_PL, locale.EN_SI, locale.EN_DE, locale.EN_DK, locale.DE_BE, locale.EN_ES, locale.AST, locale.SC, locale.DE, locale.EN_BE, locale.KU, locale.KU_LATN_IQ, locale.KU_TR, locale.DE_IT, locale.KU_LATN, locale.KU_LATN_SY:
		return FormatInfo{
			Symbol:           "XSU",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 14 locales
	case locale.EN_FI, locale.SK, locale.EN_NO, locale.EN_SK, locale.EN_EE, locale.EN_HU, locale.EN_LT, locale.EN_PT, locale.EN_SE, locale.EN_CZ, locale.CS, locale.CV, locale.EN_LV, locale.EN_UA:
		return FormatInfo{
			Symbol:           "XSU",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 8 locales
	case locale.NL_BE, locale.NL_CW, locale.NL_SX, locale.EN_NL, locale.NL_BQ, locale.NL_SR, locale.NL_AW, locale.NL:
		return FormatInfo{
			Symbol:           "XSU",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 5 locales
	case locale.LT, locale.SV, locale.FI, locale.SV_AX, locale.SV_FI:
		return FormatInfo{
			Symbol:           "XSU",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 4 locales
	case locale.NN, locale.NO, locale.NB_SJ, locale.NB:
		return FormatInfo{
			Symbol:           "XSU",
			Format:           "#,##0.00 ¤;-#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 3 locales
	case locale.EN_MV, locale.SHN, locale.SHN_TH:
		return FormatInfo{
			Symbol:           "XSU",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.HR, locale.EU, locale.HR_BA:
		return FormatInfo{
			Symbol:           "XSU",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 3 locales
	case locale.TR_CY, locale.EN_ID, locale.TR:
		return FormatInfo{
			Symbol:           "XSU",
			Format:           "¤#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.DE_CH, locale.EN_CH:
		return FormatInfo{
			Symbol:           "XSU",
			Format:           "¤ #,##0.00;¤-#,##0.00",
			GroupSeparator:   "'",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.EN_GE, locale.EN_FR:
		return FormatInfo{
			Symbol:           "XSU",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.EN_IN, locale.HI_LATN:
		return FormatInfo{
			Symbol:           "XSU",
			Format:           "¤#,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.BA:
		return FormatInfo{
			Symbol:           "XSU",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.DE_AT:
		return FormatInfo{
			Symbol:           "XSU",
			Format:           "¤ #,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.DE_LI:
		return FormatInfo{
			Symbol:           "XSU",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "'",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_150:
		return FormatInfo{
			Symbol:           "XSU",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_AT:
		return FormatInfo{
			Symbol:           "XSU",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_ZA:
		return FormatInfo{
			Symbol:           "XSU",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.FY:
		return FormatInfo{
			Symbol:           "XSU",
			Format:           "¤ #,##0.00;¤ #,##0.00-",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	default:
		return FormatInfo{
			Symbol:           "XSU",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	}
}
