// Code generated by generator.go; DO NOT EDIT.

// CLDR Version: 48.2.3
// ISO 4217 Data Last Updated: Thu, 01 Oct 2026 03:00:58 GMT

package currency

import "github.com/khatibomar/fulus/locale"

var _ Currency = ISK{}

// Iceland Krona currency type
type ISK struct{}

func (ISK) Code() string { return "ISK" }

func (ISK) Number() string { return "352" }

func (ISK) Name() string { return "Iceland Krona" }

func (ISK) MinorUnits() int { return 0 }

func (ISK) FormatInfo(localeType locale.Locale) FormatInfo {
	switch localeType {
	// Group of 151 locales
	case locale.SD_ARAB, locale.SW_KE, locale.CKB_IR, locale.GEZ, locale.ANN, locale.EN_DSRT, locale.BAL, locale.LRC_IQ, locale.SMJ_NO, locale.CKB, locale.ZA, locale.COP, locale.SAT_OLCK, locale.WAL, locale.JBO, locale.BLT, locale.BO, locale.II, locale.MUS, locale.UND, locale.CO, locale.MNI_MTEI, locale.AA_ER, locale.SSY, locale.BM_NKOO, locale.LZZ, locale.RIF, locale.YI, locale.KU_ARAB, locale.SAT, locale.HA_ARAB, locale.BGC, locale.MNI_BENG, locale.MWW_HMNP, locale.SMA, locale.MIC, locale.MAI, locale.CHO, locale.QU, locale.SUZ, locale.MYV, locale.SMJ, locale.SUZ_SUNU, locale.BQI, locale.SDH, locale.SW, locale.HA_NE, locale.SDH_IQ, locale.OSA, locale.AZ_ARAB, locale.MHN, locale.IO, locale.SYR_SY, locale.WA, locale.NV, locale.MI, locale.ES_PE, locale.BYN, locale.KAA_LATN, locale.MNI, locale.SID, locale.TRV, locale.SMA_NO, locale.AA, locale.AN, locale.MN, locale.CIC, locale.GN, locale.PI_LATN, locale.BAL_ARAB, locale.RHG, locale.TA_SG, locale.MZN, locale.KPE, locale.LRC, locale.AA_DJ, locale.SAT_DEVA, locale.KK_ARAB, locale.LAG, locale.NY, locale.QU_EC, locale.BEW, locale.EN_SHAW, locale.MDF, locale.CU, locale.TIG, locale.RAJ, locale.VO, locale.BSS, locale.SD_DEVA, locale.GAA, locale.CAD, locale.CSW, locale.MOH, locale.MWW, locale.PI, locale.QUC, locale.WBP, locale.ARN, locale.KAA, locale.RHG_ROHG_BD, locale.HA, locale.SGS, locale.KEN, locale.IU, locale.KEK, locale.PAP, locale.OKA, locale.IU_LATN, locale.DV, locale.LKT, locale.LTG, locale.NSO, locale.PAP_AW, locale.AB, locale.KS_DEVA, locale.MN_MONG, locale.PIS, locale.TA_MY, locale.FRR, locale.GEZ_ER, locale.HNJ, locale.SMS, locale.SYR, locale.SHN, locale.SKR, locale.HA_ARAB_SD, locale.ZH_LATN, locale.AZ_ARAB_TR, locale.KPE_GN, locale.SHN_TH, locale.LA, locale.TO, locale.HNJ_HMNP, locale.MG, locale.AZ_ARAB_IQ, locale.KCG, locale.APC, locale.TRW, locale.SW_UG, locale.BO_IN, locale.KAJ, locale.CCH, locale.RHG_ROHG, locale.SD, locale.SUZ_DEVA, locale.KU_ARAB_IR, locale.MGO, locale.OKA_US, locale.HA_GH, locale.KAA_CYRL:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 101 locales
	case locale.TI_ER, locale.MT, locale.OM, locale.KO_KP, locale.JA, locale.VUN, locale.GUZ, locale.MS_SG, locale.SO_KE, locale.ML, locale.OR, locale.ZH_HANS, locale.ZH_HANT_MO, locale.YO_BJ, locale.ZH_HANS_MO, locale.TEO_KE, locale.EE, locale.KI, locale.NUS, locale.OM_KE, locale.ES_BR, locale.NYN, locale.YUE_HANT_MO, locale.MER, locale.ES_CU, locale.MS_ARAB, locale.CHR, locale.ES_PR, locale.ES_SV, locale.KAM, locale.EE_TG, locale.HAW, locale.TI, locale.ES_DO, locale.AK, locale.BEM, locale.MN_MONG_MN, locale.UG, locale.SO_ET, locale.ES_419, locale.KO_CN, locale.ES_PA, locale.ZH_HANT, locale.ZH_HANT_MY, locale.GA, locale.KN, locale.KO, locale.TH, locale.SO, locale.TEO, locale.CEB, locale.SI, locale.CGG, locale.KLN, locale.GD, locale.GV, locale.ES_BZ, locale.MR, locale.VAI_VAII, locale.ES_HN, locale.MAS, locale.NAQ, locale.DOI, locale.MS, locale.ZH, locale.YO, locale.SN, locale.YUE, locale.ROF, locale.VAI_LATN, locale.ZH_HANS_MY, locale.AM, locale.BHO, locale.KW, locale.SAQ, locale.EBU, locale.YUE_HANS, locale.ST_LS, locale.VAI, locale.ES_MX, locale.CY, locale.DAV, locale.ES_US, locale.BM, locale.GA_GB, locale.PCM, locale.SO_DJ, locale.ZH_HANT_HK, locale.YUE_HANT, locale.ND, locale.MAS_TZ, locale.KDE, locale.YUE_HANT_CN, locale.ZH_HANS_HK, locale.ZH_HANS_SG, locale.ST, locale.IG, locale.ES_NI, locale.ES_GT, locale.FIL, locale.JMC:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 95 locales
	case locale.EN_TV, locale.EN_ZW, locale.EN_PN, locale.EN_VU, locale.EN_FM, locale.EN_SC, locale.EN_CA, locale.EN_AG, locale.EN_SZ, locale.EN_KI, locale.EN_TC, locale.EN_AI, locale.EN_FJ, locale.EN_MW, locale.EN_PH, locale.EN_GM, locale.EN_NF, locale.EN_ER, locale.EN_NU, locale.EN_SG, locale.EN_GH, locale.EN_PW, locale.EN_WS, locale.EN_GD, locale.EN_AS, locale.EN_GS, locale.EN_TT, locale.EN_MP, locale.EN_VG, locale.EN_VC, locale.EN_BB, locale.EN_FK, locale.EN_IL, locale.EN_LR, locale.EN_NA, locale.EN_GG, locale.EN_DG, locale.EN_PK, locale.EN_JM, locale.EN_CC, locale.EN_NR, locale.EN_RW, locale.EN, locale.EN_BM, locale.EN_GI, locale.EN_SB, locale.EN_GY, locale.EN_JP, locale.EN_SL, locale.EN_MO, locale.EN_001, locale.EN_CK, locale.EN_MH, locale.EN_PG, locale.EN_VI, locale.EN_UM, locale.EN_NG, locale.EN_TK, locale.EN_DM, locale.EN_UG, locale.EN_AE, locale.EN_IM, locale.EN_HK, locale.EN_GB, locale.EN_KN, locale.EN_BI, locale.EN_IO, locale.EN_CX, locale.EN_MU, locale.EN_NZ, locale.EN_AU, locale.EN_ZM, locale.EN_CM, locale.EN_SH, locale.EN_KY, locale.EN_BZ, locale.EN_PR, locale.EN_MT, locale.EN_SX, locale.EN_MY, locale.EN_GU, locale.EN_BW, locale.EN_IE, locale.EN_KE, locale.EN_MG, locale.EN_TZ, locale.EN_BS, locale.EN_CY, locale.EN_TO, locale.EN_JE, locale.EN_MS, locale.EN_LC, locale.EN_LS, locale.EN_SD, locale.EN_SS:
		return FormatInfo{
			Symbol:           "ISK",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 67 locales
	case locale.FF_LATN_MR, locale.UK, locale.DUA, locale.PT_CV, locale.SMN, locale.FF_LATN_GH, locale.PL, locale.TT, locale.UZ_LATN, locale.SK, locale.HU, locale.PT_MZ, locale.FF, locale.RU, locale.YAV, locale.CS, locale.FR_CA, locale.SAH, locale.PT_AO, locale.RU_BY, locale.UZ_CYRL, locale.FF_LATN_GW, locale.FF_LATN_LR, locale.FF_LATN_CM, locale.FF_LATN_GN, locale.KSF, locale.RU_MD, locale.BUA, locale.TZM, locale.HT, locale.FF_LATN_GM, locale.HY, locale.PT_GQ, locale.FF_LATN, locale.PT_ST, locale.BAS, locale.TK, locale.KK, locale.NMG, locale.FF_LATN_NE, locale.PT_MO, locale.RU_KZ, locale.FF_LATN_BF, locale.BG, locale.BR, locale.PT_GW, locale.KEA, locale.CV, locale.EWO, locale.TG, locale.FF_LATN_NG, locale.KA, locale.SZL, locale.PRG, locale.PT_LU, locale.PT_TL, locale.KY, locale.PT_CH, locale.FF_LATN_SL, locale.RU_UA, locale.DYO, locale.KK_KZ, locale.UZ, locale.LV, locale.KK_CYRL, locale.PT_PT, locale.RU_KG:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 60 locales
	case locale.DE_BE, locale.BS_CYRL, locale.EL_POLYTON, locale.ES, locale.IT, locale.DSB, locale.SR_CYRL_ME, locale.RO, locale.RO_MD, locale.BS_LATN, locale.VMW, locale.LLD, locale.KU_LATN, locale.KU_LATN_SY, locale.MK, locale.IT_SM, locale.SR, locale.LN_AO, locale.ES_IC, locale.GL, locale.SR_CYRL_BA, locale.SR_LATN, locale.LIJ, locale.BS, locale.CA_IT, locale.KU_LATN_IQ, locale.KU, locale.SR_LATN_BA, locale.EL, locale.LB, locale.SR_CYRL, locale.SR_LATN_XK, locale.SR_CYRL_XK, locale.NDS, locale.CA_AD, locale.DE_LU, locale.KU_TR, locale.AZ_LATN, locale.AZ, locale.LN_CG, locale.CA, locale.DE_IT, locale.FR_MA, locale.LN, locale.LN_CF, locale.FR_LU, locale.HSB, locale.EL_CY, locale.NDS_NL, locale.AZ_CYRL, locale.DE, locale.PMS, locale.ES_EA, locale.IT_VA, locale.CA_ES_VALENCIA, locale.VI, locale.ES_PH, locale.SR_LATN_ME, locale.CA_FR, locale.SC:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 42 locales
	case locale.FR_TD, locale.FR_SN, locale.FR_CG, locale.FR_CF, locale.FR_NE, locale.FR_BL, locale.FR_YT, locale.FR_CD, locale.FR_GQ, locale.FR_VU, locale.FR, locale.FR_BJ, locale.FR_MF, locale.FR_RE, locale.FR_HT, locale.FR_GN, locale.FR_RW, locale.FR_DZ, locale.FR_KM, locale.FR_SC, locale.FR_BI, locale.FR_GF, locale.FR_DJ, locale.FR_MU, locale.FR_GA, locale.FR_WF, locale.FR_TG, locale.FR_MQ, locale.FR_MR, locale.FR_SY, locale.FR_MG, locale.FR_CI, locale.FR_ML, locale.FR_CM, locale.FR_MC, locale.FR_TN, locale.FR_BF, locale.FR_GP, locale.FR_NC, locale.FR_PM, locale.FR_BE, locale.FR_PF:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 22 locales
	case locale.AR_IQ, locale.AR_EG, locale.AR_IL, locale.AR_SY, locale.AR_JO, locale.AR_YE, locale.AR_EH, locale.AR_KM, locale.AR_SA, locale.AR_PS, locale.AR_BH, locale.AR_KW, locale.AR, locale.AR_SS, locale.AR_SO, locale.AR_ER, locale.AR_TD, locale.AR_SD, locale.AR_AE, locale.AR_DJ, locale.AR_OM, locale.AR_QA:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	// Group of 22 locales
	case locale.MGH, locale.RW, locale.YRL, locale.QU_BO, locale.KKJ, locale.JV, locale.YRL_VE, locale.NNH, locale.MS_ARAB_BN, locale.PT, locale.FUR, locale.ES_CO, locale.ES_AR, locale.ES_UY, locale.KGP, locale.SW_CD, locale.SCN, locale.JGO, locale.IA, locale.YRL_CO, locale.WO, locale.MS_BN:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 19 locales
	case locale.HI, locale.PA_GURU, locale.KXV_DEVA, locale.TE, locale.KXV, locale.TA, locale.KXV_ORYA, locale.KXV_LATN, locale.SA, locale.GU, locale.BN_IN, locale.KXV_TELU, locale.XNR, locale.DZ, locale.KOK_DEVA, locale.KOK, locale.TA_LK, locale.KOK_LATN, locale.PA:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤#,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 14 locales
	case locale.EN_LT, locale.SQ_MK, locale.SQ, locale.EN_LV, locale.EN_SE, locale.EN_UA, locale.EN_EE, locale.EN_FI, locale.EN_CZ, locale.SQ_XK, locale.EN_PT, locale.EN_NO, locale.EN_SK, locale.EN_HU:
		return FormatInfo{
			Symbol:           "ISK",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 12 locales
	case locale.FF_ADLM_NG, locale.FF_ADLM_LR, locale.FF_ADLM_GM, locale.FF_ADLM_CM, locale.FF_ADLM_BF, locale.FF_ADLM_NE, locale.FF_ADLM_MR, locale.FF_ADLM_GW, locale.FF_ADLM_SN, locale.FF_ADLM, locale.FF_ADLM_GH, locale.FF_ADLM_SL:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "⹁",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 9 locales
	case locale.AST, locale.EN_PL, locale.EN_RO, locale.EN_BE, locale.EN_IT, locale.EN_ES, locale.EN_DE, locale.EN_SI, locale.EN_DK:
		return FormatInfo{
			Symbol:           "ISK",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 9 locales
	case locale.ES_GQ, locale.TR, locale.MS_ID, locale.SU, locale.MUA, locale.SU_LATN, locale.ES_BO, locale.TR_CY, locale.ID:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 8 locales
	case locale.NL_SX, locale.NL, locale.NL_CW, locale.NL_AW, locale.NL_BQ, locale.ES_PY, locale.NL_SR, locale.NL_BE:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 8 locales
	case locale.OC_ES, locale.SHI_TFNG, locale.AGQ, locale.OC, locale.SHI, locale.KAB, locale.SHI_LATN, locale.ZGH:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "#,##0.00¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 7 locales
	case locale.ES_CR, locale.SS, locale.VE, locale.SS_SZ, locale.AF, locale.NR, locale.AF_NA:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 7 locales
	case locale.SBP, locale.KM, locale.KSB, locale.BEZ, locale.LUO, locale.LG, locale.RWK:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "#,##0.00¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 6 locales
	case locale.AR_DZ, locale.AR_LB, locale.AR_MA, locale.AR_TN, locale.AR_LY, locale.AR_MR:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "\u200e-",
		}
	// Group of 6 locales
	case locale.ES_EC, locale.KL, locale.LO, locale.ES_CL, locale.SG, locale.ES_VE:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤#,##0.00;¤-#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 6 locales
	case locale.ET, locale.SE_FI, locale.SE, locale.LT, locale.SE_SE, locale.KSH:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 6 locales
	case locale.HR, locale.EU, locale.SL, locale.FO_DK, locale.FO, locale.HR_BA:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 5 locales
	case locale.ASA, locale.TPI, locale.MY, locale.CE, locale.XOG:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 5 locales
	case locale.BGN, locale.BGN_OM, locale.BGN_IR, locale.BGN_AE, locale.BGN_AF:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: "٫",
			MinusSign:        "-",
		}
	// Group of 4 locales
	case locale.DE_AT, locale.TS, locale.OS_RU, locale.OS:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤ #,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 4 locales
	case locale.NO, locale.NB, locale.NB_SJ, locale.NN:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "#,##0.00 ¤;-#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 4 locales
	case locale.TWQ, locale.DJE, locale.KHQ, locale.SES:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "#,##0.00¤",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.CCP_IN, locale.BN, locale.CCP:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "#,##,##0.00¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.DA, locale.DA_GL, locale.IS:
		return FormatInfo{
			Symbol:           "kr.",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.GSW_FR, locale.GSW, locale.GSW_LI:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   "'",
			DecimalSeparator: ".",
			MinusSign:        "−",
		}
	// Group of 3 locales
	case locale.LU, locale.SEH, locale.RN:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "#,##0.00¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.NE_IN, locale.AS, locale.NE:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤ #,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.PS, locale.UZ_ARAB, locale.PS_PK:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "\u200e−",
		}
	// Group of 3 locales
	case locale.SV, locale.SV_AX, locale.SV_FI:
		return FormatInfo{
			Symbol:           "Ikr",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 2 locales
	case locale.BE, locale.BE_TARASK:
		return FormatInfo{
			Symbol:           "Íkr",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.EN_FR, locale.EN_GE:
		return FormatInfo{
			Symbol:           "ISK",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.EN_IN, locale.HI_LATN:
		return FormatInfo{
			Symbol:           "ISK",
			Format:           "¤#,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.IE, locale.BLO:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.IT_CH, locale.DE_CH:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤ #,##0.00;¤-#,##0.00",
			GroupSeparator:   "'",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.KS, locale.KS_ARAB:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤#,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.LMO, locale.WAE:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "'",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.MFE, locale.TYV:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤ #,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.TN, locale.TN_BW:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤#,##0.00",
			GroupSeparator:   "'",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.UR, locale.UR_IN:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	// Group of 2 locales
	case locale.VEC, locale.EO:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.BA:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.BAL_LATN:
		return FormatInfo{
			Symbol:           "ISLK",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.BRX:
		return FormatInfo{
			Symbol:           "आई.एस.के",
			Format:           "¤ #,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.DE_LI:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "'",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_150:
		return FormatInfo{
			Symbol:           "ISK",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_AT:
		return FormatInfo{
			Symbol:           "ISK",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_CH:
		return FormatInfo{
			Symbol:           "ISK",
			Format:           "¤ #,##0.00;¤-#,##0.00",
			GroupSeparator:   "'",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_ID:
		return FormatInfo{
			Symbol:           "ISK",
			Format:           "¤#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_MV:
		return FormatInfo{
			Symbol:           "ISK",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_NL:
		return FormatInfo{
			Symbol:           "ISK",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_ZA:
		return FormatInfo{
			Symbol:           "ISK",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.FA:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "\u200e¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e−",
		}
	case locale.FA_AF:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e−",
		}
	case locale.FI:
		return FormatInfo{
			Symbol:           "ISK",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	case locale.FR_CH:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   "'",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.FY:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤ #,##0.00;¤ #,##0.00-",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.HE:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "\u200f#,##0.00 \u200f¤;\u200f-#,##0.00 \u200f¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case locale.LUY:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤#,##0.00;¤- #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.NQO:
		return FormatInfo{
			Symbol:           "ߌߛߞ",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.PA_ARAB:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case locale.RM:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.TOK:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤#,#0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.XH:
		return FormatInfo{
			Symbol:           "kr",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.ZU:
		return FormatInfo{
			Symbol:           "Kr",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	default:
		return FormatInfo{
			Symbol:           "ISK",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	}
}
