// Code generated by generator.go; DO NOT EDIT.

// CLDR Version: 47.0.0
// ISO 4217 Data Last Updated: Sat, 31 May 2025 03:00:43 GMT

package currency

import "github.com/khatibomar/fulus/locale"

var _ Currency = BBD{}

// Barbados Dollar currency type
type BBD struct{}

func (BBD) Code() string { return "BBD" }

func (BBD) Number() string { return "052" }

func (BBD) Name() string { return "Barbados Dollar" }

func (BBD) MinorUnits() int { return 2 }

func (BBD) FormatInfo(localeType locale.Locale) FormatInfo {
	switch localeType {
	// Group of 138 locales
	case locale.PAP_AW, locale.SW_UG, locale.YI, locale.AN, locale.BM_NKOO, locale.KOK, locale.CKB, locale.MZN, locale.MI, locale.MNI_BENG, locale.CHO, locale.MG, locale.GN, locale.AB, locale.GEZ_ER, locale.NY, locale.SDH_IQ, locale.RHG_ROHG, locale.ZA, locale.WA, locale.BO_IN, locale.BEW, locale.JBO, locale.MDF, locale.BGC, locale.GAA, locale.AA, locale.AZ_ARAB, locale.MNI, locale.IO, locale.OSA, locale.RIF, locale.AZ_ARAB_IQ, locale.COP, locale.KK_ARAB, locale.ANN, locale.HNJ_HMNP, locale.CKB_IR, locale.MN, locale.LRC_IQ, locale.PAP, locale.EN_SHAW, locale.ES_PE, locale.KCG, locale.CAD, locale.CU, locale.HA_NE, locale.IU, locale.TRV, locale.ARN, locale.DV, locale.HA, locale.LTG, locale.MHN, locale.MGO, locale.MOH, locale.SD, locale.FRR, locale.HA_ARAB, locale.CIC, locale.SMJ, locale.SKR, locale.SMA_NO, locale.UND, locale.BAL_ARAB, locale.TO, locale.AA_ER, locale.II, locale.BA, locale.MNI_MTEI, locale.TYV, locale.SW, locale.SYR, locale.RHG, locale.SAT, locale.SHN_TH, locale.SMJ_NO, locale.TA_SG, locale.MUS, locale.SMA, locale.BLT, locale.TRW, locale.KAA_LATN, locale.RAJ, locale.BYN, locale.SSY, locale.GEZ, locale.WAL, locale.KS_DEVA, locale.HA_ARAB_SD, locale.HNJ, locale.SHN, locale.TIG, locale.KAJ, locale.SCN, locale.SD_DEVA, locale.AA_DJ, locale.CO, locale.MAI, locale.MYV, locale.KEN, locale.RHG_ROHG_BD, locale.KPE_GN, locale.APC, locale.SYR_SY, locale.ZH_LATN, locale.EN_DSRT, locale.LKT, locale.NV, locale.MIC, locale.KAA, locale.SDH, locale.BSS, locale.SD_ARAB, locale.SAT_DEVA, locale.CSW, locale.PIS, locale.SID, locale.CCH, locale.IU_LATN, locale.AZ_ARAB_TR, locale.KOK_DEVA, locale.WBP, locale.KAA_CYRL, locale.LAG, locale.KPE, locale.SAT_OLCK, locale.SW_KE, locale.HA_GH, locale.LRC, locale.BAL, locale.VO, locale.BO, locale.MN_MONG, locale.LA, locale.QUC, locale.TA_MY, locale.SMS:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 99 locales
	case locale.ML, locale.ND, locale.SAQ, locale.ST, locale.ES_PA, locale.GD, locale.GUZ, locale.YO, locale.DOI, locale.MAS, locale.KLN, locale.YUE_HANS, locale.CY, locale.ZH_HANS, locale.ZH_HANT_MO, locale.AM, locale.GA_GB, locale.OR, locale.ZH_HANT_MY, locale.SN, locale.ZH, locale.EBU, locale.TI, locale.VUN, locale.HAW, locale.MS_SG, locale.EN_BB, locale.EE_TG, locale.ZH_HANS_MY, locale.FIL, locale.MT, locale.CHR, locale.ES_SV, locale.GA, locale.NAQ, locale.ES_BR, locale.KI, locale.KO_KP, locale.IG, locale.ES_BZ, locale.JA, locale.ES_NI, locale.MS, locale.BEM, locale.KAM, locale.KO, locale.ZH_HANT_HK, locale.ZU, locale.KW, locale.MN_MONG_MN, locale.YUE_HANT_CN, locale.YO_BJ, locale.MAS_TZ, locale.BHO, locale.ES_PR, locale.BM, locale.EE, locale.CEB, locale.ES_US, locale.YUE_HANT_MO, locale.NYN, locale.ST_LS, locale.VAI_LATN, locale.SI, locale.ZH_HANS_HK, locale.ES_MX, locale.DAV, locale.ZH_HANT, locale.YUE_HANT, locale.UG, locale.YUE, locale.MS_ARAB, locale.TI_ER, locale.VAI, locale.ES_419, locale.JMC, locale.ES_CU, locale.VAI_VAII, locale.ES_HN, locale.MR, locale.ZH_HANS_MO, locale.GV, locale.MER, locale.CGG, locale.ES_DO, locale.ZH_HANS_SG, locale.KO_CN, locale.TEO_KE, locale.AK, locale.ES_GT, locale.OM_KE, locale.TH, locale.ROF, locale.KDE, locale.TEO, locale.NUS, locale.KN, locale.OM, locale.PCM:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 93 locales
	case locale.EN_VU, locale.EN_CA, locale.EN_NG, locale.EN_AS, locale.EN_GI, locale.EN_SG, locale.EN_MP, locale.EN_NR, locale.EN_SD, locale.EN_MT, locale.EN_GB, locale.EN_KN, locale.EN_PH, locale.EN_SH, locale.EN_TO, locale.EN_TC, locale.EN_TT, locale.EN_NZ, locale.EN_GS, locale.EN_PN, locale.EN_ZW, locale.EN_MU, locale.EN_FK, locale.EN_CC, locale.EN_GY, locale.EN_UG, locale.EN_HK, locale.EN_PG, locale.EN_CX, locale.EN, locale.EN_KY, locale.EN_CK, locale.EN_FM, locale.EN_IM, locale.EN_SC, locale.EN_GH, locale.EN_TZ, locale.EN_GD, locale.EN_KI, locale.EN_PK, locale.EN_IE, locale.EN_NA, locale.EN_ZM, locale.EN_VG, locale.EN_GG, locale.EN_AG, locale.EN_MH, locale.EN_IO, locale.EN_NF, locale.EN_BZ, locale.EN_ER, locale.EN_BM, locale.EN_VI, locale.EN_AU, locale.EN_CM, locale.EN_SS, locale.EN_TV, locale.EN_SL, locale.EN_WS, locale.EN_GM, locale.EN_AI, locale.EN_DG, locale.EN_MG, locale.EN_SB, locale.EN_LS, locale.EN_DM, locale.EN_JE, locale.EN_BI, locale.EN_001, locale.EN_AE, locale.EN_TK, locale.EN_LR, locale.EN_MS, locale.EN_MY, locale.EN_IL, locale.EN_VC, locale.EN_LC, locale.EN_BW, locale.EN_FJ, locale.EN_GU, locale.EN_CY, locale.EN_RW, locale.EN_PR, locale.EN_PW, locale.EN_JM, locale.EN_UM, locale.EN_KE, locale.EN_MW, locale.EN_MO, locale.EN_SZ, locale.EN_SX, locale.EN_BS, locale.EN_NU:
		return FormatInfo{
			Symbol:           "BBD",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 66 locales
	case locale.FF_LATN, locale.HT, locale.RU, locale.TZM, locale.UK, locale.FF_LATN_BF, locale.PT_LU, locale.PT_MO, locale.UZ_LATN, locale.YAV, locale.RU_KZ, locale.PT_ST, locale.TT, locale.EO, locale.PT_CH, locale.FR_CA, locale.FF_LATN_GM, locale.PT_GQ, locale.KK_KZ, locale.SZL, locale.PT_AO, locale.BAS, locale.PT_CV, locale.PRG, locale.KK_CYRL, locale.FF_LATN_MR, locale.CV, locale.DYO, locale.FF_LATN_SL, locale.RU_UA, locale.NMG, locale.RU_KG, locale.KY, locale.KSF, locale.KA, locale.FF_LATN_GN, locale.BR, locale.SMN, locale.RU_MD, locale.EWO, locale.KEA, locale.LV, locale.FF_LATN_GH, locale.UZ, locale.PT_PT, locale.SAH, locale.PT_MZ, locale.PT_GW, locale.FF_LATN_CM, locale.FF_LATN_GW, locale.PT_TL, locale.CS, locale.RU_BY, locale.KK, locale.FF_LATN_NG, locale.FF_LATN_NE, locale.SK, locale.FF, locale.FF_LATN_LR, locale.UZ_CYRL, locale.HY, locale.DUA, locale.HU, locale.TK, locale.PL, locale.TG:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 59 locales
	case locale.ES, locale.CA_AD, locale.ES_IC, locale.RO_MD, locale.SR_CYRL, locale.FR_MA, locale.CA, locale.DA, locale.SR_LATN_XK, locale.IT, locale.LB, locale.AZ_CYRL, locale.SR_LATN, locale.VI, locale.DE_LU, locale.AZ_LATN, locale.SR_CYRL_BA, locale.LN, locale.CA_FR, locale.LN_CG, locale.NDS, locale.LLD, locale.BS_LATN, locale.EL_CY, locale.SR_CYRL_XK, locale.DE_IT, locale.RO, locale.EL, locale.BS, locale.GL, locale.DA_GL, locale.DSB, locale.NDS_NL, locale.HSB, locale.LIJ, locale.AST, locale.ES_PH, locale.AZ, locale.CA_IT, locale.MK, locale.VMW, locale.SR_CYRL_ME, locale.DE, locale.DE_BE, locale.FR_LU, locale.LN_CF, locale.LN_AO, locale.SR_LATN_BA, locale.SR, locale.IT_SM, locale.CA_ES_VALENCIA, locale.KU, locale.SC, locale.SR_LATN_ME, locale.IT_VA, locale.EL_POLYTON, locale.ES_EA, locale.IS, locale.BS_CYRL:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 43 locales
	case locale.FR_GA, locale.FR_NC, locale.FR_SC, locale.FR_DJ, locale.FR_SN, locale.FR_GQ, locale.FR_CG, locale.FR_MR, locale.FR_MU, locale.FR_YT, locale.FR_PM, locale.FR_RW, locale.FR_NE, locale.FR_SY, locale.FR_BF, locale.FR_HT, locale.FR_CM, locale.FR_GF, locale.FR_BI, locale.FR_PF, locale.FR_TG, locale.FR_DZ, locale.FR_WF, locale.FR_CH, locale.FR_MG, locale.FR_CD, locale.FR_MC, locale.FR_TD, locale.FR_MQ, locale.FR_KM, locale.FR_ML, locale.FR_GP, locale.FR_MF, locale.FR_RE, locale.FR_BL, locale.FR_BE, locale.FR_BJ, locale.FR_CI, locale.FR_TN, locale.FR_CF, locale.FR_VU, locale.FR_GN, locale.FR:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 22 locales
	case locale.AR_TD, locale.AR_EH, locale.AR_SY, locale.AR_OM, locale.AR, locale.AR_AE, locale.AR_SD, locale.AR_PS, locale.AR_IQ, locale.AR_YE, locale.AR_JO, locale.AR_SO, locale.AR_QA, locale.AR_SS, locale.AR_EG, locale.AR_SA, locale.AR_KM, locale.AR_ER, locale.AR_DJ, locale.AR_KW, locale.AR_BH, locale.AR_IL:
		return FormatInfo{
			Symbol:           "BB$",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	// Group of 20 locales
	case locale.NNH, locale.SW_CD, locale.WO, locale.JGO, locale.MS_BN, locale.MGH, locale.MS_ARAB_BN, locale.PT, locale.YRL_VE, locale.YRL_CO, locale.IA, locale.JV, locale.FUR, locale.YRL, locale.RW, locale.KKJ, locale.KGP, locale.ES_AR, locale.ES_UY, locale.ES_CO:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 17 locales
	case locale.DZ, locale.TA_LK, locale.SA, locale.GU, locale.TA, locale.XNR, locale.BN_IN, locale.TE, locale.KXV_LATN, locale.KOK_LATN, locale.KXV_DEVA, locale.PA, locale.KXV_TELU, locale.HI, locale.KXV, locale.KXV_ORYA, locale.PA_GURU:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 12 locales
	case locale.FF_ADLM_GM, locale.FF_ADLM_LR, locale.FF_ADLM, locale.FF_ADLM_MR, locale.FF_ADLM_GH, locale.FF_ADLM_GW, locale.FF_ADLM_NG, locale.FF_ADLM_BF, locale.FF_ADLM_SN, locale.FF_ADLM_CM, locale.FF_ADLM_NE, locale.FF_ADLM_SL:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "⹁",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 11 locales
	case locale.EN_CZ, locale.EN_SK, locale.EN_SE, locale.SQ_MK, locale.EN_HU, locale.SQ_XK, locale.EN_FI, locale.EN_PT, locale.BG, locale.SQ, locale.EN_NO:
		return FormatInfo{
			Symbol:           "BBD",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 9 locales
	case locale.ES_GQ, locale.MS_ID, locale.ID, locale.ES_BO, locale.MUA, locale.SU_LATN, locale.TR, locale.SU, locale.TR_CY:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 8 locales
	case locale.EN_ES, locale.EN_IT, locale.EN_BE, locale.EN_PL, locale.EN_SI, locale.EN_RO, locale.EN_DE, locale.EN_DK:
		return FormatInfo{
			Symbol:           "BBD",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 8 locales
	case locale.NL_BE, locale.NL_BQ, locale.NL_AW, locale.NL_CW, locale.ES_PY, locale.NL_SR, locale.NL, locale.NL_SX:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 8 locales
	case locale.OC_ES, locale.KAB, locale.SHI_TFNG, locale.AGQ, locale.ZGH, locale.SHI_LATN, locale.SHI, locale.OC:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 7 locales
	case locale.ES_CR, locale.AF, locale.NR, locale.VE, locale.SS_SZ, locale.AF_NA, locale.SS:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 7 locales
	case locale.LUO, locale.BEZ, locale.SBP, locale.KM, locale.KSB, locale.RWK, locale.LG:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 6 locales
	case locale.AR_DZ, locale.AR_LB, locale.AR_MR, locale.AR_TN, locale.AR_LY, locale.AR_MA:
		return FormatInfo{
			Symbol:           "BB$",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "\u200e-",
		}
	// Group of 6 locales
	case locale.HR, locale.SL, locale.HR_BA, locale.FO, locale.EU, locale.FO_DK:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 6 locales
	case locale.SE, locale.LT, locale.KSH, locale.SE_FI, locale.SE_SE, locale.ET:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 6 locales
	case locale.SG, locale.ES_CL, locale.KL, locale.LO, locale.ES_EC, locale.ES_VE:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,##0.00;¤-#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 5 locales
	case locale.BGN_IR, locale.BGN_AE, locale.BGN_AF, locale.BGN, locale.BGN_OM:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: "٫",
			MinusSign:        "-",
		}
	// Group of 4 locales
	case locale.KHQ, locale.SES, locale.TWQ, locale.DJE:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00¤",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 4 locales
	case locale.NB_SJ, locale.NB, locale.NN, locale.NO:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00 ¤;-#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 4 locales
	case locale.OS, locale.DE_AT, locale.OS_RU, locale.TS:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 4 locales
	case locale.RM, locale.GSW_FR, locale.GSW_LI, locale.GSW:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "−",
		}
	// Group of 4 locales
	case locale.SO_DJ, locale.SO_ET, locale.SO, locale.SO_KE:
		return FormatInfo{
			Symbol:           "DBB",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 4 locales
	case locale.XOG, locale.TPI, locale.CE, locale.ASA:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.CCP, locale.BN, locale.CCP_IN:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##,##0.00¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.NE_IN, locale.NE, locale.AS:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.PS_PK, locale.UZ_ARAB, locale.PS:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "\u200e−",
		}
	// Group of 3 locales
	case locale.SEH, locale.LU, locale.RN:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.SV_FI, locale.SV_AX, locale.SV:
		return FormatInfo{
			Symbol:           "Bds$",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 2 locales
	case locale.BE, locale.BE_TARASK:
		return FormatInfo{
			Symbol:           "Bds$",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.BLO, locale.IE:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.DE_CH, locale.IT_CH:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00;¤-#,##0.00",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.HI_LATN, locale.EN_IN:
		return FormatInfo{
			Symbol:           "BBD",
			Format:           "¤#,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.KS_ARAB, locale.KS:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.MFE, locale.NSO:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.QU_EC, locale.QU:
		return FormatInfo{
			Symbol:           "BBG",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.TN, locale.TN_BW:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,##0.00",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.UR_IN, locale.UR:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	// Group of 2 locales
	case locale.WAE, locale.LMO:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "’",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.BAL_LATN:
		return FormatInfo{
			Symbol:           "BRBD",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.BRX:
		return FormatInfo{
			Symbol:           "बि.बि.दि",
			Format:           "¤ #,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.DE_LI:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_150:
		return FormatInfo{
			Symbol:           "BBD",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_AT:
		return FormatInfo{
			Symbol:           "BBD",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_CH:
		return FormatInfo{
			Symbol:           "BBD",
			Format:           "¤ #,##0.00;¤-#,##0.00",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_FR:
		return FormatInfo{
			Symbol:           "BBD",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_ID:
		return FormatInfo{
			Symbol:           "BBD",
			Format:           "¤#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_MV:
		return FormatInfo{
			Symbol:           "BBD",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_NL:
		return FormatInfo{
			Symbol:           "BBD",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_ZA:
		return FormatInfo{
			Symbol:           "BBD",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.FA:
		return FormatInfo{
			Symbol:           "$",
			Format:           "\u200e¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e−",
		}
	case locale.FA_AF:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e−",
		}
	case locale.FI:
		return FormatInfo{
			Symbol:           "BBD",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	case locale.FY:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00;¤ #,##0.00-",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.HE:
		return FormatInfo{
			Symbol:           "$",
			Format:           "\u200f#,##0.00 \u200f¤;\u200f-#,##0.00 \u200f¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case locale.LUY:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,##0.00;¤- #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.MY:
		return FormatInfo{
			Symbol:           "Bds$",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.NQO:
		return FormatInfo{
			Symbol:           "ߓߓߘ",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.PA_ARAB:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case locale.QU_BO:
		return FormatInfo{
			Symbol:           "BBG",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.TOK:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,#0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.VEC:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.XH:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	default:
		return FormatInfo{
			Symbol:           "BBD",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	}
}
