// Code generated by generator.go; DO NOT EDIT.

// CLDR Version: 48.2.0
// ISO 4217 Data Last Updated: Wed, 02 Sep 2026 13:40:22 GMT

package currency

import "github.com/khatibomar/fulus/locale"

var _ Currency = CUP{}

// Cuban Peso currency type
type CUP struct{}

func (CUP) Code() string { return "CUP" }

func (CUP) Number() string { return "192" }

func (CUP) Name() string { return "Cuban Peso" }

func (CUP) MinorUnits() int { return 2 }

func (CUP) FormatInfo(localeType locale.Locale) FormatInfo {
	switch localeType {
	// Group of 151 locales
	case locale.SMS, locale.MIC, locale.WAL, locale.CIC, locale.RHG_ROHG_BD, locale.TA_MY, locale.CHO, locale.CKB_IR, locale.QU_EC, locale.SKR, locale.AZ_ARAB_TR, locale.MNI_MTEI, locale.SD_DEVA, locale.KS_DEVA, locale.AZ_ARAB_IQ, locale.TIG, locale.IO, locale.IU_LATN, locale.BLT, locale.BQI, locale.RHG, locale.CU, locale.ARN, locale.GN, locale.KK_ARAB, locale.PIS, locale.SUZ, locale.BO_IN, locale.VO, locale.BYN, locale.KAA_LATN, locale.KU_ARAB, locale.SW_KE, locale.SMJ, locale.KEN, locale.WBP, locale.COP, locale.CO, locale.MGO, locale.KPE_GN, locale.QUC, locale.HNJ_HMNP, locale.OSA, locale.HA_ARAB_SD, locale.MHN, locale.OKA, locale.SAT_OLCK, locale.TA_SG, locale.GEZ_ER, locale.KU_ARAB_IR, locale.SGS, locale.NV, locale.MNI, locale.KAA, locale.QU, locale.APC, locale.BSS, locale.LKT, locale.MZN, locale.BO, locale.ZH_LATN, locale.ANN, locale.KAA_CYRL, locale.CAD, locale.MUS, locale.YI, locale.ZA, locale.LAG, locale.MG, locale.SSY, locale.HA_NE, locale.SDH_IQ, locale.MN, locale.BGC, locale.LTG, locale.MI, locale.SAT, locale.SHN_TH, locale.HNJ, locale.RHG_ROHG, locale.HA_GH, locale.HA_ARAB, locale.PAP, locale.PAP_AW, locale.SAT_DEVA, locale.AZ_ARAB, locale.GEZ, locale.IU, locale.PI, locale.FRR, locale.SD_ARAB, locale.MOH, locale.UND, locale.HA, locale.SID, locale.CCH, locale.NY, locale.AN, locale.GAA, locale.RIF, locale.SW, locale.MN_MONG, locale.MDF, locale.SYR_SY, locale.PI_LATN, locale.MAI, locale.SHN, locale.TO, locale.OKA_US, locale.AA_DJ, locale.LA, locale.MWW_HMNP, locale.SUZ_SUNU, locale.ES_PE, locale.II, locale.JBO, locale.KAJ, locale.NSO, locale.MWW, locale.MYV, locale.RAJ, locale.KEK, locale.SW_UG, locale.TRW, locale.CKB, locale.LRC_IQ, locale.LRC, locale.SD, locale.SUZ_DEVA, locale.AA_ER, locale.BM_NKOO, locale.EN_DSRT, locale.BEW, locale.LZZ, locale.SYR, locale.TRV, locale.BAL, locale.KCG, locale.SMA, locale.AB, locale.SMA_NO, locale.BAL_ARAB, locale.SMJ_NO, locale.CSW, locale.AA, locale.DV, locale.SDH, locale.KPE, locale.EN_SHAW, locale.MNI_BENG, locale.WA:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 102 locales
	case locale.CEB, locale.MS_ARAB, locale.KN, locale.NYN, locale.KLN, locale.BHO, locale.BM, locale.TEO, locale.ZH, locale.ZH_HANT_HK, locale.KW, locale.AM, locale.YUE_HANT, locale.KAM, locale.MAS, locale.MT, locale.PCM, locale.VAI_VAII, locale.VUN, locale.YO, locale.KDE, locale.ZH_HANT_MY, locale.YUE_HANS, locale.ES_US, locale.HAW, locale.ST_LS, locale.SO_KE, locale.UG, locale.GD, locale.TEO_KE, locale.CGG, locale.YO_BJ, locale.ZH_HANS_MY, locale.ES_SV, locale.NUS, locale.ES_PA, locale.MS, locale.MAS_TZ, locale.EBU, locale.CY, locale.ND, locale.DOI, locale.TI_ER, locale.OM, locale.NAQ, locale.ES_HN, locale.BEM, locale.KI, locale.YUE_HANT_CN, locale.ES_BZ, locale.ZH_HANS_HK, locale.EE, locale.ZH_HANS_SG, locale.ML, locale.MER, locale.JMC, locale.MR, locale.MS_SG, locale.ZH_HANT_MO, locale.KO_KP, locale.SN, locale.DAV, locale.ES_DO, locale.OM_KE, locale.ST, locale.ES_419, locale.FIL, locale.TI, locale.VAI_LATN, locale.GA_GB, locale.ES_CU, locale.JA, locale.CHR, locale.ZU, locale.GUZ, locale.EE_TG, locale.OR, locale.KO, locale.ROF, locale.ES_MX, locale.GV, locale.SI, locale.SO_DJ, locale.ZH_HANS, locale.AK, locale.TH, locale.ES_PR, locale.ES_BR, locale.GA, locale.IG, locale.SO_ET, locale.SO, locale.ZH_HANS_MO, locale.VAI, locale.SAQ, locale.YUE, locale.ES_NI, locale.ZH_HANT, locale.ES_GT, locale.YUE_HANT_MO, locale.MN_MONG_MN, locale.KO_CN:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 95 locales
	case locale.EN_NU, locale.EN_MY, locale.EN_AG, locale.EN_001, locale.EN_PG, locale.EN_NA, locale.EN_WS, locale.EN_FM, locale.EN_TZ, locale.EN_BI, locale.EN_BZ, locale.EN_IO, locale.EN_KY, locale.EN_VG, locale.EN_MS, locale.EN_KN, locale.EN_KE, locale.EN_RW, locale.EN_LS, locale.EN_VC, locale.EN_GH, locale.EN_FK, locale.EN_UG, locale.EN_GG, locale.EN_UM, locale.EN_JM, locale.EN_NZ, locale.EN_TT, locale.EN_HK, locale.EN_MH, locale.EN_SS, locale.EN_JE, locale.EN_AI, locale.EN_NR, locale.EN_IL, locale.EN_JP, locale.EN_MP, locale.EN_TO, locale.EN_FJ, locale.EN_LC, locale.EN_ZM, locale.EN_CA, locale.EN_DG, locale.EN_KI, locale.EN_CY, locale.EN_CC, locale.EN_TC, locale.EN_VU, locale.EN_SX, locale.EN_GI, locale.EN_SB, locale.EN_BS, locale.EN_SH, locale.EN_SZ, locale.EN_MW, locale.EN_SC, locale.EN_SL, locale.EN_GM, locale.EN_TV, locale.EN, locale.EN_GB, locale.EN_GD, locale.EN_CM, locale.EN_GY, locale.EN_MT, locale.EN_SG, locale.EN_TK, locale.EN_SD, locale.EN_PK, locale.EN_GU, locale.EN_IE, locale.EN_PH, locale.EN_GS, locale.EN_MO, locale.EN_CX, locale.EN_DM, locale.EN_NF, locale.EN_LR, locale.EN_BB, locale.EN_PN, locale.EN_CK, locale.EN_PR, locale.EN_MG, locale.EN_AE, locale.EN_PW, locale.EN_AS, locale.EN_VI, locale.EN_ER, locale.EN_BW, locale.EN_ZW, locale.EN_IM, locale.EN_NG, locale.EN_BM, locale.EN_MU, locale.EN_AU:
		return FormatInfo{
			Symbol:           "CUP",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 66 locales
	case locale.FF_LATN_LR, locale.NMG, locale.DUA, locale.KK_CYRL, locale.FF_LATN_GW, locale.FF_LATN_NG, locale.FF_LATN_NE, locale.RU_UA, locale.KA, locale.PT_CV, locale.PT_LU, locale.PT_CH, locale.DYO, locale.FF, locale.PT_AO, locale.CS, locale.KK, locale.SK, locale.EWO, locale.FR_CA, locale.FF_LATN_GN, locale.TZM, locale.KSF, locale.TG, locale.PT_MO, locale.RU, locale.KEA, locale.LV, locale.SZL, locale.PL, locale.PT_PT, locale.UZ_LATN, locale.PT_GW, locale.YAV, locale.UZ_CYRL, locale.CV, locale.FF_LATN_CM, locale.FF_LATN_GH, locale.RU_BY, locale.UZ, locale.RU_KG, locale.FF_LATN, locale.TK, locale.HU, locale.PT_MZ, locale.PRG, locale.PT_TL, locale.FF_LATN_BF, locale.BR, locale.SMN, locale.HT, locale.FF_LATN_GM, locale.PT_ST, locale.PT_GQ, locale.KK_KZ, locale.SAH, locale.BUA, locale.UK, locale.RU_KZ, locale.FF_LATN_MR, locale.FF_LATN_SL, locale.RU_MD, locale.KY, locale.BAS, locale.TT, locale.HY:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 64 locales
	case locale.FR_MA, locale.DE_LU, locale.PMS, locale.EL_POLYTON, locale.SR_CYRL_ME, locale.RO, locale.CA_ES_VALENCIA, locale.SR_CYRL_XK, locale.DA_GL, locale.AZ_CYRL, locale.NDS, locale.SC, locale.SR_LATN_ME, locale.ES_EA, locale.SR, locale.ES_PH, locale.IT_VA, locale.IT, locale.IT_SM, locale.KU_LATN, locale.CA_AD, locale.FR_LU, locale.HSB, locale.LN_AO, locale.LB, locale.KU_LATN_SY, locale.BS, locale.LN, locale.LN_CG, locale.EL, locale.DSB, locale.MK, locale.VI, locale.BS_LATN, locale.EL_CY, locale.ES_IC, locale.NDS_NL, locale.BS_CYRL, locale.KU_LATN_IQ, locale.CA_IT, locale.AZ, locale.DE, locale.DE_IT, locale.RO_MD, locale.VMW, locale.IS, locale.DA, locale.ES, locale.LN_CF, locale.SR_CYRL, locale.GL, locale.KU, locale.CA, locale.SR_CYRL_BA, locale.SR_LATN, locale.AZ_LATN, locale.LIJ, locale.LLD, locale.SR_LATN_BA, locale.CA_FR, locale.SR_LATN_XK, locale.KU_TR, locale.DE_BE, locale.AST:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 42 locales
	case locale.FR_HT, locale.FR_CG, locale.FR_MF, locale.FR_GA, locale.FR_NE, locale.FR_GQ, locale.FR_BF, locale.FR_WF, locale.FR_BJ, locale.FR_MR, locale.FR_NC, locale.FR_TN, locale.FR_PF, locale.FR_SN, locale.FR, locale.FR_GP, locale.FR_DJ, locale.FR_MG, locale.FR_KM, locale.FR_GN, locale.FR_PM, locale.FR_VU, locale.FR_MQ, locale.FR_CF, locale.FR_TG, locale.FR_CM, locale.FR_BL, locale.FR_RE, locale.FR_BE, locale.FR_ML, locale.FR_BI, locale.FR_TD, locale.FR_RW, locale.FR_YT, locale.FR_SY, locale.FR_CD, locale.FR_GF, locale.FR_MU, locale.FR_SC, locale.FR_MC, locale.FR_CI, locale.FR_DZ:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 22 locales
	case locale.AR, locale.AR_JO, locale.AR_KW, locale.AR_BH, locale.AR_DJ, locale.AR_ER, locale.AR_IQ, locale.AR_TD, locale.AR_SY, locale.AR_KM, locale.AR_SD, locale.AR_YE, locale.AR_EH, locale.AR_IL, locale.AR_QA, locale.AR_SA, locale.AR_PS, locale.AR_OM, locale.AR_SO, locale.AR_AE, locale.AR_SS, locale.AR_EG:
		return FormatInfo{
			Symbol:           "CU$",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	// Group of 22 locales
	case locale.NNH, locale.YRL_CO, locale.KKJ, locale.WO, locale.SW_CD, locale.QU_BO, locale.FUR, locale.IA, locale.MS_BN, locale.SCN, locale.PT, locale.KGP, locale.ES_CO, locale.MGH, locale.YRL_VE, locale.YRL, locale.ES_AR, locale.RW, locale.JGO, locale.ES_UY, locale.MS_ARAB_BN, locale.JV:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 19 locales
	case locale.PA, locale.KOK, locale.TA_LK, locale.XNR, locale.TE, locale.KXV, locale.BN_IN, locale.KXV_ORYA, locale.KXV_LATN, locale.HI, locale.KOK_LATN, locale.KXV_TELU, locale.TA, locale.DZ, locale.KOK_DEVA, locale.GU, locale.SA, locale.PA_GURU, locale.KXV_DEVA:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 15 locales
	case locale.EN_CZ, locale.BG, locale.EN_NO, locale.EN_EE, locale.EN_SE, locale.EN_FI, locale.SQ_XK, locale.SQ_MK, locale.EN_LT, locale.EN_HU, locale.SQ, locale.EN_LV, locale.EN_SK, locale.EN_UA, locale.EN_PT:
		return FormatInfo{
			Symbol:           "CUP",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 12 locales
	case locale.FF_ADLM_BF, locale.FF_ADLM_GH, locale.FF_ADLM_GM, locale.FF_ADLM_NE, locale.FF_ADLM_CM, locale.FF_ADLM_SL, locale.FF_ADLM_MR, locale.FF_ADLM_GW, locale.FF_ADLM, locale.FF_ADLM_LR, locale.FF_ADLM_SN, locale.FF_ADLM_NG:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "⹁",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 9 locales
	case locale.ET, locale.SV_AX, locale.SV, locale.SV_FI, locale.KSH, locale.SE, locale.SE_FI, locale.LT, locale.SE_SE:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 9 locales
	case locale.TR, locale.MUA, locale.ES_GQ, locale.SU, locale.MS_ID, locale.ES_BO, locale.TR_CY, locale.ID, locale.SU_LATN:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 8 locales
	case locale.AGQ, locale.ZGH, locale.SHI, locale.OC_ES, locale.KAB, locale.SHI_TFNG, locale.OC, locale.SHI_LATN:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 8 locales
	case locale.EN_DE, locale.EN_SI, locale.EN_DK, locale.EN_RO, locale.EN_IT, locale.EN_ES, locale.EN_PL, locale.EN_BE:
		return FormatInfo{
			Symbol:           "CUP",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 8 locales
	case locale.NL_SR, locale.NL_CW, locale.NL_BQ, locale.NL_SX, locale.NL_AW, locale.NL_BE, locale.NL, locale.ES_PY:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 7 locales
	case locale.BEZ, locale.KM, locale.LUO, locale.KSB, locale.RWK, locale.LG, locale.SBP:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 7 locales
	case locale.SS, locale.SS_SZ, locale.VE, locale.NR, locale.ES_CR, locale.AF_NA, locale.AF:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 6 locales
	case locale.AR_LB, locale.AR_DZ, locale.AR_MA, locale.AR_LY, locale.AR_TN, locale.AR_MR:
		return FormatInfo{
			Symbol:           "CU$",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "\u200e-",
		}
	// Group of 6 locales
	case locale.FO, locale.HR_BA, locale.SL, locale.FO_DK, locale.HR, locale.EU:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 6 locales
	case locale.KL, locale.LO, locale.ES_VE, locale.ES_EC, locale.SG, locale.ES_CL:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,##0.00;¤-#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 5 locales
	case locale.BGN, locale.BGN_OM, locale.BGN_AF, locale.BGN_AE, locale.BGN_IR:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: "٫",
			MinusSign:        "-",
		}
	// Group of 5 locales
	case locale.XOG, locale.MY, locale.TPI, locale.ASA, locale.CE:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 4 locales
	case locale.KHQ, locale.TWQ, locale.DJE, locale.SES:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00¤",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 4 locales
	case locale.NO, locale.NB, locale.NN, locale.NB_SJ:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00 ¤;-#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 4 locales
	case locale.TS, locale.OS, locale.DE_AT, locale.OS_RU:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.CCP_IN, locale.BN, locale.CCP:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##,##0.00¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.GSW_FR, locale.GSW, locale.GSW_LI:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   "'",
			DecimalSeparator: ".",
			MinusSign:        "−",
		}
	// Group of 3 locales
	case locale.NE_IN, locale.NE, locale.AS:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.PS_PK, locale.UZ_ARAB, locale.PS:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "\u200e−",
		}
	// Group of 3 locales
	case locale.RN, locale.LU, locale.SEH:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.BE_TARASK, locale.BE:
		return FormatInfo{
			Symbol:           "$MN",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.EN_GE, locale.EN_FR:
		return FormatInfo{
			Symbol:           "CUP",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.EO, locale.VEC:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.HI_LATN, locale.EN_IN:
		return FormatInfo{
			Symbol:           "CUP",
			Format:           "¤#,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.IE, locale.BLO:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.IT_CH, locale.DE_CH:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00;¤-#,##0.00",
			GroupSeparator:   "'",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.KS, locale.KS_ARAB:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.TN_BW, locale.TN:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,##0.00",
			GroupSeparator:   "'",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.TYV, locale.MFE:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.UR_IN, locale.UR:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	// Group of 2 locales
	case locale.WAE, locale.LMO:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "'",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.BA:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.BAL_LATN:
		return FormatInfo{
			Symbol:           "CBAP",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.BRX:
		return FormatInfo{
			Symbol:           "सि.इउ.पि",
			Format:           "¤ #,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.DE_LI:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "'",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_150:
		return FormatInfo{
			Symbol:           "CUP",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_AT:
		return FormatInfo{
			Symbol:           "CUP",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_CH:
		return FormatInfo{
			Symbol:           "CUP",
			Format:           "¤ #,##0.00;¤-#,##0.00",
			GroupSeparator:   "'",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_ID:
		return FormatInfo{
			Symbol:           "CUP",
			Format:           "¤#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_MV:
		return FormatInfo{
			Symbol:           "CUP",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_NL:
		return FormatInfo{
			Symbol:           "CUP",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_ZA:
		return FormatInfo{
			Symbol:           "CUP",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.FA:
		return FormatInfo{
			Symbol:           "$",
			Format:           "\u200e¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e−",
		}
	case locale.FA_AF:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e−",
		}
	case locale.FI:
		return FormatInfo{
			Symbol:           "CUP",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	case locale.FR_CH:
		return FormatInfo{
			Symbol:           "$",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   "'",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.FY:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00;¤ #,##0.00-",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.HE:
		return FormatInfo{
			Symbol:           "$",
			Format:           "\u200f#,##0.00 \u200f¤;\u200f-#,##0.00 \u200f¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case locale.LUY:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,##0.00;¤- #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.NQO:
		return FormatInfo{
			Symbol:           "ߞߎ߳ߔ",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.PA_ARAB:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case locale.RM:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.TOK:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,#0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.XH:
		return FormatInfo{
			Symbol:           "$",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	default:
		return FormatInfo{
			Symbol:           "CUP",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	}
}
