// Code generated by generator.go; DO NOT EDIT.

// CLDR Version: 47.0.0
// ISO 4217 Data Last Updated: Sat, 31 May 2025 03:00:43 GMT

package currency

import "github.com/khatibomar/fulus/locale"

var _ Currency = LKR{}

// Sri Lanka Rupee currency type
type LKR struct{}

func (LKR) Code() string { return "LKR" }

func (LKR) Number() string { return "144" }

func (LKR) Name() string { return "Sri Lanka Rupee" }

func (LKR) MinorUnits() int { return 2 }

func (LKR) FormatInfo(localeType locale.Locale) FormatInfo {
	switch localeType {
	// Group of 140 locales
	case locale.AA_ER, locale.ARN, locale.HA_ARAB, locale.HNJ, locale.BSS, locale.LRC_IQ, locale.UND, locale.ES_PE, locale.KPE_GN, locale.SW_KE, locale.NY, locale.QUC, locale.AZ_ARAB_TR, locale.BAL, locale.LTG, locale.BM_NKOO, locale.SW, locale.MNI_BENG, locale.MN, locale.KOK_DEVA, locale.II, locale.SMJ, locale.RAJ, locale.GAA, locale.SAT, locale.SMS, locale.LKT, locale.MZN, locale.RHG_ROHG_BD, locale.YI, locale.IU_LATN, locale.MNI_MTEI, locale.SDH_IQ, locale.LRC, locale.PAP, locale.SCN, locale.SYR_SY, locale.MYV, locale.ZH_LATN, locale.BGC, locale.AA_DJ, locale.IO, locale.KAA_CYRL, locale.KS_DEVA, locale.BO_IN, locale.QU_EC, locale.WBP, locale.SMJ_NO, locale.CU, locale.WAL, locale.HA, locale.HA_NE, locale.RHG_ROHG, locale.HNJ_HMNP, locale.IU, locale.NV, locale.GEZ, locale.CCH, locale.SSY, locale.CIC, locale.TIG, locale.KAA, locale.SW_UG, locale.DV, locale.SHN, locale.CSW, locale.HA_ARAB_SD, locale.TRW, locale.ZA, locale.GEZ_ER, locale.PIS, locale.RHG, locale.AZ_ARAB_IQ, locale.VO, locale.SAT_OLCK, locale.SD_DEVA, locale.TO, locale.BYN, locale.CAD, locale.MOH, locale.SMA, locale.TA_MY, locale.BLT, locale.KAA_LATN, locale.MI, locale.TRV, locale.AZ_ARAB, locale.BA, locale.KEN, locale.MDF, locale.MHN, locale.LA, locale.BEW, locale.AB, locale.CO, locale.JBO, locale.KCG, locale.LAG, locale.MN_MONG, locale.BAL_ARAB, locale.CHO, locale.MG, locale.SID, locale.AA, locale.MIC, locale.SHN_TH, locale.EN_DSRT, locale.KAJ, locale.TA_SG, locale.OSA, locale.BO, locale.HA_GH, locale.RIF, locale.KK_ARAB, locale.KOK, locale.SDH, locale.ANN, locale.APC, locale.SMA_NO, locale.SYR, locale.WA, locale.CKB, locale.QU, locale.COP, locale.MNI, locale.SAT_DEVA, locale.SD_ARAB, locale.MGO, locale.FRR, locale.MAI, locale.TYV, locale.GN, locale.EN_SHAW, locale.AN, locale.PAP_AW, locale.CKB_IR, locale.MUS, locale.SKR, locale.KPE, locale.SD:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 101 locales
	case locale.SO_KE, locale.ES_BZ, locale.MAS_TZ, locale.ZH_HANS, locale.ZH_HANS_SG, locale.ES_NI, locale.ZH_HANT, locale.MT, locale.OR, locale.TI_ER, locale.YUE_HANT, locale.MS_SG, locale.TH, locale.KN, locale.KI, locale.VAI, locale.JMC, locale.SO_ET, locale.AK, locale.VAI_VAII, locale.KO, locale.ES_419, locale.GD, locale.DOI, locale.VAI_LATN, locale.KDE, locale.YUE_HANT_MO, locale.GUZ, locale.MAS, locale.NAQ, locale.NUS, locale.YUE, locale.KAM, locale.JA, locale.ES_HN, locale.PCM, locale.TI, locale.ML, locale.SN, locale.GA, locale.ZH_HANS_HK, locale.EE_TG, locale.KO_CN, locale.ND, locale.TEO_KE, locale.NYN, locale.CY, locale.EBU, locale.ES_CU, locale.YUE_HANT_CN, locale.MS, locale.YO, locale.GA_GB, locale.CEB, locale.CGG, locale.BEM, locale.EE, locale.OM_KE, locale.UG, locale.CHR, locale.ZH, locale.VUN, locale.MS_ARAB, locale.ST_LS, locale.KO_KP, locale.ES_BR, locale.ES_GT, locale.ZH_HANS_MO, locale.ZH_HANT_MO, locale.ES_SV, locale.ES_US, locale.ST, locale.SO_DJ, locale.AM, locale.SAQ, locale.ZH_HANT_HK, locale.DAV, locale.BM, locale.MER, locale.TEO, locale.SO, locale.IG, locale.OM, locale.YUE_HANS, locale.KLN, locale.ES_PR, locale.BHO, locale.ES_PA, locale.ES_DO, locale.KW, locale.MN_MONG_MN, locale.HAW, locale.MR, locale.ZU, locale.YO_BJ, locale.ZH_HANS_MY, locale.ROF, locale.FIL, locale.GV, locale.ES_MX, locale.ZH_HANT_MY:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 94 locales
	case locale.EN_TV, locale.EN_CC, locale.EN_GI, locale.EN_001, locale.EN_MP, locale.EN_VG, locale.EN, locale.EN_KI, locale.EN_SL, locale.EN_ER, locale.EN_UM, locale.EN_TZ, locale.EN_SH, locale.EN_HK, locale.EN_IL, locale.EN_GB, locale.EN_MG, locale.EN_CK, locale.EN_DG, locale.EN_KN, locale.EN_RW, locale.EN_BW, locale.EN_MY, locale.EN_NZ, locale.EN_VU, locale.EN_MO, locale.EN_CM, locale.EN_BB, locale.EN_WS, locale.EN_PN, locale.EN_AU, locale.EN_BM, locale.EN_FK, locale.EN_BS, locale.EN_MU, locale.EN_MT, locale.EN_AI, locale.EN_GG, locale.EN_NR, locale.EN_IO, locale.EN_SX, locale.EN_NA, locale.EN_BZ, locale.EN_BI, locale.EN_FJ, locale.EN_KE, locale.EN_PW, locale.EN_MH, locale.EN_TC, locale.EN_GM, locale.EN_ZW, locale.EN_NF, locale.EN_LS, locale.EN_DM, locale.EN_GD, locale.EN_VI, locale.EN_TK, locale.EN_AE, locale.EN_SZ, locale.EN_PH, locale.EN_GY, locale.EN_GH, locale.EN_PK, locale.EN_AG, locale.EN_JM, locale.EN_PR, locale.EN_TT, locale.EN_MW, locale.EN_CY, locale.EN_ZM, locale.EN_AS, locale.EN_IM, locale.EN_KY, locale.EN_LC, locale.EN_SC, locale.EN_TO, locale.EN_GS, locale.EN_NU, locale.EN_SB, locale.EN_SD, locale.EN_FM, locale.EN_SS, locale.EN_UG, locale.EN_IE, locale.EN_JE, locale.EN_PG, locale.EN_CX, locale.EN_MS, locale.EN_NG, locale.EN_GU, locale.EN_CA, locale.EN_LR, locale.EN_SG, locale.EN_VC:
		return FormatInfo{
			Symbol:           "LKR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 69 locales
	case locale.KK_KZ, locale.FF_LATN_GM, locale.FF_LATN_GW, locale.FF_LATN_GH, locale.FF_LATN_GN, locale.UK, locale.KSF, locale.BE, locale.KA, locale.LV, locale.PT_MZ, locale.YAV, locale.TK, locale.FF_LATN_SL, locale.PRG, locale.RU_BY, locale.RU, locale.CS, locale.FF_LATN_NG, locale.BG, locale.KK_CYRL, locale.BE_TARASK, locale.UZ_LATN, locale.RU_UA, locale.BR, locale.KK, locale.PT_TL, locale.CV, locale.RU_KZ, locale.TT, locale.RU_MD, locale.HT, locale.FF_LATN_NE, locale.DUA, locale.KEA, locale.PT_ST, locale.PT_LU, locale.PT_PT, locale.SAH, locale.RU_KG, locale.PT_AO, locale.PT_CV, locale.PT_MO, locale.SK, locale.SZL, locale.FF, locale.TG, locale.PL, locale.FF_LATN, locale.EO, locale.NMG, locale.UZ_CYRL, locale.FF_LATN_CM, locale.HY, locale.DYO, locale.FF_LATN_LR, locale.EWO, locale.HU, locale.PT_GW, locale.TZM, locale.FR_CA, locale.BAS, locale.PT_CH, locale.FF_LATN_BF, locale.UZ, locale.FF_LATN_MR, locale.KY, locale.SMN, locale.PT_GQ:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 59 locales
	case locale.ES, locale.CA, locale.HSB, locale.EL_CY, locale.EL_POLYTON, locale.NDS_NL, locale.RO_MD, locale.BS_CYRL, locale.CA_IT, locale.CA_ES_VALENCIA, locale.LIJ, locale.LLD, locale.SR_CYRL_XK, locale.AZ_LATN, locale.LN_AO, locale.KU, locale.DE, locale.IT_SM, locale.VI, locale.RO, locale.DSB, locale.SR_LATN_XK, locale.SR_LATN_BA, locale.BS, locale.ES_PH, locale.SR_CYRL, locale.EL, locale.DE_LU, locale.DE_IT, locale.SR_LATN_ME, locale.DA, locale.ES_IC, locale.SC, locale.SR_LATN, locale.SR_CYRL_ME, locale.AZ_CYRL, locale.DA_GL, locale.LN_CF, locale.SR_CYRL_BA, locale.AZ, locale.MK, locale.NDS, locale.BS_LATN, locale.IS, locale.AST, locale.ES_EA, locale.CA_FR, locale.IT, locale.LN, locale.DE_BE, locale.FR_MA, locale.LN_CG, locale.VMW, locale.GL, locale.LB, locale.CA_AD, locale.IT_VA, locale.SR, locale.FR_LU:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 43 locales
	case locale.FR_MR, locale.FR_TD, locale.FR_DZ, locale.FR, locale.FR_PF, locale.FR_BL, locale.FR_BJ, locale.FR_RW, locale.FR_DJ, locale.FR_GP, locale.FR_GF, locale.FR_BI, locale.FR_RE, locale.FR_GN, locale.FR_CM, locale.FR_PM, locale.FR_TG, locale.FR_NE, locale.FR_BF, locale.FR_VU, locale.FR_SY, locale.FR_ML, locale.FR_NC, locale.FR_SC, locale.FR_CF, locale.FR_CI, locale.FR_WF, locale.FR_HT, locale.FR_CD, locale.FR_MU, locale.FR_KM, locale.FR_SN, locale.FR_MQ, locale.FR_GA, locale.FR_GQ, locale.FR_MF, locale.FR_MG, locale.FR_BE, locale.FR_MC, locale.FR_CH, locale.FR_TN, locale.FR_CG, locale.FR_YT:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 22 locales
	case locale.AR_JO, locale.AR_IL, locale.AR_SS, locale.AR_KW, locale.AR_IQ, locale.AR_SA, locale.AR_SO, locale.AR_AE, locale.AR_DJ, locale.AR, locale.AR_EH, locale.AR_ER, locale.AR_YE, locale.AR_EG, locale.AR_OM, locale.AR_KM, locale.AR_QA, locale.AR_PS, locale.AR_TD, locale.AR_BH, locale.AR_SD, locale.AR_SY:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	// Group of 21 locales
	case locale.MGH, locale.MS_BN, locale.RW, locale.JV, locale.YRL_CO, locale.MS_ARAB_BN, locale.QU_BO, locale.KKJ, locale.SW_CD, locale.NNH, locale.FUR, locale.ES_AR, locale.WO, locale.YRL, locale.ES_CO, locale.PT, locale.KGP, locale.JGO, locale.IA, locale.YRL_VE, locale.ES_UY:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 16 locales
	case locale.KOK_LATN, locale.BN_IN, locale.GU, locale.HI, locale.TE, locale.DZ, locale.KXV_ORYA, locale.KXV_TELU, locale.TA, locale.SA, locale.PA, locale.PA_GURU, locale.KXV_DEVA, locale.XNR, locale.KXV, locale.KXV_LATN:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 12 locales
	case locale.FF_ADLM_GM, locale.FF_ADLM_NE, locale.FF_ADLM_BF, locale.FF_ADLM_LR, locale.FF_ADLM_NG, locale.FF_ADLM_SL, locale.FF_ADLM_GH, locale.FF_ADLM_SN, locale.FF_ADLM_MR, locale.FF_ADLM_GW, locale.FF_ADLM_CM, locale.FF_ADLM:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "⹁",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 10 locales
	case locale.EN_NO, locale.SQ, locale.EN_CZ, locale.EN_HU, locale.EN_PT, locale.EN_SE, locale.EN_FI, locale.SQ_XK, locale.EN_SK, locale.SQ_MK:
		return FormatInfo{
			Symbol:           "LKR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 9 locales
	case locale.SE_SE, locale.SE, locale.KSH, locale.SV, locale.SV_FI, locale.LT, locale.SV_AX, locale.SE_FI, locale.ET:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 9 locales
	case locale.TR, locale.MUA, locale.MS_ID, locale.ID, locale.ES_GQ, locale.ES_BO, locale.SU_LATN, locale.TR_CY, locale.SU:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 8 locales
	case locale.EN_RO, locale.EN_SI, locale.EN_ES, locale.EN_PL, locale.EN_IT, locale.EN_BE, locale.EN_DE, locale.EN_DK:
		return FormatInfo{
			Symbol:           "LKR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 8 locales
	case locale.NL_BQ, locale.NL_BE, locale.NL_CW, locale.ES_PY, locale.NL, locale.NL_AW, locale.NL_SX, locale.NL_SR:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 8 locales
	case locale.SHI_LATN, locale.SHI, locale.OC_ES, locale.OC, locale.ZGH, locale.AGQ, locale.SHI_TFNG, locale.KAB:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 7 locales
	case locale.BEZ, locale.KSB, locale.RWK, locale.KM, locale.LG, locale.SBP, locale.LUO:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 7 locales
	case locale.NR, locale.AF, locale.SS_SZ, locale.VE, locale.ES_CR, locale.AF_NA, locale.SS:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 6 locales
	case locale.AR_MR, locale.AR_MA, locale.AR_LY, locale.AR_TN, locale.AR_DZ, locale.AR_LB:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "\u200f#,##0.00 ¤;\u200f-#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "\u200e-",
		}
	// Group of 6 locales
	case locale.KL, locale.SG, locale.ES_VE, locale.LO, locale.ES_CL, locale.ES_EC:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,##0.00;¤-#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 6 locales
	case locale.SL, locale.FO, locale.HR, locale.FO_DK, locale.EU, locale.HR_BA:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 5 locales
	case locale.BGN_OM, locale.BGN_AF, locale.BGN_IR, locale.BGN_AE, locale.BGN:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: "٫",
			MinusSign:        "-",
		}
	// Group of 5 locales
	case locale.XOG, locale.ASA, locale.CE, locale.TPI, locale.MY:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 4 locales
	case locale.AS, locale.BRX, locale.NE, locale.NE_IN:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 4 locales
	case locale.GSW, locale.GSW_LI, locale.RM, locale.GSW_FR:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "−",
		}
	// Group of 4 locales
	case locale.NN, locale.NB, locale.NB_SJ, locale.NO:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00 ¤;-#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	// Group of 4 locales
	case locale.TS, locale.OS, locale.DE_AT, locale.OS_RU:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 4 locales
	case locale.TWQ, locale.SES, locale.KHQ, locale.DJE:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00¤",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.BN, locale.CCP_IN, locale.CCP:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##,##0.00¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 3 locales
	case locale.PS, locale.UZ_ARAB, locale.PS_PK:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "\u200e−",
		}
	// Group of 3 locales
	case locale.RN, locale.SEH, locale.LU:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00¤",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.EN_IN, locale.HI_LATN:
		return FormatInfo{
			Symbol:           "LKR",
			Format:           "¤#,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.IE, locale.BLO:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.IT_CH, locale.DE_CH:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00;¤-#,##0.00",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.KS_ARAB, locale.KS:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.MFE, locale.NSO:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.TN_BW, locale.TN:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,##0.00",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	// Group of 2 locales
	case locale.UR, locale.UR_IN:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	// Group of 2 locales
	case locale.WAE, locale.LMO:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "’",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.BAL_LATN:
		return FormatInfo{
			Symbol:           "SRLR",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.DE_LI:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_150:
		return FormatInfo{
			Symbol:           "LKR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_AT:
		return FormatInfo{
			Symbol:           "LKR",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_CH:
		return FormatInfo{
			Symbol:           "LKR",
			Format:           "¤ #,##0.00;¤-#,##0.00",
			GroupSeparator:   "’",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_FR:
		return FormatInfo{
			Symbol:           "LKR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_ID:
		return FormatInfo{
			Symbol:           "LKR",
			Format:           "¤#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_MV:
		return FormatInfo{
			Symbol:           "LKR",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.EN_NL:
		return FormatInfo{
			Symbol:           "LKR",
			Format:           "¤ #,##0.00;¤ -#,##0.00",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.EN_ZA:
		return FormatInfo{
			Symbol:           "LKR",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.FA:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "\u200e¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e−",
		}
	case locale.FA_AF:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e−",
		}
	case locale.FI:
		return FormatInfo{
			Symbol:           "LKR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "−",
		}
	case locale.FY:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00;¤ #,##0.00-",
			GroupSeparator:   ".",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.HE:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "\u200f#,##0.00 \u200f¤;\u200f-#,##0.00 \u200f¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case locale.LUY:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,##0.00;¤- #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.NQO:
		return FormatInfo{
			Symbol:           "ߟߞߙ",
			Format:           "¤ #,##0.00",
			GroupSeparator:   "،",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.PA_ARAB:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤ #,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "\u200e-",
		}
	case locale.SI:
		return FormatInfo{
			Symbol:           "රු.",
			Format:           "¤#,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.TA_LK:
		return FormatInfo{
			Symbol:           "Rs.",
			Format:           "¤#,##,##0.00",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	case locale.TOK:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,#0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.VEC:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   " ",
			DecimalSeparator: ",",
			MinusSign:        "-",
		}
	case locale.XH:
		return FormatInfo{
			Symbol:           "Rs",
			Format:           "¤#,##0.00",
			GroupSeparator:   " ",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	default:
		return FormatInfo{
			Symbol:           "LKR",
			Format:           "#,##0.00 ¤",
			GroupSeparator:   ",",
			DecimalSeparator: ".",
			MinusSign:        "-",
		}
	}
}
