// Code generated by currency_generator.go; DO NOT EDIT.

package currency

var _ Currency = SCR{}

type SCR struct{}

func (SCR) Code() string { return "SCR" }

func (SCR) Number() string { return "690" }

func (SCR) Name() string { return "Seychelles Rupee" }

func (SCR) MinorUnits() int { return 2 }

func (SCR) Symbol() string { return "₨" }

func (SCR) MinorUnitName() string { return "Cent" }

func (SCR) MinorUnitSymbol() string { return "¢" }
