// Code generated by currency_generator.go; DO NOT EDIT.

package currency

var _ Currency = XBA{}

type XBA struct{}

func (XBA) Code() string { return "XBA" }

func (XBA) Number() string { return "955" }

func (XBA) Name() string { return "Bond Markets Unit European Composite Unit (EURCO)" }

func (XBA) MinorUnits() int { return 0 }

func (XBA) Symbol() string { return "XBA" }

func (XBA) MinorUnitName() string { return "" }

func (XBA) MinorUnitSymbol() string { return "" }
